import { normalize } from '@std/path';
import { normalizeSlashes } from './path.ts';

const RELEASE_EVIDENCE_PATHS = Object.freeze({
  prefixes: ['docs/release/', 'vendor/', 'site/app/data/_generated-'],
  exact: [
    'deno.lock',
  ],
});

function normalizeGitPath(path: string): string {
  return normalizeSlashes(normalize(path)).replace(/^\.\//, '');
}

export function parsePorcelainPath(line: string): string {
  const raw = line.slice(3).trim();
  const renamed = raw.includes(' -> ') ? raw.slice(raw.lastIndexOf(' -> ') + 4) : raw;
  return normalizeGitPath(renamed.replace(/^"|"$/g, ''));
}

function isReleaseEvidencePath(path: string): boolean {
  const normalized = normalizeGitPath(path);
  return RELEASE_EVIDENCE_PATHS.exact.includes(normalized) ||
    RELEASE_EVIDENCE_PATHS.prefixes.some((prefix) => normalized.startsWith(prefix));
}

export function filterNonEvidenceDirty(status: string): string[] {
  return status.split(/\r?\n/).filter((line) =>
    line.trim() !== '' && !isReleaseEvidencePath(parsePorcelainPath(line))
  );
}

/**
 * Refuse to continue when the worktree carries changes outside the generated
 * release-evidence allowlist. `refusal` is the caller-specific first line of
 * the thrown error; the dirty paths follow on subsequent lines.
 */
export async function assertCleanWorktree(refusal: string): Promise<void> {
  const output = await new Deno.Command('git', {
    args: ['status', '--porcelain'],
    stdout: 'piped',
    stderr: 'piped',
  }).output();
  if (!output.success) {
    throw new Error(`git status failed with exit code ${output.code}`);
  }
  // Release evidence files are generated by the release flow itself; any
  // changes under docs/release/ should not block releasing or publishing.
  const nonEvidenceDirty = filterNonEvidenceDirty(new TextDecoder().decode(output.stdout));
  if (nonEvidenceDirty.length > 0) {
    throw new Error(`${refusal}:\n${nonEvidenceDirty.join('\n')}`);
  }
}
