#!/bin/sh
#
# openElement pre-commit hook. Format/lint are owned by the Deno toolchain
# directly; heavier gates run pre-push and in CI.
#
# Install: deno task hooks:install

set -e

deno fmt --check
deno lint
