/**
 * Generate the per-article source-freshness map from the committed manifest.
 *
 * The build is hermetic: dates come from `www/lib/content-dates.json`, never
 * from Git, so the same source tree and lockfile produce the same output with
 * no network, no remote and no `.git` present. The manifest itself is
 * refreshed deliberately by `check-content-dates.ts --write` when sources
 * move; this generator only projects it into the module the app imports.
 *
 * Output `www/app/data/_generated-content-meta.ts` (gitignored) maps
 * `<collection>/<slug>` to `{ en, zh }` ISO dates; `--check` regenerates in
 * memory and fails on drift.
 */
import { fromFileUrl, join } from '@std/path';

const repoRoot = fromFileUrl(new URL('../../', import.meta.url));
const manifestFile = join(repoRoot, 'www/lib/content-dates.json');
const outFile = join(repoRoot, 'www/app/data/_generated-content-meta.ts');

interface ContentDatesManifest {
  generatedFrom: string;
  articles: Record<string, { en: string; zh: string }>;
}

let manifest: ContentDatesManifest;
try {
  manifest = JSON.parse(await Deno.readTextFile(manifestFile)) as ContentDatesManifest;
} catch {
  throw new Error(
    `generate-site-content-meta: cannot read ${manifestFile}; ` +
      'refresh it with deno task --cwd tools/repo content-dates:refresh',
  );
}
if (
  typeof manifest.generatedFrom !== 'string' ||
  manifest.articles === null ||
  typeof manifest.articles !== 'object'
) {
  throw new Error(`generate-site-content-meta: ${manifestFile} is malformed`);
}

/** ISO date or the explicit 'uncommitted' sentinel (render layer hides it). */
const STAMP = /^(?:\d{4}-\d{2}-\d{2}|uncommitted)$/;
for (const [slug, stamps] of Object.entries(manifest.articles)) {
  if (
    stamps === null || typeof stamps !== 'object' ||
    !STAMP.test(stamps.en) || !STAMP.test(stamps.zh)
  ) {
    throw new Error(
      `generate-site-content-meta: bad stamps for ${slug}: ${JSON.stringify(stamps)}`,
    );
  }
}

const meta: Record<string, { en: string; zh: string }> = {};
for (const slug of Object.keys(manifest.articles).sort()) {
  const { en, zh } = manifest.articles[slug];
  meta[slug] = { en, zh };
}

const generated =
  `// Auto-generated by tools/repo/generate-site-content-meta.ts from www/lib/content-dates.json - do not edit.

/** Last-commit ISO date per article source, keyed by \`<collection>/<slug>\`. */
export const contentMeta: Record<string, { en: string; zh: string }> = ${
    JSON.stringify(meta, null, 2)
  };
`;

if (Deno.args.includes('--check')) {
  let current = '';
  try {
    current = await Deno.readTextFile(outFile);
  } catch {
    // Missing file is drift; fall through to the mismatch path.
  }
  if (current !== generated) {
    console.error(
      'site content meta drift: regenerate with deno task --cwd tools/repo generate:site-content-meta',
    );
    Deno.exit(1);
  }
  console.log('site content meta check passed.');
} else {
  await Deno.writeTextFile(outFile, generated);
  console.log(`site content meta written: ${Object.keys(meta).length} articles.`);
}
