/**
 * Generate the site data modules required by tests, the site check tools and the
 * site build on a clean clone.
 *
 * Emits, from the checked-in content collections:
 *   www/app/data/_generated-guide-data.ts
 *   www/app/data/_generated-architecture-data.ts
 *   www/app/data/_generated-blog-data.ts
 * and, from docs/release/release-state.json:
 *   www/app/data/_generated-release-line.ts
 *
 * The remaining modules under www/app/data/ (_generated-api-reference.ts,
 * version.ts) are consumed as ordinary checked-in modules; the API reference
 * has its own `deno task generate:api-reference` gate.
 *
 * `--check` regenerates in memory and fails on drift.
 */
import {
  loadCollectionData,
  writeBlogDataModule,
  writeCollectionDataModule,
} from '../../www/lib/content.ts';
import { blogCollection, prepareBlogPosts } from '../../www/lib/blog.ts';
import { fromFileUrl, join } from '@std/path';
import { articleCollections } from '../../www/content-collections.ts';

const siteRoot = fromFileUrl(new URL('../../www/', import.meta.url));

const outputs = new Map<string, string>();
for (const name of ['guide', 'architecture'] as const) {
  const options = {
    ...articleCollections[name],
    contentDir: join(siteRoot, articleCollections[name].contentDir),
  };
  const entries = await loadCollectionData(name, options);
  const output = writeCollectionDataModule(name, entries, options);
  outputs.set(join(siteRoot, `app/data/_generated-${name}-data.ts`), output);
}

const blogOptions = { ...blogCollection, contentDir: join(siteRoot, blogCollection.contentDir) };
const blogEntries = await loadCollectionData('blog', blogOptions);
outputs.set(
  join(siteRoot, 'app/data/_generated-blog-data.ts'),
  writeBlogDataModule(prepareBlogPosts(blogEntries)),
);

// Release-line truth, derived from docs/release/release-state.json (the
// registry-verified source of truth) so site copy about the source line
// flips automatically when the release train publishes — no manual wording
// sweep. Consumed by www/app/data/version.ts.
const releaseState = JSON.parse(
  await Deno.readTextFile(join(siteRoot, '../docs/release/release-state.json')),
) as {
  sourceVersion: string;
  packages: Array<{ name: string; registry: Record<string, string | undefined> }>;
};
const sourceVersion = releaseState.sourceVersion;
const alphaResolutions = releaseState.packages.map((pkg) => pkg.registry.alpha);
// The source line counts as published only when EVERY package's @alpha
// dist-tag resolves to it — a partial train must still read as unpublished.
const sourceLinePublished = alphaResolutions.every((v) => v === sourceVersion);
const createEntry = releaseState.packages.find((pkg) => pkg.name === '@openelement/create');
const alphaResolvesTo = createEntry?.registry.alpha ?? 'unknown';
outputs.set(
  join(siteRoot, 'app/data/_generated-release-line.ts'),
  `// GENERATED by tools/repo/generate-site-content-data.ts from
// docs/release/release-state.json — do not edit by hand. Regenerate with
// \`deno task generate:site-content-data\` (part of site:build).
export const SOURCE_VERSION = '${sourceVersion}';
export const SOURCE_LINE_PUBLISHED = ${sourceLinePublished};
export const ALPHA_RESOLVES_TO = '${alphaResolvesTo}';
`,
);

if (Deno.args.includes('--check')) {
  const drifted: string[] = [];
  for (const [path, expected] of outputs) {
    let current = '';
    try {
      current = await Deno.readTextFile(path);
    } catch {
      // Missing file is drift; fall through to the mismatch path.
    }
    if (current !== expected) drifted.push(path);
  }
  if (drifted.length > 0) {
    console.error(
      'site content data drift: regenerate with deno task --cwd tools/repo generate:site-content-data',
    );
    for (const path of drifted) console.error(`  ${path}`);
    Deno.exit(1);
  }
  console.log('site content data check passed.');
} else {
  for (const [path, output] of outputs) await Deno.writeTextFile(path, output);
  console.log(`site content data written: ${outputs.size} modules.`);
}
