/**
 * Generate the per-article source-freshness map.
 *
 * For every guide/architecture article slug, records the last-commit date
 * (`git log --follow -1 --format=%cs`) of its en and zh Markdown sources
 * separately — a zh-only edit must not refresh the en stamp, and --follow
 * keeps the stamp across pure moves. Untracked sources (a new article not
 * yet committed) record the explicit sentinel 'uncommitted' instead of a
 * date: the render layer hides the freshness row for it, so a machine/CI
 * date difference can never false-red the drift check.
 *
 * Shallow clones collapse history and would flatten every stamp onto one
 * date — fail closed instead of generating misleading data.
 *
 * Output `www/app/data/_generated-content-meta.ts` (gitignored) maps
 * `<collection>/<slug>` to `{ en, zh }` ISO dates; the article page model
 * projects the render locale's stamp into the reading-shell meta row.
 *
 * `--check` regenerates in memory and fails on drift.
 */
import { fromFileUrl, join } from '@std/path';

const repoRoot = fromFileUrl(new URL('../../', import.meta.url));
const contentRoot = join(repoRoot, 'www/content/docs');
const outFile = join(repoRoot, 'www/app/data/_generated-content-meta.ts');

const COLLECTIONS = ['guide', 'architecture'] as const;

async function gitDate(args: string[]): Promise<string> {
  const command = new Deno.Command('git', {
    args,
    cwd: repoRoot,
    stdout: 'piped',
    stderr: 'null',
  });
  const { code, stdout } = await command.output();
  if (code !== 0) return '';
  return new TextDecoder().decode(stdout).trim();
}

const headDate = await gitDate(['log', '-1', '--format=%cs']);
if (!headDate) throw new Error('git HEAD date unavailable — run inside the repository checkout');

const shallow = await gitDate(['rev-parse', '--is-shallow-repository']);
if (shallow === 'true') {
  throw new Error(
    'generate-site-content-meta: shallow clone collapses history — every stamp would flatten onto one date. Use a full clone.',
  );
}

/** Sentinel for sources git does not track yet; the render layer hides the row for it. */
const UNCOMMITTED = 'uncommitted';

const meta: Record<string, { en: string; zh: string }> = {};
for (const collection of COLLECTIONS) {
  const slugs = new Set<string>();
  for await (const entry of Deno.readDir(join(contentRoot, collection))) {
    if (!entry.isFile || !entry.name.endsWith('.md')) continue;
    slugs.add(entry.name.replace(/\.zh\.md$/, '').replace(/\.md$/, ''));
  }
  for (const slug of [...slugs].sort()) {
    const rel = `www/content/docs/${collection}`;
    const en = await gitDate(['log', '--follow', '-1', '--format=%cs', '--', `${rel}/${slug}.md`]);
    const zh = await gitDate(['log', '--follow', '-1', '--format=%cs', '--', `${rel}/${slug}.zh.md`]);
    meta[`${collection}/${slug}`] = { en: en || UNCOMMITTED, zh: zh || en || UNCOMMITTED };
  }
}

const generated =
  `// Auto-generated by tools/repo/generate-site-content-meta.ts from git log dates - do not edit.

/** Last-commit ISO date per article source, keyed by \`<collection>/<slug>\`. */
export const contentMeta: Record<string, { en: string; zh: string }> = ${
    JSON.stringify(meta, null, 2)
  };
`;

if (Deno.args.includes('--check')) {
  let current = '';
  try {
    current = await Deno.readTextFile(outFile);
  } catch {
    // Missing file is drift; fall through to the mismatch path.
  }
  if (current !== generated) {
    console.error(
      'site content meta drift: regenerate with deno task --cwd tools/repo generate:site-content-meta',
    );
    Deno.exit(1);
  }
  console.log('site content meta check passed.');
} else {
  await Deno.writeTextFile(outFile, generated);
  console.log(`site content meta written: ${Object.keys(meta).length} articles.`);
}
