/**
 * Generate the per-article source-freshness map.
 *
 * For every guide/architecture article slug, records the last-commit date
 * (`git log -1 --format=%cs`) of its en and zh Markdown sources separately —
 * a zh-only edit must not refresh the en stamp. Untracked sources (a new
 * article not yet committed) fall back to the HEAD date so generation stays
 * deterministic and needs no manual step.
 *
 * Output `www/app/data/_generated-content-meta.ts` (gitignored) maps
 * `<collection>/<slug>` to `{ en, zh }` ISO dates; the article page model
 * projects the render locale's stamp into the reading-shell meta row.
 *
 * `--check` regenerates in memory and fails on drift.
 */
import { fromFileUrl, join } from '@std/path';

const repoRoot = fromFileUrl(new URL('../../', import.meta.url));
const contentRoot = join(repoRoot, 'www/content/docs');
const outFile = join(repoRoot, 'www/app/data/_generated-content-meta.ts');

const COLLECTIONS = ['guide', 'architecture'] as const;

async function gitDate(args: string[]): Promise<string> {
  const command = new Deno.Command('git', {
    args,
    cwd: repoRoot,
    stdout: 'piped',
    stderr: 'null',
  });
  const { code, stdout } = await command.output();
  if (code !== 0) return '';
  return new TextDecoder().decode(stdout).trim();
}

const headDate = await gitDate(['log', '-1', '--format=%cs']);
if (!headDate) throw new Error('git HEAD date unavailable — run inside the repository checkout');

const meta: Record<string, { en: string; zh: string }> = {};
for (const collection of COLLECTIONS) {
  const slugs = new Set<string>();
  for await (const entry of Deno.readDir(join(contentRoot, collection))) {
    if (!entry.isFile || !entry.name.endsWith('.md')) continue;
    slugs.add(entry.name.replace(/\.zh\.md$/, '').replace(/\.md$/, ''));
  }
  for (const slug of [...slugs].sort()) {
    const rel = `www/content/docs/${collection}`;
    const en = await gitDate(['log', '-1', '--format=%cs', '--', `${rel}/${slug}.md`]);
    const zh = await gitDate(['log', '-1', '--format=%cs', '--', `${rel}/${slug}.zh.md`]);
    meta[`${collection}/${slug}`] = { en: en || headDate, zh: zh || en || headDate };
  }
}

const generated = `// Auto-generated by tools/repo/generate-site-content-meta.ts from git log dates - do not edit.

/** Last-commit ISO date per article source, keyed by \`<collection>/<slug>\`. */
export const contentMeta: Record<string, { en: string; zh: string }> = ${
  JSON.stringify(meta, null, 2)
};
`;

if (Deno.args.includes('--check')) {
  let current = '';
  try {
    current = await Deno.readTextFile(outFile);
  } catch {
    // Missing file is drift; fall through to the mismatch path.
  }
  if (current !== generated) {
    console.error('site content meta drift: regenerate with deno task --cwd tools/repo generate:site-content-meta');
    Deno.exit(1);
  }
  console.log('site content meta check passed.');
} else {
  await Deno.writeTextFile(outFile, generated);
  console.log(`site content meta written: ${Object.keys(meta).length} articles.`);
}
