/**
 * Generate the site navigation data module from the route `meta` exports.
 *
 * Router 1.0 deliberately does not synthesize app-shell nav data (the
 * generated entry carries empty defaults); the Site owns its own navigation.
 * Route files are the single source of truth via
 * `export const meta = { section, label, order }`, and this generator projects
 * them into `apps/site/app/data/_generated-nav-data.ts` for the app shell:
 *
 *   navSections — grouped sidebar tree consumed by the open-layout sidebar
 *   headerNav   — the curated top-level header links, filtered to real routes
 *
 * `--check` regenerates in memory and fails on drift. The module is generated
 * (gitignored) and rebuilt before the site build.
 */
import { walk } from '@std/fs/walk';
import { fromFileUrl, join } from '@std/path';

const siteRoot = fromFileUrl(new URL('../../apps/site/', import.meta.url));
const routesDir = join(siteRoot, 'app/routes');
const outFile = join(siteRoot, 'app/data/_generated-nav-data.ts');

const SECTION_ORDER = [
  'Quick Start',
  'Guide',
  'Core',
  'Production',
  'Principles',
  'Reference',
  'History',
  'Project',
];

/** Curated header links; each must resolve to a scanned static route. */
const HEADER_NAV: ReadonlyArray<{ path: string; label: string }> = [
  { path: '/docs', label: 'Docs' },
  { path: '/guide/core-concepts', label: 'Guide' },
  { path: '/architecture/architecture', label: 'Architecture' },
  { path: '/apilist', label: 'API' },
  { path: '/blog', label: 'Blog' },
  { path: '/roadmap', label: 'Roadmap' },
  { path: '/changelog', label: 'Changelog' },
];

interface RouteMeta {
  section: string;
  label: string;
  order: number;
}

function fileToRoutePath(relativePath: string): string | undefined {
  const withoutExtension = relativePath.replace(/\.tsx?$/, '');
  const segments = withoutExtension.split('/');
  const mapped: string[] = [];
  for (const segment of segments) {
    if (segment === 'index') continue;
    if (segment.startsWith('[')) return undefined; // dynamic routes are not nav
    mapped.push(segment);
  }
  return `/${mapped.join('/')}`;
}

function parseMeta(source: string): RouteMeta | undefined {
  const object = /export const meta\s*=\s*\{([^}]*)\}/.exec(source)?.[1];
  if (!object) return undefined;
  const section = /section:\s*'([^']*)'/.exec(object)?.[1];
  const label = /label:\s*'([^']*)'/.exec(object)?.[1];
  const order = /order:\s*(-?\d+)/.exec(object)?.[1];
  if (label === undefined || order === undefined) return undefined;
  return { section: section ?? '', label, order: Number(order) };
}

interface NavItem {
  path: string;
  label: string;
  order: number;
}

async function collect(): Promise<{ routes: string[]; sections: Map<string, NavItem[]> }> {
  const routes: string[] = [];
  const sections = new Map<string, NavItem[]>();
  for await (const entry of walk(routesDir, { exts: ['.tsx'], includeDirs: false })) {
    const relativePath = entry.path.slice(routesDir.length + 1);
    const path = fileToRoutePath(relativePath);
    if (!path) continue;
    routes.push(path);
    const meta = parseMeta(await Deno.readTextFile(entry.path));
    if (!meta) continue;
    const list = sections.get(meta.section) ?? [];
    list.push({ path, label: meta.label, order: meta.order });
    sections.set(meta.section, list);
  }
  for (const list of sections.values()) {
    list.sort((a, b) => a.order - b.order || (a.label < b.label ? -1 : 1));
  }
  return { routes, sections };
}

function render(
  sections: Map<string, NavItem[]>,
  routes: string[],
): string {
  const orderedSections: Array<{ section: string; items: NavItem[] }> = [];
  for (const section of SECTION_ORDER) {
    const items = sections.get(section);
    if (items?.length) orderedSections.push({ section, items });
  }
  // Any section not in the canonical order (or the nameless group) is appended
  // deterministically so a new section cannot silently disappear.
  for (const [section, items] of [...sections.entries()].sort()) {
    if (SECTION_ORDER.includes(section)) continue;
    if (items.length) orderedSections.push({ section, items });
  }
  const headerNav = HEADER_NAV.filter((link) => routes.includes(link.path)).map((link) => ({
    href: link.path,
    label: link.label,
  }));
  const missing = HEADER_NAV.filter((link) => !routes.includes(link.path));
  if (missing.length > 0) {
    throw new Error(
      `headerNav targets missing routes: ${missing.map((link) => link.path).join(', ')}`,
    );
  }
  return `// Auto-generated by tools/repo/generate-site-nav.ts from route meta - do not edit.
import type { HeaderNavLink, NavSection } from '../site-ui/open-layout-navigation.ts';

export const navSections: NavSection[] = ${
    JSON.stringify(
      orderedSections.map((section) => ({
        section: section.section,
        items: section.items.map((item) => ({ path: item.path, label: item.label })),
      })),
      null,
      2,
    )
  };

export const headerNav: HeaderNavLink[] = ${JSON.stringify(headerNav, null, 2)};
`;
}

const { routes, sections } = await collect();
const generated = render(sections, routes);
const check = Deno.args.includes('--check');

if (check) {
  let current = '';
  try {
    current = await Deno.readTextFile(outFile);
  } catch {
    // Missing file is drift; fall through to the mismatch path.
  }
  if (current !== generated) {
    console.error('site nav drift: regenerate with deno task --cwd tools/repo generate:site-nav');
    Deno.exit(1);
  }
  console.log('site nav check passed.');
} else {
  await Deno.writeTextFile(outFile, generated);
  console.log(`site nav written: ${routes.length} routes, ${sections.size} sections.`);
}
