/**
 * One-knob release version bump (#1415).
 *
 * A version bump is SIX points, not one, and hand-editing them burned two
 * release rounds in alpha.2:
 *
 *   1-4. packages/{element,router,create,ui}/deno.json `version`
 *   5.    packages/create/src/version.ts `CREATE_VERSION`
 *   6.    the four fixture `deno.lock` files (they record
 *         `jsr:@openelement/<pkg>@<version>` workspace links), regenerated by
 *         `deno task --cwd tools/repo fixtures:locks:update`
 *
 * Usage:
 *   deno task version-bump 1.0.0-alpha.4              # dry run (default)
 *   deno task version-bump 1.0.0-alpha.4 --write      # apply, then regenerate locks
 *
 * Dry run prints the diff for points 1-5 and the PREDICTED lock diff for
 * point 6 (the lock entries are pure `@<version>` links), so the six points
 * can be reviewed before anything is written. `--write` performs the edits,
 * runs `fixtures:locks:update`, and fails when the six points do not end up
 * carrying one version.
 *
 * The existing gates stay the second line of defence: `check-package-graph`
 * cross-asserts CREATE_VERSION and every package version against
 * docs/release/release-state.json, and `check-fixture-locks` re-derives the
 * lock universes. Registry truth (release-state.json) is release bookkeeping
 * and is deliberately NOT touched here.
 */

import { parse } from '@std/semver';
import { join } from '@std/path';
import { FIXTURE_LOCKS } from './check-fixture-locks.ts';

/** Packages whose `deno.json` carries the release line version. */
export const PACKAGE_CONFIGS: readonly string[] = [
  'packages/element/deno.json',
  'packages/router/deno.json',
  'packages/create/deno.json',
  'packages/ui/deno.json',
];

/** The embedded create-CLI version anchor. */
export const VERSION_SOURCE = 'packages/create/src/version.ts';

/** Every registered fixture lock, repo-relative. */
export const LOCK_FILES: readonly string[] = FIXTURE_LOCKS.map((entry) =>
  `tests/fixtures/${entry.fixture}/deno.lock`
);

/** One pending text edit. */
export interface VersionEdit {
  /** Repo-relative path. */
  path: string;
  /** Which of the six points this edit belongs to. */
  point: 'package-config' | 'create-anchor' | 'fixture-lock';
  before: string;
  after: string;
}

export interface VersionBumpPlan {
  /** Version the tree carries now (from packages/element/deno.json). */
  currentVersion: string;
  targetVersion: string;
  /** Package-config + anchor edits (points 1-5). */
  edits: VersionEdit[];
  /** Lock files whose predicted content differs (point 6). */
  lockEdits: VersionEdit[];
}

/** Validate the requested release version. Returns an error message or null. */
export function validateVersion(version: string): string | null {
  try {
    parse(version);
  } catch {
    return `"${version}" is not a valid semver version (expected e.g. 1.0.0-alpha.4).`;
  }
  if (!/^\d+\.\d+\.\d+/.test(version)) {
    return `"${version}" must be a concrete version, not a range (e.g. 1.0.0-alpha.4).`;
  }
  return null;
}

/** The version a package deno.json declares, or null when absent/invalid. */
export function readConfigVersion(text: string): string | null {
  try {
    const parsed = JSON.parse(text) as { version?: unknown };
    return typeof parsed.version === 'string' ? parsed.version : null;
  } catch {
    return null;
  }
}

/** Rewrite a package deno.json `version` field in place, preserving formatting. */
export function rewriteConfigVersion(text: string, from: string, to: string): string {
  const pattern = new RegExp(`("version"\\s*:\\s*")${escapeRegExp(from)}(")`);
  if (!pattern.test(text)) {
    throw new Error(`package deno.json does not declare version "${from}"`);
  }
  return text.replace(pattern, `$1${to}$2`);
}

/** Rewrite the CREATE_VERSION anchor, leaving VITE_STARTER_PIN alone. */
export function rewriteCreateVersion(text: string, from: string, to: string): string {
  const pattern = new RegExp(`(CREATE_VERSION = ')${escapeRegExp(from)}(')`);
  if (!pattern.test(text)) {
    throw new Error(`CREATE_VERSION anchor for "${from}" not found in ${VERSION_SOURCE}`);
  }
  return text.replace(pattern, `$1${to}$2`);
}

/**
 * Predicted lock content: the registered locks record the release line as
 * `jsr:@openelement/<pkg>@<version>` workspace links, so the only bytes the
 * bump moves are the `@<version>` tokens. `--write` still regenerates the
 * locks from their declarations (`fixtures:locks:update`), which is the
 * authority; this prediction is what the dry run reviews.
 */
export function rewriteLockVersion(text: string, from: string, to: string): string {
  return text.split(`@${from}`).join(`@${to}`);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/** Build the six-point plan without touching the filesystem beyond reads. */
export async function planVersionBump(
  root: string,
  targetVersion: string,
): Promise<VersionBumpPlan> {
  const elementConfig = await Deno.readTextFile(join(root, PACKAGE_CONFIGS[0]));
  const currentVersion = readConfigVersion(elementConfig);
  if (currentVersion === null) {
    throw new Error(`${PACKAGE_CONFIGS[0]} declares no version`);
  }

  const edits: VersionEdit[] = [];
  for (const path of PACKAGE_CONFIGS) {
    const before = await Deno.readTextFile(join(root, path));
    const after = rewriteConfigVersion(before, currentVersion, targetVersion);
    if (after !== before) {
      edits.push({ path, point: 'package-config', before, after });
    }
  }

  const anchorBefore = await Deno.readTextFile(join(root, VERSION_SOURCE));
  const anchorAfter = rewriteCreateVersion(anchorBefore, currentVersion, targetVersion);
  if (anchorAfter !== anchorBefore) {
    edits.push({
      path: VERSION_SOURCE,
      point: 'create-anchor',
      before: anchorBefore,
      after: anchorAfter,
    });
  }

  const lockEdits: VersionEdit[] = [];
  for (const path of LOCK_FILES) {
    const before = await Deno.readTextFile(join(root, path)).catch(() => null);
    if (before === null) continue;
    const after = rewriteLockVersion(before, currentVersion, targetVersion);
    if (after !== before) {
      lockEdits.push({ path, point: 'fixture-lock', before, after });
    }
  }

  return { currentVersion, targetVersion, edits, lockEdits };
}

/**
 * The six points after a bump must all carry one version. Returns one message
 * per point that does not (empty when the tree is consistent).
 */
export async function inconsistencyFailures(
  root: string,
  expected: string,
): Promise<string[]> {
  const failures: string[] = [];
  for (const path of PACKAGE_CONFIGS) {
    const version = readConfigVersion(await Deno.readTextFile(join(root, path)));
    if (version !== expected) {
      failures.push(`${path}: version ${String(version)} != ${expected}`);
    }
  }
  const anchor = await Deno.readTextFile(join(root, VERSION_SOURCE));
  const match = anchor.match(/CREATE_VERSION = '([^']+)'/u);
  if (match?.[1] !== expected) {
    failures.push(`${VERSION_SOURCE}: CREATE_VERSION ${String(match?.[1])} != ${expected}`);
  }
  for (const path of LOCK_FILES) {
    const text = await Deno.readTextFile(join(root, path)).catch(() => null);
    if (text === null) {
      failures.push(`${path}: missing`);
      continue;
    }
    if (text.includes(`@${expected}`)) continue;
    // router-nitro and web-component-interop resolve no @openelement link.
    if (!text.includes('jsr:@openelement/')) continue;
    failures.push(`${path}: no @${expected} workspace link`);
  }
  return failures;
}

/** Render a line diff (only the changed lines, plus a header). */
export function renderDiff(edit: VersionEdit, limit = 12): string {
  const before = edit.before.split('\n');
  const after = edit.after.split('\n');
  const lines = [`--- ${edit.path} (${edit.point})`, `+++ ${edit.path}`];
  let shown = 0;
  for (let index = 0; index < Math.max(before.length, after.length); index++) {
    if (before[index] === after[index]) continue;
    if (shown >= limit) {
      lines.push('  … (more changes elided)');
      break;
    }
    lines.push(`- ${before[index] ?? ''}`);
    lines.push(`+ ${after[index] ?? ''}`);
    shown += 1;
  }
  return lines.join('\n');
}

async function runFixtureLockUpdate(root: string): Promise<number> {
  const status = await new Deno.Command(Deno.execPath(), {
    args: ['task', '--cwd', 'tools/repo', 'fixtures:locks:update'],
    cwd: root,
    stdin: 'null',
    stdout: 'inherit',
    stderr: 'inherit',
  }).spawn().status;
  return status.code;
}

async function main(): Promise<void> {
  const args = Deno.args.filter((arg) => !arg.startsWith('--'));
  const write = Deno.args.includes('--write');
  const root = Deno.cwd();
  const target = args[0];
  if (!target) {
    console.error(
      'usage: deno task version-bump <version> [--write]\n' +
        '       (dry run by default; --write applies the six-point update)',
    );
    Deno.exit(2);
  }
  const invalid = validateVersion(target);
  if (invalid) {
    console.error(`version-bump: ${invalid}`);
    Deno.exit(2);
  }

  const plan = await planVersionBump(root, target);
  if (plan.currentVersion === target) {
    console.log(`version-bump: tree already at ${target}; nothing to do.`);
    return;
  }

  console.log(
    `version-bump: ${plan.currentVersion} -> ${target} (${write ? 'WRITE' : 'dry run'})`,
  );
  for (const edit of plan.edits) console.log(renderDiff(edit));
  for (const edit of plan.lockEdits) console.log(renderDiff(edit));
  console.log(
    `\npoints: ${plan.edits.length} file(s) edited (4 package configs + create anchor); ` +
      `${plan.lockEdits.length}/${LOCK_FILES.length} fixture lock(s) carry @${plan.currentVersion}`,
  );

  if (!write) {
    console.log(
      '\ndry run: nothing written. Apply with `--write`, which also runs ' +
        '`deno task --cwd tools/repo fixtures:locks:update` for point 6.',
    );
    return;
  }

  for (const edit of [...plan.edits, ...plan.lockEdits]) {
    await Deno.writeTextFile(join(root, edit.path), edit.after);
    console.log(`[version-bump] wrote ${edit.path}`);
  }

  console.log('[version-bump] regenerating fixture locks (point 6)…');
  const code = await runFixtureLockUpdate(root);
  if (code !== 0) {
    console.error(`version-bump: fixtures:locks:update exited ${code}`);
    Deno.exit(1);
  }

  const failures = await inconsistencyFailures(root, target);
  if (failures.length > 0) {
    console.error(
      `version-bump: six points are NOT consistent after the bump:\n  ${failures.join('\n  ')}`,
    );
    Deno.exit(1);
  }
  console.log(
    `version-bump: six points consistent at ${target}. ` +
      'Still required (release bookkeeping, not this knob): ' +
      'docs/release/release-state.json sourceVersion/activeTarget + CHANGELOG entry.',
  );
}

if (import.meta.main) {
  try {
    await main();
  } catch (error) {
    console.error(`version-bump: ${error instanceof Error ? error.message : String(error)}`);
    Deno.exit(1);
  }
}
