// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/compiled-grammar.md - do not edit.
import { definePage } from '@openelement/router';
import GuideCompiledGrammarPage from '../../components/article-routes/guide-compiled-grammar.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideCompiledGrammarPage, {
  head: ({ locale }) => articlePageHead('guide', 'compiled-grammar', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'compiled-grammar', locale) };
  },
});
