// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/configuration.md - do not edit.
import { definePage } from '@openelement/router';
import GuideConfigurationPage from '../../components/article-routes/guide-configuration.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideConfigurationPage, {
  head: ({ locale }) => articlePageHead('guide', 'configuration', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'configuration', locale) };
  },
});
