// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/core-concepts.md - do not edit.
import { definePage } from '@openelement/router';
import GuideCoreConceptsPage from '../../components/article-routes/guide-core-concepts.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideCoreConceptsPage, {
  head: ({ locale }) => articlePageHead('guide', 'core-concepts', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'core-concepts', locale) };
  },
});
