// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/deployment.md - do not edit.
import { definePage } from '@openelement/router';
import GuideDeploymentPage from '../../components/article-routes/guide-deployment.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideDeploymentPage, {
  head: ({ locale }) => articlePageHead('guide', 'deployment', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'deployment', locale) };
  },
});
