// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/deploy-cloudflare.md - do not edit.
import { definePage } from '@openelement/router';
import GuideDeployCloudflarePage from '../../components/article-routes/guide-deploy-cloudflare.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideDeployCloudflarePage, {
  head: ({ locale }) => articlePageHead('guide', 'deploy-cloudflare', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'deploy-cloudflare', locale) };
  },
});
