// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/islands-and-ssr.md - do not edit.
import { definePage } from '@openelement/router';
import GuideIslandsAndSsrPage from '../../components/article-routes/guide-islands-and-ssr.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideIslandsAndSsrPage, {
  head: ({ locale }) => articlePageHead('guide', 'islands-and-ssr', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'islands-and-ssr', locale) };
  },
});
