// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/mdx.md - do not edit.
import { definePage } from '@openelement/router';
import GuideMdxPage from '../../components/article-routes/guide-mdx.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideMdxPage, {
  head: ({ locale }) => articlePageHead('guide', 'mdx', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'mdx', locale) };
  },
});
