// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/routing-and-data.md - do not edit.
import { definePage } from '@openelement/router';
import GuideRoutingAndDataPage from '../../components/article-routes/guide-routing-and-data.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideRoutingAndDataPage, {
  head: ({ locale }) => articlePageHead('guide', 'routing-and-data', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'routing-and-data', locale) };
  },
});
