// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/security.md - do not edit.
import { definePage } from '@openelement/router';
import GuideSecurityPage from '../../components/article-routes/guide-security.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideSecurityPage, {
  head: ({ locale }) => articlePageHead('guide', 'security', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'security', locale) };
  },
});
