// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/streaming.md - do not edit.
import { definePage } from '@openelement/router';
import GuideStreamingPage from '../../components/article-routes/guide-streaming.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideStreamingPage, {
  head: ({ locale }) => articlePageHead('guide', 'streaming', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'streaming', locale) };
  },
});
