// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/styling.md - do not edit.
import { definePage } from '@openelement/router';
import GuideStylingPage from '../../components/article-routes/guide-styling.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideStylingPage, {
  head: ({ locale }) => articlePageHead('guide', 'styling', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'styling', locale) };
  },
});
