// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/guide/testing.md - do not edit.
import { definePage } from '@openelement/router';
import GuideTestingPage from '../../components/article-routes/guide-testing.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(GuideTestingPage, {
  head: ({ locale }) => articlePageHead('guide', 'testing', locale),
  props({ locale }) {
    return { model: projectArticlePage('guide', 'testing', locale) };
  },
});
