// Auto-generated by @openelement/adapter-vite nav-writer — do not edit
export const headerNav = [
  {
    "href": "/docs",
    "label": "Docs"
  },
  {
    "href": "/apilist",
    "label": "API"
  },
  {
    "href": "/roadmap",
    "label": "Roadmap"
  },
  {
    "href": "/blog",
    "label": "Blog"
  },
  {
    "href": "https://github.com/open-element/openelement",
    "label": "GitHub"
  }
];
export const navSections = [
  {
    "section": "Reference",
    "items": [
      {
        "path": "/apilist",
        "label": "API Reference",
        "order": 5
      },
      {
        "path": "/architecture/design-system",
        "label": "Design System",
        "order": 15
      },
      {
        "path": "/architecture/standards-registry",
        "label": "WC Standards Contract",
        "order": 80
      },
      {
        "path": "/architecture/package-compatibility",
        "label": "Package Compatibility",
        "order": 90
      },
      {
        "path": "/architecture/benchmark",
        "label": "Performance",
        "order": 100
      }
    ]
  },
  {
    "section": "Principles",
    "items": [
      {
        "path": "/architecture/architecture",
        "label": "Architecture",
        "order": 10
      },
      {
        "path": "/architecture/comparison",
        "label": "Comparison",
        "order": 20
      },
      {
        "path": "/architecture/dsd",
        "label": "DSD Rendering",
        "order": 30
      },
      {
        "path": "/architecture/islands",
        "label": "Islands",
        "order": 40
      },
      {
        "path": "/architecture/islands-deep",
        "label": "Island Deep Dive",
        "order": 50
      }
    ]
  },
  {
    "section": "History",
    "items": [
      {
        "path": "/blog",
        "label": "Blog",
        "order": 10
      }
    ]
  },
  {
    "section": "",
    "items": [
      {
        "path": "/roadmap",
        "label": "Roadmap",
        "order": 10
      },
      {
        "path": "/changelog",
        "label": "Changelog",
        "order": 20
      },
      {
        "path": "/contributing",
        "label": "Contributing",
        "order": 30
      }
    ]
  },
  {
    "section": "Quick Start",
    "items": [
      {
        "path": "/docs",
        "label": "Docs",
        "order": 0
      }
    ]
  },
  {
    "section": "Core",
    "items": [
      {
        "path": "/guide/api",
        "label": "API Routes",
        "order": 60
      }
    ]
  },
  {
    "section": "Guide",
    "items": [
      {
        "path": "/guide/getting-started",
        "label": "Getting Started",
        "order": 1
      },
      {
        "path": "/guide/styling",
        "label": "Styling",
        "order": 5
      },
      {
        "path": "/guide/core-concepts",
        "label": "Core Concepts",
        "order": 10
      },
      {
        "path": "/guide/architecture",
        "label": "Architecture",
        "order": 20
      },
      {
        "path": "/guide/comparison",
        "label": "Comparison",
        "order": 25
      },
      {
        "path": "/guide/routing-and-data",
        "label": "Routing and Data",
        "order": 40
      },
      {
        "path": "/guide/mdx",
        "label": "MDX",
        "order": 50
      },
      {
        "path": "/guide/configuration",
        "label": "Configuration",
        "order": 70
      },
      {
        "path": "/guide/migration",
        "label": "Migration",
        "order": 75
      },
      {
        "path": "/guide/error-handling",
        "label": "Error Handling",
        "order": 80
      },
      {
        "path": "/guide/islands-and-ssr",
        "label": "Islands and SSR",
        "order": 90
      },
      {
        "path": "/guide/security",
        "label": "Security",
        "order": 95
      },
      {
        "path": "/guide/deployment",
        "label": "Deployment",
        "order": 100
      },
      {
        "path": "/guide/testing",
        "label": "Testing",
        "order": 110
      }
    ]
  }
];
