// Auto-generated by @openelement/adapter-vite/i18n — do not edit
export const locales = ["en","zh"];
export const defaultLocale = "en";

export function getDefaultLocale(): string { return defaultLocale; }
