// GENERATED FILE — do not edit by hand.
// Regenerate via the repository's "generate:all" tooling task.
// Source of truth: the "exports" field of each workspace package manifest.
export const OPENELEMENT_EXPORT_FILES: Record<string, Record<string, string>> = {
  compiler: {
    '.': 'src/compiler.ts',
    vite: 'src/vite.ts',
  },
  create: {
    '.': 'src/cli.ts',
    'install-command': 'src/install-command.ts',
  },
  element: {
    '.': 'src/index.ts',
    authoring: 'src/authoring.ts',
    base: 'src/base.ts',
    'build-utils': 'src/build-utils.ts',
    'client-only': 'src/client-only.ts',
    'css-modules': 'src/css-modules.d.ts',
    html: 'src/html.ts',
    'jsx-dev-runtime': 'src/jsx-dev-runtime.ts',
    'jsx-runtime': 'src/jsx-runtime.ts',
    logger: 'src/logger.ts',
    'no-regions': 'src/no-regions.ts',
  },
  protocol: {
    '.': 'src/index.ts',
    'app-model': 'src/app-model.ts',
    'client-assets': 'src/client-assets.ts',
    data: 'src/data.ts',
    errors: 'src/errors.ts',
    'forbidden-sinks': 'src/forbidden-sinks.ts',
    framework: 'src/framework.ts',
    island: 'src/island.ts',
    'island-admission': 'src/island-admission.ts',
    manifest: 'src/manifest.ts',
    'module-descriptors': 'src/module-descriptors.ts',
    'module-vocabulary': 'src/module-vocabulary.ts',
    'part-program': 'src/part-program.ts',
    policy: 'src/policy.ts',
    'registry-markers': 'src/registry-markers.ts',
    render: 'src/render.ts',
    runtime: 'src/runtime.ts',
    signal: 'src/signal.ts',
    ssg: 'src/ssg.ts',
    'stream-frame-policy': 'src/stream-frame-policy.ts',
    'style-sheet': 'src/style-sheet.ts',
    'void-tags': 'src/void-tags.ts',
  },
  router: {
    '.': 'src/index.ts',
    'cli/build': 'src/cli/build.ts',
    'cli/start': 'src/cli/start.ts',
    document: 'src/document.ts',
    hono: 'src/hono-adapter.ts',
    http: 'src/http.ts',
    lit: 'src/lit.ts',
    'lit-ssr': 'src/lit-ssr.ts',
    'nitro-mount': 'src/nitro-mount.ts',
    router: 'src/router.ts',
    'router/client': 'src/router-client.ts',
    'server-runtime': 'src/vite/internal/server-runtime/mod.ts',
    vite: 'src/vite/index.ts',
  },
  ui: {
    '.': 'src/index.ts',
    'instance-state': 'src/instance-state.ts',
    manifest: 'src/manifest.ts',
    'open-button': 'src/open-button.tsx',
    'open-code-block': 'src/open-code-block.tsx',
    'open-dialog': 'src/open-dialog.tsx',
    'open-dropdown': 'src/open-dropdown.tsx',
    'open-input': 'src/open-input.tsx',
    'open-theme-toggle': 'src/open-theme-toggle.tsx',
    'theme.css': 'src/theme.css',
  },
};
