/**
 * Route manifest generator for SPA mode client routing.
 *
 * Scans the project's routes directory and generates a TypeScript manifest
 * that maps URL paths to lazy import() calls. The generated file is bundled
 * by Vite for client-side route lazy loading.
 *
 * ## Usage (SPA mode)
 *
 * ```ts
 * // Generated to `${outDir}/route-manifest.ts`; import from that generated
 * // module or alias it from your client entry.
 * import { routeRecords } from './route-manifest.ts';
 * import { defineApp } from '@openelement/router';
 *
 * const app = defineApp({
 *   mode: 'spa',
 *   routes: await Promise.all(
 *     routeRecords.map(async ({ load, ...record }) => {
 *       const mod = await load();
 *       return { ...record, tagName: mod.tagName };
 *     }),
 *   ),
 * });
 * app.mount('#root');
 * ```
 *
 * ## File System Convention
 *
 * - `routes/index.tsx`          → `/`
 * - `routes/products.tsx`       → `/products`
 * - `routes/products/[id].tsx`  → `/products/:id`
 * - `routes/products/index.tsx` → `/products`
 * - `routes/products/[...slug].tsx` → `/products/:slug{.+}` (catch-all; Hono
 *   named-regex parameter matching across `/`, see scanRoutes #556)
 *
 * @module route-manifest
 */

import { scanRoutes } from './internal/ssg/index.ts';
import { dirname, join, relative } from '@std/path';
import { normalizeSeparators } from '@openelement/element/build-utils';
import { DEFAULT_ROUTES_DIR } from './internal/paths.ts';
import { quoteGeneratedJavaScriptValue } from './internal/ssg/codegen-literals.ts';

/**
 * Parameters for route manifest generation.
 */
interface GenerateRouteManifestOptions {
  /** Project routes directory (default: 'app/routes') */
  routesDir?: string;
  /** Output directory for the generated manifest file */
  outDir: string;
}

interface RouteManifestGeneration {
  content: string;
  count: number;
}

async function generateRouteManifest(
  routesDir: string,
  manifestPath: string,
): Promise<RouteManifestGeneration> {
  const routes = await scanRoutes(routesDir);
  const pageRoutes = routes.filter((r) => r.type === 'page' && !r.special);

  const manifestDir = dirname(manifestPath);

  const entries = pageRoutes.map((r) => {
    const absFilePath = join(routesDir, r.filePath);
    const importPath = relativeToOutput(absFilePath, manifestDir);
    // Route paths and file names are interpolated into generated code, so
    // they go through the shared JS-literal quoting (a `'` in a file name
    // must not break the manifest's syntax, #1039).
    return `  { id: ${quoteGeneratedJavaScriptValue(r.filePath)}, path: ${
      quoteGeneratedJavaScriptValue(r.path)
    }, methods: ['GET', 'POST'], load: () => import(${
      quoteGeneratedJavaScriptValue(importPath)
    }) }`;
  });

  if (entries.length === 0) {
    return {
      count: 0,
      content: `// Auto-generated by @openelement/router — do not edit.
// No page routes found in "${routesDir}".
export const routeRecords = [] as const;
`,
    };
  }

  return {
    count: entries.length,
    content: `// Auto-generated by @openelement/router — do not edit.
export const routeRecords = [
${entries.join(',\n')}
] as const;
`,
  };
}

/**
 * Compute a relative import path from the manifest output directory to a
 * source file, ensuring posix separators and a leading `./` prefix.
 *
 * @param absSourcePath - Absolute path to the source file (route module)
 * @param fromDir - Absolute directory from which the import originates
 * @returns Relative import path string
 */
function relativeToOutput(absSourcePath: string, fromDir: string): string {
  const rel = relative(fromDir, absSourcePath);
  const posixRel = normalizeSeparators(rel).replace(/^\.+\//, '');
  const normalized = posixRel.replaceAll('\\', '/');
  if (normalized.startsWith('.')) return normalized;
  return './' + normalized;
}

/**
 * Ensure the output directory exists, then write the route manifest file.
 *
 * @param options - Generation options
 * @returns The number of page routes written
 */
export async function writeRouteManifest(
  options: GenerateRouteManifestOptions,
): Promise<number> {
  const { routesDir = DEFAULT_ROUTES_DIR, outDir } = options;
  const manifestPath = join(outDir, 'route-manifest.ts');

  await Deno.mkdir(outDir, { recursive: true });
  const { content, count } = await generateRouteManifest(routesDir, manifestPath);
  await Deno.writeTextFile(manifestPath, content);
  return count;
}
