/**
 * packages/compiler/__tests__/compiled-artifact-style-requests.test.ts — the
 * artifact adoption read (#1558 / KR-10, alpha.13 I1).
 *
 * Packages ship the compiler's OWN emitted modules (the pack pipeline stages
 * `compilePackageElementModules` output). A consumer build that resolves one
 * has no authored grammar left to compile, but its `.css` imports are real
 * edges of the style asset protocol — and the router's style-asset intercept
 * answers only edges the compiled-element transform registered. This suite
 * pins the read's consumer form:
 *
 *   - the compiler's own emission round-trips: compiled module in, the same
 *     edge specifiers out (the packed form admits identically to the
 *     workspace-source form);
 *   - adoption is all-or-nothing per module: anything outside the ONE style
 *     authoring grammar leaves the module entirely to the graph's normal
 *     channels, so a partial adoption can never turn a working module into a
 *     fail-closed intercept;
 *   - the transform is the registry's one writer for adopted artifacts too
 *     (the edges land in the registry under the resolver-landed module id).
 */

import { beforeEach, describe, expect, test } from 'vitest';
import {
  CompiledElementError,
  compileElementProgram,
} from '../src/internal/compiler/semantic-core/compile.ts';
import { compiledArtifactStyleRequests } from '../src/internal/compiler/compiled-artifact-style-requests.ts';
import { compiledElementPlugin } from '../src/internal/compiler/plugin.ts';
import {
  clearStyleRequests,
  getStyleRequest,
  hasStyleImporter,
  styleRequestModuleId,
} from '../src/internal/compiler/style-requests.ts';

const IMPORTER = '/proj/node_modules/@acme/ui/src/open-widget.js';

/** An authored compiled module with the given relative sheet imports. */
function authoredSource(specifiers: string[]): string {
  return [
    "import { element, OpenElement, property, type StyleSheetLike } from '@openelement/element';",
    ...specifiers.map((specifier, index) => `import sheet${index} from '${specifier}';`),
    "@element('oe-widget', { root: 'shadow-open' })",
    'export class OeWidget extends OpenElement {',
    `  static override styles: StyleSheetLike[] = [${specifiers
      .map((_specifier, index) => `sheet${index}`)
      .join(', ')}];`,
    "  @property({ reflect: false }) label = '';",
    '  render() {',
    '    return <main>{this.label}</main>;',
    '  }',
    '}',
  ].join('\n');
}

/** The compiler's own emission for an authored module — the artifact shape. */
function emittedArtifact(specifiers: string[]): string {
  return compileElementProgram(authoredSource(specifiers), '/proj/src/open-widget.tsx').code;
}

const transformOf = (): ((code: string, id: string) => unknown) => {
  const plugin = compiledElementPlugin();
  const transform = plugin.transform as (this: unknown, code: string, id: string) => unknown;
  return (code: string, id: string): unknown => transform.call({}, code, id);
};

beforeEach(() => {
  clearStyleRequests();
});

describe('the artifact read', () => {
  test("the compiler's own emission round-trips its edges in authored order", () => {
    const artifact = emittedArtifact(['./control-recipe.css', './open-widget.css']);
    expect(compiledArtifactStyleRequests(artifact, IMPORTER)).toEqual([
      './control-recipe.css',
      './open-widget.css',
    ]);
  });

  test('a single-sheet artifact recovers one edge', () => {
    expect(compiledArtifactStyleRequests(emittedArtifact(['./only.css']), IMPORTER)).toEqual([
      './only.css',
    ]);
  });

  test('an emitted module with no sheets recovers nothing', () => {
    expect(compiledArtifactStyleRequests(emittedArtifact([]), IMPORTER)).toBeUndefined();
  });
});

describe('adoption is all-or-nothing', () => {
  test('a non-artifact module is never parsed as one', () => {
    expect(
      compiledArtifactStyleRequests(
        ["import sheet from './x.css';", 'export const a = sheet;'].join('\n'),
        IMPORTER,
      ),
    ).toBeUndefined();
  });

  test('a mangled artifact (no followable styles shape) is left to the graph', () => {
    const artifact = emittedArtifact(['./x.css']);
    // Truncated before the class: the marker survives but no `static styles`
    // member exists, so nothing is adoptable.
    expect(
      compiledArtifactStyleRequests(artifact.slice(0, artifact.indexOf('class')), IMPORTER),
    ).toBeUndefined();
  });

  test('a sheet import that no static styles arrays leaves the module untouched', () => {
    const artifact = [
      '// <auto-generated by open:compiled-element; do not edit>',
      "import sheet0 from './unadopted.css';",
      'const __partProgram = { version: 1 };',
      'var OpenWidget = class {',
      '  static __partProgram = __partProgram;',
      '  static styles = [];',
      '};',
    ].join('\n');
    // The ONE style authoring grammar array every sheet import; an unarrayed
    // edge means the module is not that shape, and a partial adoption would
    // leave the intercept to fail closed on the remaining edge.
    expect(compiledArtifactStyleRequests(artifact, IMPORTER)).toBeUndefined();
  });

  test('a spread in the styles array leaves the module untouched', () => {
    const artifact = [
      "import sheet0 from './x.css';",
      "import sheets from './all.js';",
      'const __partProgram = { version: 1 };',
      'var OpenWidget = class {',
      '  static __partProgram = __partProgram;',
      '  static styles = [sheet0, ...sheets];',
      '};',
    ].join('\n');
    expect(compiledArtifactStyleRequests(artifact, IMPORTER)).toBeUndefined();
  });

  test('a styles member the read cannot follow leaves the module untouched', () => {
    const artifact = [
      "import sheet0 from './x.css';",
      'const __partProgram = { version: 1 };',
      'var OpenWidget = class {',
      '  static __partProgram = __partProgram;',
      '  static styles = buildStyles(sheet0);',
      '};',
    ].join('\n');
    expect(compiledArtifactStyleRequests(artifact, IMPORTER)).toBeUndefined();
  });

  test('the pre-#1558 legacy shape (a sheet built in a plain module) is untouched', () => {
    // The retired authoring form: `static styles` references a StyleSheet the
    // module built itself, with no `.css` import to recover. The read must not
    // claim anything, so published pre-#1558 packages keep the old path.
    const artifact = [
      "import { StyleSheet } from '@openelement/element';",
      "import { controlRecipe } from './component-recipes.js';",
      'const __partProgram = { version: 1 };',
      'var OpenButton = class {',
      '  static __partProgram = __partProgram;',
      '  static styles = [controlRecipe];',
      '};',
    ].join('\n');
    expect(compiledArtifactStyleRequests(artifact, IMPORTER)).toBeUndefined();
  });
});

describe('the transform registers adopted artifact edges', () => {
  test('an artifact edge lands in the registry under the resolver-landed id', () => {
    const transform = transformOf();
    transform(emittedArtifact(['./control-recipe.css']), IMPORTER);
    const request = getStyleRequest(styleRequestModuleId(IMPORTER, './control-recipe.css'));
    expect(request).toBeDefined();
    expect(request?.importer).toEqual(IMPORTER);
    expect(request?.file.endsWith('/src/control-recipe.css')).toEqual(true);
    expect(hasStyleImporter(IMPORTER)).toEqual(true);
  });

  test('adopting an artifact does not compile it', () => {
    const transform = transformOf();
    // The artifact ships as its own emitted module; the hook's job is the edge
    // registration, so the transform returns null (no module rewrite).
    expect(transform(emittedArtifact(['./x.css']), IMPORTER)).toEqual(null);
  });

  test('an authored module still compiles and registers through the same hook', () => {
    const transform = transformOf();
    const result = transform(
      authoredSource(['./authored.css']),
      '/proj/app/islands/open-widget.tsx',
    );
    expect(String(result)).toContain('auto-generated by open:compiled-element');
    expect(
      getStyleRequest(styleRequestModuleId('/proj/app/islands/open-widget.tsx', './authored.css')),
    ).toBeDefined();
  });
});

describe('the compiler still fails an authored module closed', () => {
  test('an inline sheet string in authored source is still OEC9029', () => {
    expect(() =>
      compileElementProgram(
        [
          "import { element, OpenElement, type StyleSheetLike } from '@openelement/element';",
          "@element('oe-bad')",
          'export class OeBad extends OpenElement {',
          '  static override styles: StyleSheetLike[] = [`:host { display: block; }`];',
          '  render() {',
          '    return <main></main>;',
          '  }',
          '}',
        ].join('\n'),
        '/proj/src/oe-bad.tsx',
      ),
    ).toThrow(CompiledElementError);
  });
});
