// openelement.config.ts — the framework options of the official Site.
//
// The Vite configuration owns only Vite concerns (base, resolve.alias, the
// oxc JSX transform); everything the framework reads lives here. The
// plugin call in vite.config.ts is therefore plain `openElement()`.
//
// Two channels feed the document <head>:
//   - `head.scripts` below: external scripts, structured (src/defer), so the
//     framework serializes the tags and the Site never hand-writes markup;
//   - `app/head.tsx`: structural content a URL list cannot express (meta tags,
//     font preloads, icons, feed links, inline critical CSS).
import { defineConfig } from '@openelement/router';
import { SITE_BUDGET } from './site-budget.ts';
import { SITE_DEFAULT_LOCALE, SITE_LOCALES } from './site-config.ts';
import { headerNav, navSections } from './app/data/_generated-nav-data.ts';

export default defineConfig({
  // The framework's documented defaults, stated explicitly: the Site pins its
  // source roots so a future default change cannot silently move them. The
  // tokens/app-shell/head conventions resolve under the shared base of the
  // three roots, which is `app` — where app/head.tsx lives.
  dirs: {
    routes: 'app/routes',
    islands: 'app/islands',
    components: 'app/components',
  },
  // The document title is deliberately NOT set here: the framework's default is
  // already `openElement`, and every Site page declares its own title through
  // the page descriptor head (www/app/site-ui/head.ts), which is the only
  // meaning <title> should carry. Setting it here would additionally emit the
  // site-level og:title/og:site_name pair, which the page-level head owns.
  head: {
    // All scripts are same-origin. theme-init is inlined instead of requested;
    // goatcounter was removed (unreachable from CN networks, cost a console
    // error + best-practices points on every page). Code highlighting compiles
    // into the page HTML at build time (www/lib/markdown.ts) — no highlighting
    // script ships or runs in the browser (issue #1552 retired the vendored
    // Prism runtime).
    scripts: [{ src: '/theme-init.js' }],
  },
  // The shell's tag name (`open-layout`) is derived from the import's basename.
  appShell: {
    import: './app/islands/open-layout.tsx',
    props: {
      footerText: 'Built with OpenElement — Web Components-native application framework',
      // Router 1.0 keeps the app-shell nav contract in the consumer: the Site
      // projects its route-meta nav tree into the shell (Nav items are
      // static; the router injects currentPath/locale per route).
      navItems: navSections,
      headerNav,
    },
  },
  // Listing the UI package admits its island modules AND derives the SSR
  // externalization list: a package whose islands the build renders must be
  // bundled, not imported at run time. There is no separate `ssr` key.
  packageIslands: ['@openelement/ui'],
  viewTransition: true,
  speculation: true,
  // One shared official-Site SLO (www/site-budget.ts): the build manifest
  // reports against exactly these values.
  build: {
    manifestBudget: SITE_BUDGET,
  },
  // The Site's generated data modules (app/data/_generated-*) are untracked
  // build inputs, regenerated by `pnpm --dir www run generate:content`
  // (article collections and blog) and `pnpm --dir www run
  // generate:api-reference` from www/lib/content.ts + lib/blog.ts.
  i18n: {
    locales: [...SITE_LOCALES],
    defaultLocale: SITE_DEFAULT_LOCALE,
  },
});
