// Auto-generated by tools/generate-site-content-data.ts from collection:blog - do not edit
export interface GeneratedBlogPost {
  slug: string;
  frontmatter: {
    title: string;
    date: string;
    draft?: boolean;
    tags?: string[];
    excerpt?: string;
    type?: string;
    lang?: string;
  };
  content: string;
  html: string;
}

export const posts: GeneratedBlogPost[] = [
  {
    "slug": "1-0-0-alpha-1-baseline",
    "frontmatter": {
      "title": "1.0.0-alpha.1: a new baseline",
      "date": "2026-09-13",
      "draft": false,
      "tags": [
        "release",
        "alpha"
      ],
      "excerpt": "Element and Router converge on a fresh 1.0 Alpha baseline: public core, supported creation entry, experimental UI, and independently qualified packages.",
      "lang": "en"
    },
    "content": "\n## What 1.0.0-alpha.1 is\n\n`1.0.0-alpha.1` is a new baseline for Element and Router, not an upgrade of the\n0.x lines. There is no supported migration path from 0.x: new projects start\nfrom `@openelement/create`.\n\n## Product surface\n\n- **Element** and **Router** are the public framework core.\n- **Create** is the supported creation entry.\n- **UI** ships in this repository as experimental: usable, but outside the 1.0\n  stable API promise.\n- The **site** you are reading is the official product surface; the bundled\n  **SaaS** app is the first-party core consumer that proves the standard\n  consumption shape.\n\n## How it is qualified\n\nEvery release candidate must survive independent packed consumers: the published\ntarballs — never the monorepo sources — build a minimal Element app, a Router\nSSR/SSG app, and browser claim/hydration checks on current Chromium, Firefox,\nand WebKit. Deployment targets are Deno 2.9 and Node.js 24 via the Nitro\nserver adapter; local preview serves through `Deno.serve` from TypeScript\nsource. There is no first-party Node HTTP bridge.\n\n## What to expect next\n\nAlpha APIs may still change. Breaking changes land with the baseline, and each\nstep must re-pass the packed-consumer gate before it counts as progress.\n",
    "html": "<h2>What 1.0.0-alpha.1 is</h2>\n<p><code>1.0.0-alpha.1</code> is a new baseline for Element and Router, not an upgrade of the\n0.x lines. There is no supported migration path from 0.x: new projects start\nfrom <code>@openelement/create</code>.</p>\n<h2>Product surface</h2>\n<ul>\n<li><strong>Element</strong> and <strong>Router</strong> are the public framework core.</li>\n<li><strong>Create</strong> is the supported creation entry.</li>\n<li><strong>UI</strong> ships in this repository as experimental: usable, but outside the 1.0\nstable API promise.</li>\n<li>The <strong>site</strong> you are reading is the official product surface; the bundled\n<strong>SaaS</strong> app is the first-party core consumer that proves the standard\nconsumption shape.</li>\n</ul>\n<h2>How it is qualified</h2>\n<p>Every release candidate must survive independent packed consumers: the published\ntarballs — never the monorepo sources — build a minimal Element app, a Router\nSSR/SSG app, and browser claim/hydration checks on current Chromium, Firefox,\nand WebKit. Deployment targets are Deno 2.9 and Node.js 24 via the Nitro\nserver adapter; local preview serves through <code>Deno.serve</code> from TypeScript\nsource. There is no first-party Node HTTP bridge.</p>\n<h2>What to expect next</h2>\n<p>Alpha APIs may still change. Breaking changes land with the baseline, and each\nstep must re-pass the packed-consumer gate before it counts as progress.</p>\n"
  }
];

export function getPostBySlug(slug: string): GeneratedBlogPost | undefined {
  return posts.find((post) => post.slug === slug);
}
