name: Setup Deno Workspace
description: Install Deno, restore workspace dependencies, and materialize node_modules.

runs:
  using: composite
  steps:
    # v2.0.5
    - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed
      with:
        deno-version-file: .dvmrc
    - name: Cache dependencies
      # v4.3.0
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
      with:
        path: node_modules
        key: ${{ runner.os }}-deno-${{ hashFiles('.dvmrc') }}-${{ hashFiles('deno.lock') }}
    - name: Install dependencies
      shell: bash
      run: |
        deno install --frozen --node-modules-dir
        git diff --exit-code -- deno.lock
