/**
 * @openelement/element — #1160 TSX-to-Part Program vertical compiler v1.
 *
 * Behavior-first coverage for the open:compiled-element v1 transform:
 *   - the one-component fixture is transformed through the actual
 *     compiledElementPlugin() Vite transform hook
 *   - the emitted module embeds one deterministic, serializable Part Program
 *     (static structure + typed Part/Region instructions) that deep-equals the
 *     frozen expected-program.json fixture consumed by the element runtime
 *     test, minus the compile-time sourceMap provenance the wire payload omits
 *   - re-running the transform yields byte-identical output
 *   - unsupported syntax fails closed at transform time with a source-located
 *     diagnostic; no runtime fallback is emitted
 *   - measurement evidence (generated bytes, instruction count) is recorded
 *
 * The compiler modules are loaded via dynamic import so a RED run proves the
 * harness and fixtures work while the new vertical behavior is absent.
 */

import { readFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { describe, expect, test } from 'vitest';
import { assertThrowsIncludes } from '../../../tests/lib/vitest-asserts.ts';
import type { Plugin } from 'vite';
import {
  COMPILED_MODULE_ABI_VERSION,
  PART_PROGRAM_VERSION,
} from '@openelement/protocol/part-program';
import type { StaticSidecarDescriptor } from '../../../packages/compiler/src/internal/compiler/semantic-core/module-analysis.ts';

const FIXTURE_DIR = new URL('../__fixtures__/compiled-element-v1/', import.meta.url);

// Module-level loads (top-level await): vitest describe bodies are
// synchronous, so the loads hoist here — one load, cached modules, shared by
// every suite below.
const { compiledElementPlugin } = await loadPluginModule();
const { compileElementProgram, CompiledElementError } =
  await import('../../../packages/compiler/src/internal/compiler/semantic-core/compile.ts');

/**
 * The island sidecar descriptor a host framework injects (#1468): the
 * compiler ships no router knowledge, so the alpha.8 island policy statement
 * is exercised through this explicit descriptor.
 */
const ISLAND_SIDECAR: StaticSidecarDescriptor = {
  moduleSpecifier: '@openelement/router',
  exportName: 'defineIslandConfig',
  kind: 'static-sidecar',
};

async function readFixture(name: string): Promise<string> {
  return await readFile(new URL(name, FIXTURE_DIR), 'utf8');
}

function readFixtureSync(name: string): string {
  return readFileSync(new URL(name, FIXTURE_DIR), 'utf8');
}

type PluginModule = typeof import('../../../packages/compiler/src/internal/compiler/plugin.ts');

async function loadPluginModule(): Promise<PluginModule> {
  return await import('../../../packages/compiler/src/internal/compiler/plugin.ts');
}

interface TransformContext {
  // Vite's `this.error()` takes a string or a Rollup error object; since
  // #1413 the adapter passes the structured form, so the harness mirrors that
  // signature while the message-text assertions stay unchanged.
  error(error: string | { message: string }): never;
}

function failingContext(): TransformContext & { messages: string[] } {
  const messages: string[] = [];
  return {
    messages,
    error(error: string | { message: string }): never {
      const message = typeof error === 'string' ? error : error.message;
      messages.push(message);
      throw new Error(message);
    },
  };
}

type TransformHook = (this: TransformContext, code: string, id: string) => string | null;

function transformOf(plugin: Plugin): TransformHook {
  expect(
    typeof plugin.transform === 'function',
    'plugin must expose a transform hook',
  ).toBeTruthy();
  return plugin.transform as unknown as TransformHook;
}

function decodeBase64(value: string): string {
  const binary = atob(value);
  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

test('compiled-element v1 - harness sanity (fixtures load)', async () => {
  const counter = await readFixture('counter.tsx');
  const expected = await readFixture('expected-program.json');
  expect(counter.includes("@element('oe-program-counter')")).toBeTruthy();
  expect(JSON.parse(expected).tag).toEqual('oe-program-counter');
});

test('compiled-element v1 - the standalone compiler hook has its canonical name', () => {
  // The default Router pipeline (open:core) embeds the compiler instead of
  // registering this standalone plugin; that composition is pinned by the
  // adapter-side openPlugin ordering tests. loadPluginModule hoists to the
  // module-level top-level await above.
  expect(compiledElementPlugin().name).toEqual('open:compiled-element');
});

describe('compiled-element v1 - fixture transforms through the Vite hook', () => {
  const plugin = compiledElementPlugin();
  const transform = transformOf(plugin);
  const source = readFixtureSync('counter.tsx');
  const id = '/project/app/islands/counter.tsx';

  // One shared emission across the steps (module describe scope): a single test
  // produces it, later tests pin its properties in the same order.
  let emitted: string | null = null;
  test('transform returns generated code', () => {
    emitted = transform.call(failingContext(), source, id);
    expect(typeof emitted === 'string').toBeTruthy();
    expect(emitted).toContain('__partProgram');
  });

  const programLiteral = (code: string): string => {
    const marker = 'const __partProgram = ';
    const start = code.indexOf(marker);
    expect(start >= 0, 'generated code must embed the Part Program literal').toBeTruthy();
    const end = code.indexOf(';', start);
    return code.slice(start + marker.length, end);
  };

  test('emitted program deep-equals the frozen expected program', () => {
    const expected = JSON.parse(readFixtureSync('expected-program.json'));
    // The wire payload omits the compile-time sourceMap provenance; the
    // frozen fixture keeps it for the in-memory artifact contract.
    const { sourceMap: _provenance, ...wireExpected } = expected;
    expect(JSON.parse(programLiteral(emitted!))).toEqual(wireExpected);
  });

  test('emitted metadata preserves @property reflection decisions (R2)', () => {
    const marker = 'const __compiledProperties = ';
    const start = emitted!.indexOf(marker);
    expect(start >= 0, 'generated code must embed compiled-property metadata').toBeTruthy();
    const end = emitted!.indexOf(';', start);
    const metadata = JSON.parse(emitted!.slice(start + marker.length, end));
    // Exact fixture decisions: count reflected; label and items not reflected.
    expect(metadata).toEqual([
      {
        name: 'count',
        attribute: 'count',
        type: 'number',
        converter: 'number',
        reflect: true,
        default: 0,
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string',
        converter: 'string',
        reflect: false,
        default: 'ready',
      },
      {
        name: 'items',
        attribute: 'items',
        type: 'array',
        converter: 'array',
        reflect: false,
        default: [
          { id: 'a', text: 'alpha' },
          { id: 'b', text: 'beta' },
        ],
      },
    ]);
    // Compile-time data only: no runtime reflection behavior is emitted.
    expect(emitted!.includes('attributeChangedCallback')).toEqual(false);
    expect(emitted!).toContain(
      'static __compiledProperties: typeof __compiledProperties = __compiledProperties;',
    );
    expect(emitted!).toContain('static props: typeof __compiledProps = __compiledProps;');
    expect(emitted!).toContain(
      'static observedAttributes: typeof __observedAttributes = __observedAttributes;',
    );
  });

  test('program carries static structure plus typed Part/Region instructions', () => {
    const program = JSON.parse(programLiteral(emitted!));
    expect(program.version).toEqual(1);
    const kinds = program.parts.map((p: { k: string }) => p.k).sort();
    expect(kinds).toEqual(['each', 'event', 'prop', 'text', 'when']);
    // instruction count = typed parts; static structure lives in the template
    expect(program.parts.length).toEqual(5);
  });

  test('emitted code contains no VNode/binding/hydration fallback vocabulary', () => {
    for (const token of [
      'VNode',
      'BindingDescriptor',
      'hydrationScope',
      'HydrationScope',
      'createElement(',
    ]) {
      expect(emitted!.includes(token), `generated code must not contain ${token}`).toEqual(false);
    }
    expect(emitted!).toContain('the runtime JSX render path is not available');
  });

  test('generated banner stamps protocol versions, not release names', () => {
    const banner = emitted!.split('\n')[0];
    expect(banner).toContain(
      `// <auto-generated by open:compiled-element; part-program format ${PART_PROGRAM_VERSION} / module ABI ${COMPILED_MODULE_ABI_VERSION} - do not edit>`,
    );
    // The banner carries protocol versions only — never a package release name.
    expect(/v?\d+\.\d+\.\d+/.test(banner), `banner leaked a release version: ${banner}`).toEqual(
      false,
    );
  });

  test('re-running the transform yields byte-identical output', () => {
    const again = transform.call(failingContext(), source, id);
    expect(again).toEqual(emitted);
  });

  test('inline source map carries x_openElement v1 program source records', () => {
    const marker = '//# sourceMappingURL=data:application/json;base64,';
    const line = emitted!.split('\n').find((candidate) => candidate.startsWith(marker));
    expect(line, 'generated code must embed an inline base64 source map').toBeTruthy();
    const map = JSON.parse(decodeBase64(line.slice(marker.length)));
    expect(map.version).toEqual(3);
    expect(map.sources).toEqual([id]);
    // sourcesContent carries the original TSX source verbatim.
    expect(map.sourcesContent).toEqual([source]);
    // The frozen fixture program is the source of truth for the v1 records:
    // x_openElement must deep-equal its sourceMap (file + every record).
    const expected = JSON.parse(readFixtureSync('expected-program.json'));
    expect(map.x_openElement.version).toEqual(1);
    expect(map.x_openElement).toEqual(expected.sourceMap);
    expect(map.x_openElement.records.length).toEqual(expected.sourceMap.records.length);
  });

  test('measurement evidence is recorded', () => {
    const programJson = programLiteral(emitted!);
    const generatedBytes = new TextEncoder().encode(emitted!).length;
    const programBytes = new TextEncoder().encode(programJson).length;
    const instructionCount = JSON.parse(programJson).parts.length;
    // Frozen program evidence (alpha.0 fixture): regenerated only by changing the
    // fixture grammar. These are evidence, not a performance claim.
    expect(instructionCount).toEqual(5);
    console.log(
      JSON.stringify({
        proof: 'adapter-compiler',
        generatedBytes,
        programBytes,
        instructionCount,
      }),
    );
  });

  test('files outside the program grammar marker pass through untouched', () => {
    const result = transform.call(
      failingContext(),
      'export class Plain { render() { return null; } }',
      '/project/app/components/plain.tsx',
    );
    expect(result).toEqual(null);
  });
});

describe('compiled-element v1 - unsupported syntax fails closed with located diagnostics', () => {
  const transform = transformOf(compiledElementPlugin());

  test('spread attributes are rejected with file/line location', () => {
    const source = readFixtureSync('unsupported-spread.tsx');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/unsupported-spread.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    expect(thrown, 'transform must throw for unsupported syntax').toBeTruthy();
    expect(ctx.messages.length).toEqual(1);
    const message = ctx.messages[0];
    expect(message).toContain('unsupported-spread.tsx:');
    expect(message).toContain('OEC9');
    expect(message.toLowerCase()).toContain('spread');
  });

  test('unknown decorators on an OpenElement class fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      'declare function mystery(): ClassDecorator;',
      "@element('oe-proof-mystery')",
      '@mystery()',
      'export class Mystery extends OpenElement {',
      '  render() { return <div>ok</div>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/mystery.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    expect(thrown, 'transform must throw for unknown decorators').toBeTruthy();
    expect(ctx.messages[0]).toContain('mystery.tsx:');
    expect(ctx.messages[0].toLowerCase()).toContain('decorator');
  });

  test('classes not extending OpenElement fail closed', () => {
    const source = [
      "import { element } from '@openelement/element';",
      "@element('oe-proof-alien')",
      'export class Alien extends HTMLElement {',
      '  render() { return null; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/alien.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    expect(thrown, 'transform must throw for non-OpenElement base classes').toBeTruthy();
    expect(ctx.messages[0]).toContain('OpenElement');
  });

  test('path-addressed fixed sinks after dynamic anchors fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-unsafe-path')",
      'export class UnsafePath extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() {',
      '    return <div>{this.count > 0 ? <p>positive</p> : <p>zero</p>}<input value={this.label} /></div>;',
      '  }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrowsIncludes(
      () => transform.call(ctx, source, '/project/app/islands/unsafe-path.tsx'),
      Error,
      'OEC9015',
    );
    expect(ctx.messages[0]).toContain('dynamic anchor');
  });

  test('duplicate static and dynamic attribute sinks fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-duplicate-attribute')",
      'export class DuplicateAttribute extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <input value="static" value={this.label} />; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrowsIncludes(
      () => transform.call(ctx, source, '/project/app/islands/duplicate-attribute.tsx'),
      Error,
      'duplicate attribute',
    );
    expect(ctx.messages[0]).toContain('OEC9011');
  });

  test('void elements with children fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-void-children')",
      'export class VoidChildren extends OpenElement {',
      '  render() { return <input>not supported</input>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrowsIncludes(
      () => transform.call(ctx, source, '/project/app/islands/void-children.tsx'),
      Error,
      'void element',
    );
    expect(ctx.messages[0]).toContain('OEC9013');
  });

  test('event-looking attribute sinks fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-unsafe-attribute')",
      'export class UnsafeAttribute extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <input onclick={this.label} />; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrowsIncludes(
      () => transform.call(ctx, source, '/project/app/islands/unsafe-attribute.tsx'),
      Error,
      'unsafe',
    );
    expect(ctx.messages[0]).toContain('OEC9011');
  });

  test('=== ternary conditions compile; non-literal comparisons still fail closed (#1372)', () => {
    // The old fixture (`this.count === 1 ? … : …`) failed only because `===`
    // was outside the seed operator set; with #1372 it is a valid program.
    const admitted = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-equals-ternary')",
      'export class EqualsTernary extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      '  render() { return <div>{this.count === 1 ? <p>one</p> : <p>other</p>}</div>; }',
      '}',
    ].join('\n');
    const okCtx = failingContext();
    transform.call(okCtx, admitted, '/project/app/islands/equals-ternary.tsx');
    expect(okCtx.messages.length, '=== ternary condition should compile (#1372)').toEqual(0);

    // The right-hand side must stay a literal: comparing two properties is
    // outside the grammar and fails closed.
    const rejected = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-non-literal-condition')",
      'export class NonLiteralCondition extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      '  @property({ reflect: false }) limit = 10;',
      '  render() { return <div>{this.count > this.limit && <p>over</p>}</div>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrowsIncludes(
      () => transform.call(ctx, rejected, '/project/app/islands/non-literal-condition.tsx'),
      Error,
      'OEC9013',
    );
    expect(ctx.messages[0]).toContain('OEC9013');
  });

  test('list Regions admit multi-field item slots and fail closed on non-item expressions', async () => {
    const { compileElementProgram } =
      await import('../../../packages/compiler/src/internal/compiler/semantic-core/compile.ts');
    // alpha.8: item templates carry one ival/iattr slot per item field — a row
    // may bind {item.text} twice and per-item attributes (id, href, ...).
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-multi-field')",
      'export class MultiField extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', text: 'alpha', link: '/a' }];",
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id} id={item.id}>{item.text}{item.text}<a href={item.link}>{item.text}</a></li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const program = compileElementProgram(source, '/project/app/islands/multi-field.tsx').program;
    const each = program.parts.find((part: { k: string }) => part.k === 'each') as
      | {
          field?: string;
          item: unknown[];
        }
      | undefined;
    expect(each, 'each Region must exist').toBeTruthy();
    expect(each.field, 'multi-field templates omit the Region field restatement').toEqual(
      undefined,
    );
    expect(JSON.stringify(each.item).includes('"iattrs"')).toBeTruthy();

    // Expressions that are not item field slots still fail closed.
    const bad = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-bad-item')",
      'export class BadItem extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', text: 'alpha' }];",
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id}>{item.text.toUpperCase()}</li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrowsIncludes(
      () => transform.call(ctx, bad, '/project/app/islands/bad-item.tsx'),
      Error,
      'item child must be',
    );
    expect(ctx.messages[0]).toContain('OEC9013');
  });

  test('list Region item events lower to ItemEventBinding entries (#1556 IR v2)', async () => {
    const { compileElementProgram } =
      await import('../../../packages/compiler/src/internal/compiler/semantic-core/compile.ts');
    // Method form on the item root: one binding, no selector — the runtime
    // attaches it to each item's root and dispatches with (event, item).
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-item-events')",
      'export class ItemEvents extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', label: 'alpha' }];",
      '  pick(event: MouseEvent, item: { id: string }) { void event; void item; }',
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id} onClick={this.pick}>{item.label}</li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const program = compileElementProgram(source, '/project/app/islands/item-events.tsx').program;
    const each = program.parts.find((part: { k: string }) => part.k === 'each') as
      | { itemEvents?: unknown[] }
      | undefined;
    expect(each, 'each Region must exist').toBeTruthy();
    expect(each.itemEvents).toEqual([
      { event: 'click', handler: 'pick', action: { kind: 'method', name: 'pick' } },
    ]);

    // Nested element target: the binding carries the compile-time structural
    // selector (`:nth-child` counts element siblings; ival text does not).
    const nested = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-item-events-nested')",
      'export class NestedItemEvents extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', label: 'alpha' }];",
      '  press(event: PointerEvent, item: { id: string }) { void event; void item; }',
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id}>{item.label}<button onPointerDown={this.press}>go</button></li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const nestedProgram = compileElementProgram(
      nested,
      '/project/app/islands/item-events-nested.tsx',
    ).program;
    const nestedEach = nestedProgram.parts.find((part: { k: string }) => part.k === 'each') as
      | { itemEvents?: Array<{ event: string; handler: string; selector?: string }> }
      | undefined;
    expect(nestedEach.itemEvents).toEqual([
      {
        event: 'pointerdown',
        handler: 'press',
        action: { kind: 'method', name: 'press' },
        selector: ':scope > *:nth-child(1)',
      },
    ]);

    // Single-action arrows reuse the fixed-event action grammar verbatim.
    const arrow = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-item-events-arrow')",
      'export class ArrowItemEvents extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', label: 'alpha' }];",
      '  @property({ reflect: false }) picked = 0;',
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id} onClick={() => this.picked++}>{item.label}</li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const arrowProgram = compileElementProgram(
      arrow,
      '/project/app/islands/item-events-arrow.tsx',
    ).program;
    const arrowEach = arrowProgram.parts.find((part: { k: string }) => part.k === 'each') as
      | { itemEvents?: Array<{ action: { kind: string; signal: string } }> }
      | undefined;
    expect(arrowEach.itemEvents).toEqual([
      {
        event: 'click',
        handler: '__compiledEvent0',
        action: { kind: 'increment', signal: 'picked' },
      },
    ]);

    // Non-method this.<property> handlers fail closed with the event dialect.
    const notAMethod = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-item-events-bad')",
      'export class BadItemEvents extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', label: 'alpha' }];",
      '  @property({ reflect: false }) pick = 0;',
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id} onClick={this.pick}>{item.label}</li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrowsIncludes(
      () => transform.call(ctx, notAMethod, '/project/app/islands/item-events-bad.tsx'),
      Error,
      'event handlers must be',
    );
    expect(ctx.messages[0]).toContain('OEC9016');

    // The mapper parameter is not a handler source: item.<field> stays a slot
    // expression and fails the event dialect rather than silently binding.
    const itemRef = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-item-events-item-ref')",
      'export class ItemRefEvents extends OpenElement {',
      "  @property({ reflect: false }) items = [{ id: 'a', label: 'alpha', pick: 'noop' }];",
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id} onClick={item.pick}>{item.label}</li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const itemCtx = failingContext();
    assertThrowsIncludes(
      () => transform.call(itemCtx, itemRef, '/project/app/islands/item-events-item-ref.tsx'),
      Error,
      'event handlers must be',
    );
    expect(itemCtx.messages[0]).toContain('OEC9016');
  });
});

test('compiled-element alpha.1 - canonical program records and decorator lowering', async () => {
  const { compiledElementPlugin, compileElementModule } = await loadPluginModule();
  const transform = transformOf(compiledElementPlugin());
  const source = [
    "import { element, OpenElement, property } from '@openelement/element';",
    "@element('oe-alpha-one')",
    'export class AlphaOne extends OpenElement {',
    '  @property({ type: Number, reflect: true })',
    '  count = 0;',
    "  @property({ type: Boolean, attribute: 'enabled' })",
    '  enabled = false;',
    '  render() {',
    '    return <button disabled={this.enabled} onClick={() => this.count++}>Count: {this.count}</button>;',
    '  }',
    '}',
  ].join('\n');
  const id = '/project/app/islands/alpha-one.tsx';
  const emitted = transform.call(failingContext(), source, id);
  expect(typeof emitted === 'string').toBeTruthy();

  const marker = 'const __partProgram = ';
  const start = emitted.indexOf(marker);
  expect(start >= 0, 'generated code must embed the Part Program literal').toBeTruthy();
  const end = emitted.indexOf(';', start);
  const program = JSON.parse(emitted.slice(start + marker.length, end));

  expect(program.version).toEqual(1);
  expect(program.root).toEqual({ id: 'root', kind: 'light', nodes: ['e0'] });
  expect(program.parts.map((part: { k: string }) => part.k)).toEqual(['bool', 'event', 'text']);
  expect(program.parts[0].location).toEqual({
    id: 'p0',
    kind: 'sink',
    node: 'e0',
    path: [0],
  });
  expect(program.dependencies).toEqual([
    { signal: 'enabled', owner: { kind: 'part', index: 0 }, location: 'p0' },
    { signal: 'count', owner: { kind: 'part', index: 2 }, location: 'p2' },
  ]);
  expect(program.metadata.properties).toEqual([
    {
      name: 'count',
      attribute: 'count',
      type: 'number',
      converter: 'number',
      reflect: true,
      default: 0,
    },
    {
      name: 'enabled',
      attribute: 'enabled',
      type: 'boolean',
      converter: 'boolean',
      reflect: false,
      default: false,
    },
  ]);
  expect(program.metadata.observedAttributes).toEqual(['count', 'enabled']);
  // The wire payload omits the compile-time sourceMap (no runtime consumer);
  // provenance stays on the in-memory program artifact.
  const compiled = compileElementModule(source, id);
  expect(
    compiled?.program.sourceMap.records.some(
      (record) => record.id === 'p0' && record.source.file === id,
    ),
  ).toBeTruthy();
  expect(emitted).toContain(
    'static observedAttributes: typeof __observedAttributes = __observedAttributes;',
  );
  expect(emitted).toContain('static props: typeof __compiledProps = __compiledProps;');
  expect(emitted.includes('@element')).toEqual(false);
  expect(emitted.includes('@property')).toEqual(false);
  expect(emitted.includes('accessor ')).toEqual(false);
});

test('compiled-element alpha.1 - program validation fails closed on unsafe identity', async () => {
  const [{ compileElementProgram }, { validatePartProgram }] = await Promise.all([
    import('../../../packages/compiler/src/internal/compiler/semantic-core/compile.ts'),
    import('@openelement/protocol/part-program'),
  ]);
  const source = await readFixture('counter.tsx');
  const program = compileElementProgram(source, '/project/app/islands/counter.tsx').program;

  const shiftedLocation = structuredClone(program) as {
    parts: Array<{ location: { path: number[] } }>;
  };
  shiftedLocation.parts[1].location.path = [0];
  assertThrowsIncludes(() => validatePartProgram(shiftedLocation), Error, 'location path');

  const shiftedElementLocation = structuredClone(program) as {
    locations: Array<{ id: string; path: number[]; tag?: string }>;
  };
  shiftedElementLocation.locations[0].path = [0, 99];
  assertThrowsIncludes(
    () => validatePartProgram(shiftedElementLocation),
    Error,
    'locations[0] element',
  );

  const renamedElementLocation = structuredClone(program) as {
    locations: Array<{ id: string; path: number[]; tag?: string }>;
  };
  renamedElementLocation.locations[0].tag = 'span';
  assertThrowsIncludes(
    () => validatePartProgram(renamedElementLocation),
    Error,
    'locations[0] element',
  );

  const mismatchedItemField = structuredClone(program) as {
    parts: Array<{
      item?: Array<{ children?: Array<{ field?: string }> }>;
    }>;
  };
  mismatchedItemField.parts[4].item![0].children![0].field = 'id';
  assertThrowsIncludes(
    () => validatePartProgram(mismatchedItemField),
    Error,
    'must use item field',
  );

  const mismatchedRegionSource = structuredClone(program) as {
    regions: Array<{ source: string }>;
  };
  mismatchedRegionSource.regions[0].source = 'p0';
  assertThrowsIncludes(() => validatePartProgram(mismatchedRegionSource), Error, 'regions[0]');

  const unknownPart = structuredClone(program) as { parts: Array<{ k: string }> };
  unknownPart.parts[0].k = 'future';
  assertThrowsIncludes(() => validatePartProgram(unknownPart), Error, 'unknown part kind');
});

describe('compiled-element alpha.8 - canonical page/island authoring grammar', () => {
  const prelude = [
    "import { element, OpenElement, property } from '@openelement/element';",
    "import { defineIslandConfig } from '@openelement/router';",
  ].join('\n');

  test('default-exported class with a shadow root and the island policy statement', () => {
    const source = [
      prelude,
      "export const openElement = defineIslandConfig({ hydrate: 'load', ssr: true, dsd: true });",
      "@element('oe-alpha8-page', { root: 'shadow-open' })",
      'export default class Alpha8Page extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <main><h1>{this.label}</h1></main>; }',
      '}',
    ].join('\n');
    const { code, program } = compileElementProgram(source, '/project/app/routes/alpha8.tsx', {
      staticSidecars: [ISLAND_SIDECAR],
    });
    expect(program.root.kind).toEqual('shadow-open');
    expect(code).toContain('export default class Alpha8Page extends OpenElement {');
    // The island delivery policy is copied verbatim into the compiled module.
    expect(code).toContain(
      "export const openElement = defineIslandConfig({ hydrate: 'load', ssr: true, dsd: true });",
    );
  });

  test('nested custom-element hosts lower as static shells with prop-Part attributes', () => {
    const source = [
      prelude,
      "@element('oe-alpha8-host')",
      'export class Alpha8Host extends OpenElement {',
      "  @property({ reflect: false }) marker = '';",
      '  render() {',
      '    return <main><decoupled-view marker={this.marker}></decoupled-view><live-counter></live-counter></main>;',
      '  }',
      '}',
    ].join('\n');
    const { program } = compileElementProgram(source, '/project/app/components/host.tsx');
    const template = JSON.stringify(program.template);
    expect(template.includes('"tag":"decoupled-view"'), template).toBeTruthy();
    expect(template.includes('"tag":"live-counter"'), template).toBeTruthy();
    const propPart = program.parts.find((part: { k: string }) => part.k === 'prop') as
      | { name?: string; signal?: string }
      | undefined;
    expect(propPart?.name).toEqual('marker');
    expect(propPart?.signal).toEqual('marker');
  });

  test('nested custom-element hosts inside list Region items', () => {
    const source = [
      prelude,
      "@element('oe-alpha8-list')",
      'export class Alpha8List extends OpenElement {',
      '  @property({ reflect: false }) items: Array<{ id: string; text: string }> = [];',
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id}>{item.text}<live-counter></live-counter></li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const { program } = compileElementProgram(source, '/project/app/components/list.tsx');
    const each = program.parts.find((part: { k: string }) => part.k === 'each');
    expect(each, 'each Region must exist').toBeTruthy();
    expect(JSON.stringify(each).includes('"tag":"live-counter"')).toBeTruthy();
  });

  test('fail-closed grammar boundaries for the new constructs', () => {
    const base = [
      prelude,
      "@element('oe-alpha8-bad')",
      'export class Alpha8Bad extends OpenElement {',
      "  @property({ reflect: false }) marker = '';",
      '  __RENDER__',
      '}',
    ].join('\n');
    const render = (body: string) => base.replace('__RENDER__', body);
    const expectFailure = (source: string, code: string, fragment: string) => {
      let thrown: unknown;
      try {
        compileElementProgram(source, '/project/app/components/bad.tsx', {
          staticSidecars: [ISLAND_SIDECAR],
        });
      } catch (error) {
        thrown = error;
      }
      expect(thrown instanceof CompiledElementError, `expected ${code} failure`).toBeTruthy();
      const text = String(thrown);
      expect(text).toContain(code);
      expect(text).toContain(fragment);
    };

    // Host children are the host's light content (slot projection is platform
    // behavior): they lower with the ordinary grammar.
    const withChildren = compileElementProgram(
      render('render() { return <main><live-counter><span>x</span></live-counter></main>; }'),
      '/project/app/components/host-children.tsx',
    );
    expect(
      JSON.stringify(withChildren.program.template).includes('"tag":"live-counter"'),
      'host children must lower',
    ).toBeTruthy();
    // Host event handlers are outside the grammar.
    expectFailure(
      render(
        'render() { return <main><live-counter onClick={this.marker}></live-counter></main>; }',
      ),
      'OEC9017',
      'event handlers',
    );
    // Host refs are outside the grammar.
    expectFailure(
      render('render() { return <main><live-counter ref={this.marker}></live-counter></main>; }'),
      'OEC9017',
      'may not carry a ref',
    );
    // Component (uppercase) tags remain rejected.
    expectFailure(
      render('render() { return <main><Widget></Widget></main>; }'),
      'OEC9010',
      'compiler grammar',
    );
    // Unknown root modes are rejected at the decorator.
    expectFailure(
      render('render() { return <main></main>; }').replace(
        "@element('oe-alpha8-bad')",
        "@element('oe-alpha8-bad', { root: 'sideways' })",
      ),
      'OEC9002',
      'root "sideways" is unsupported',
    );
    // A runtime top-level statement that is not the island policy fails closed.
    expectFailure(
      render('render() { return <main></main>; }') + '\nexport const other = Math.random();',
      'OEC9008',
      'runtime top-level statements',
    );
    // The island policy must stay a static defineIslandConfig object literal.
    expectFailure(
      render('render() { return <main></main>; }') +
        '\nexport const openElement = defineIslandConfig(compute());',
      'OEC9008',
      'runtime top-level statements',
    );
  });

  test('computed fields, html sinks and element options (alpha.8 grammar extension)', () => {
    // Positive: computed field drives a bool sink; innerHTML sink; element
    // options emit the facade statics.
    const source = [
      "import { computed, element, OpenElement, property, trustedHtml, type TrustedHtml } from '@openelement/element';",
      "@element('oe-alpha8-computed', { root: 'shadow-open', delegatesFocus: true, formAssociated: true })",
      'export default class Alpha8Computed extends OpenElement {',
      "  @property({ reflect: false }) label = '';",
      "  @property({ type: Object, reflect: false, attribute: false }) bodyHtml: TrustedHtml = trustedHtml('');",
      "  @property({ reflect: false, attribute: false }) noLabel = computed(() => this.label === '') as unknown as boolean;",
      '  render() {',
      '    return <main><button hidden={this.noLabel}>{this.label}</button><div innerHTML={this.bodyHtml} trustedHtml></div></main>;',
      '  }',
      '}',
    ].join('\n');
    const { code, program } = compileElementProgram(source, '/project/app/components/computed.tsx');
    const meta = program.metadata.properties.find(
      (p: { name: string }) => p.name === 'noLabel',
    ) as {
      computed?: boolean;
      deps?: string[];
    };
    expect(meta.computed).toEqual(true);
    expect(meta.deps).toEqual(['label']);
    expect(
      program.parts.some((p: { k: string }) => p.k === 'html'),
      'html Part must exist',
    ).toBeTruthy();
    expect(code).toContain('static override delegatesFocus: boolean = true;');
    expect(code).toContain('static override formAssociated: boolean = true;');
    expect(code).toContain('static __computedFields: {');
    expect(code).toContain("noLabel: (__s) => computed(() => __s.label.value === '')");

    const expectFailure = (src: string, code: string, fragment: string) => {
      let thrown: unknown;
      try {
        compileElementProgram(src, '/project/app/components/bad-computed.tsx');
      } catch (error) {
        thrown = error;
      }
      expect(
        thrown instanceof CompiledElementError,
        `expected ${code} failure, got ${String(thrown)}`,
      ).toBeTruthy();
      const text = String(thrown);
      expect(text).toContain(code);
      expect(text).toContain(fragment);
    };
    const badPrelude = [
      "import { computed, element, OpenElement, property } from '@openelement/element';",
      "@element('oe-alpha8-bad-computed')",
      'export class BadComputed extends OpenElement {',
      "  @property({ reflect: false }) label = '';",
    ].join('\n');

    // A computed that reads an undeclared member fails closed.
    expectFailure(
      [
        badPrelude,
        "  @property({ reflect: false, attribute: false }) bad = computed(() => this.missing === '') as unknown as boolean;",
        '  render() { return <main>{this.label}</main>; }',
        '}',
      ].join('\n'),
      'OEC9024',
      'this.missing',
    );
    // A computed with an attribute channel fails closed.
    expectFailure(
      [
        badPrelude,
        "  @property({ reflect: false }) bad = computed(() => this.label === '') as unknown as boolean;",
        '  render() { return <main>{this.label}</main>; }',
        '}',
      ].join('\n'),
      'OEC9025',
      'attribute: false',
    );
    // An html sink with element children fails closed (the sink owns content).
    expectFailure(
      [
        "import { element, OpenElement, property, trustedHtml, type TrustedHtml } from '@openelement/element';",
        "@element('oe-alpha8-bad-html')",
        'export class BadHtml extends OpenElement {',
        "  @property({ type: Object, reflect: false, attribute: false }) bodyHtml: TrustedHtml = trustedHtml('');",
        '  render() { return <main><div innerHTML={this.bodyHtml} trustedHtml><span>x</span></div></main>; }',
        '}',
      ].join('\n'),
      'OEC9026',
      'childless',
    );
  });
});

describe('compiled-element alpha.9 - trusted HTML sink admission matrix', () => {
  const validPrelude = [
    "import { element, OpenElement, property, trustedHtml, type TrustedHtml } from '@openelement/element';",
    "@element('oe-alpha9-trusted-html')",
    'export class Alpha9TrustedHtml extends OpenElement {',
  ];
  const validField =
    "  @property({ type: Object, reflect: false, attribute: false }) bodyHtml: TrustedHtml = trustedHtml('');";
  const sourceFor = (render: string, field = validField) =>
    [...validPrelude, field, '  render() { return ' + render + '; }', '}'].join('\n');

  test('accepts marker + Object + TrustedHtml initializer', () => {
    const result = compileElementProgram(
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml></div>'),
      '/project/app/components/alpha9-trusted-html.tsx',
    );
    expect(result.program.parts.some((part: { k: string }) => part.k === 'html')).toBeTruthy();
    expect(result.program.metadata.properties[0]).toEqual({
      name: 'bodyHtml',
      attribute: null,
      type: 'object',
      converter: 'object',
      reflect: false,
      default: null,
    });
  });

  const expectOec9026 = (name: string, source: string) => {
    let thrown: unknown;
    try {
      compileElementProgram(source, `/project/app/components/${name}.tsx`);
    } catch (error) {
      thrown = error;
    }
    expect(
      thrown instanceof CompiledElementError,
      `${name} must fail with CompiledElementError`,
    ).toBeTruthy();
    expect(String(thrown)).toContain('OEC9026');
  };

  test('accepts marker + Object + TrustedHtml initializer on a custom-element host', () => {
    // Same boundary as an intrinsic element: the custom-host prop lowering must
    // not skip innerHTML capability admission.
    const result = compileElementProgram(
      sourceFor(
        '<some-custom-element innerHTML={this.bodyHtml} trustedHtml></some-custom-element>',
      ),
      '/project/app/components/alpha9-trusted-html.tsx',
    );
    const htmlPart = result.program.parts.find((part: { k: string }) => part.k === 'html') as
      | { k: string; signal?: string }
      | undefined;
    expect(
      htmlPart,
      'custom host innerHTML must lower as a security-classified html sink',
    ).toBeTruthy();
    expect(htmlPart?.signal).toEqual('bodyHtml');
  });

  test('rejects a custom-element host innerHTML sink without the marker', () => {
    expectOec9026(
      'alpha9-custom-host-missing-marker',
      sourceFor('<some-custom-element innerHTML={this.bodyHtml}></some-custom-element>'),
    );
  });

  test('rejects a custom-element host innerHTML sink with trustedHtml={false}', () => {
    expectOec9026(
      'alpha9-custom-host-false-marker',
      sourceFor(
        '<some-custom-element innerHTML={this.bodyHtml} trustedHtml={false}></some-custom-element>',
      ),
    );
  });

  test('rejects a string-typed custom-element host innerHTML sink', () => {
    const stringField =
      "  @property({ type: String, reflect: false, attribute: false }) bodyHtml: string = '';";
    expectOec9026(
      'alpha9-custom-host-string-sink',
      sourceFor(
        '<some-custom-element innerHTML={this.bodyHtml} trustedHtml></some-custom-element>',
        stringField,
      ),
    );
  });

  test('rejects an innerHTML sink without the marker', () => {
    expectOec9026('alpha9-missing-marker', sourceFor('<div innerHTML={this.bodyHtml}></div>'));
  });

  test('rejects trustedHtml={false}', () => {
    expectOec9026(
      'alpha9-false-marker',
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml={false}></div>'),
    );
  });

  test('rejects a marker without an innerHTML sink', () => {
    expectOec9026('alpha9-marker-without-sink', sourceFor('<div trustedHtml></div>'));
  });

  test('rejects a string-typed innerHTML sink', () => {
    const stringField =
      "  @property({ type: String, reflect: false, attribute: false }) bodyHtml: string = '';";
    expectOec9026(
      'alpha9-string-sink',
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml></div>', stringField),
    );
  });

  test('rejects a TrustedHtml initializer without type:Object/attribute:false', () => {
    const incompleteField =
      "  @property({ reflect: false }) bodyHtml: TrustedHtml = trustedHtml('');";
    expectOec9026(
      'alpha9-incomplete-trusted-html-field',
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml></div>', incompleteField),
    );
  });
});

describe('compiled-element strict emission - generated statics carry explicit types for native pack', () => {
  test('module-local constants are referenced through typeof (no API growth)', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-strict-statics')",
      'export class StrictStatics extends OpenElement {',
      "  @property({ reflect: false }) label = '';",
      '  render() {',
      '    return <main>{this.label}</main>;',
      '  }',
      '}',
    ].join('\n');
    const { code } = compileElementProgram(source, '/project/app/islands/strict-statics.tsx');
    expect(code).toContain('static __partProgram: typeof __partProgram = __partProgram;');
    expect(code).toContain(
      'static __compiledProperties: typeof __compiledProperties = __compiledProperties;',
    );
    expect(code).toContain(
      'static __elementMetadata: typeof __elementMetadata = __elementMetadata;',
    );
    expect(code).toContain('static props: typeof __compiledProps = __compiledProps;');
    expect(code).toContain(
      'static observedAttributes: typeof __observedAttributes = __observedAttributes;',
    );
    // The attribute list is explicitly typed (an empty list must not infer
    // an evolving any[]).
    expect(code).toContain('const __observedAttributes: string[] = [');
  });

  test('styles keeps the authored annotation with override (#1558: .css imports)', () => {
    const source = [
      "import { element, OpenElement, property, type StyleSheetLike } from '@openelement/element';",
      "import strictStyles from './strict-styles.css';",
      "@element('oe-strict-styles', { root: 'shadow-open' })",
      'export class StrictStyles extends OpenElement {',
      '  static override styles: StyleSheetLike[] = [strictStyles];',
      "  @property({ reflect: false }) label = '';",
      '  render() {',
      '    return <main>{this.label}</main>;',
      '  }',
      '}',
    ].join('\n');
    const { code } = compileElementProgram(source, '/project/app/islands/strict-styles.tsx');
    expect(code).toContain("import strictStyles from './strict-styles.css';");
    expect(code).toContain('static override styles: StyleSheetLike[] = [strictStyles];');
  });

  test('computed factories are explicitly typed through the outer annotation', () => {
    const source = [
      "import { computed, element, OpenElement, property, type ReadonlySignal } from '@openelement/element';",
      "@element('oe-strict-computed')",
      'export class StrictComputed extends OpenElement {',
      "  @property({ reflect: false }) label = '';",
      '  @property({ reflect: false }) count = 0;',
      "  @property({ reflect: false, attribute: false }) noLabel: ReadonlySignal<boolean> = computed(() => this.label === '');",
      '  @property({ reflect: false, attribute: false }) doubled: ReadonlySignal<number> = computed(() => this.count * 2);',
      '  render() {',
      '    return <main>{this.label}</main>;',
      '  }',
      '}',
    ].join('\n');
    const { code } = compileElementProgram(source, '/project/app/islands/strict-computed.tsx');
    // Precise per-field signatures: authored return types, per-dep signal types.
    expect(code).toContain(
      'noLabel: (__s: { label: ReadonlySignal<string> }) => ReadonlySignal<boolean>;',
    );
    expect(code).toContain(
      'doubled: (__s: { count: ReadonlySignal<number> }) => ReadonlySignal<number>;',
    );
    // Inner factories stay textually unchanged and contextually typed.
    expect(code).toContain("noLabel: (__s) => computed(() => __s.label.value === '')");
  });

  test('missing ReadonlySignal binding is added as a type-only import', () => {
    const source = [
      "import { computed, element, OpenElement, property } from '@openelement/element';",
      "@element('oe-strict-import')",
      'export class StrictImport extends OpenElement {',
      "  @property({ reflect: false }) label = '';",
      '  @property({ reflect: false, attribute: false }) shouty = computed(() => this.label);',
      '  render() {',
      '    return <main>{this.label}</main>;',
      '  }',
      '}',
    ].join('\n');
    const { code } = compileElementProgram(source, '/project/app/islands/strict-import.tsx');
    expect(code).toContain("import type { ReadonlySignal } from '@openelement/element';");
    // Unannotated computed fields fall back to the contract-level signal type.
    expect(code).toContain(
      'shouty: (__s: { label: ReadonlySignal<string> }) => ReadonlySignal<unknown>;',
    );
  });

  test('element options emit override boolean flags', () => {
    const source = [
      "import { element, OpenElement } from '@openelement/element';",
      "@element('oe-strict-flags', { root: 'shadow-open', delegatesFocus: true, formAssociated: true })",
      'export class StrictFlags extends OpenElement {',
      '  render() {',
      '    return <main></main>;',
      '  }',
      '}',
    ].join('\n');
    const { code } = compileElementProgram(source, '/project/app/islands/strict-flags.tsx');
    expect(code).toContain('static override delegatesFocus: boolean = true;');
    expect(code).toContain('static override formAssociated: boolean = true;');
  });
});

describe('compiled-element alpha.11 - inline conditional class (#1556)', () => {
  test('lowers to a synthesized computed field bound to the existing class Part (IR unchanged)', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-conditional-class')",
      'export class ConditionalClass extends OpenElement {',
      '  @property({ type: Boolean, reflect: false }) flag = false;',
      '  @property({ reflect: false }) count = 0;',
      '  render() {',
      "    return <main class={this.flag ? 'on' : 'off'} data-n={this.count}>x</main>;",
      '  }',
      '}',
    ].join('\n');
    const first = compileElementProgram(source, '/project/app/islands/conditional-class.tsx');
    const second = compileElementProgram(source, '/project/app/islands/conditional-class.tsx');
    // Deterministic emission, same as every other lowering form.
    expect(JSON.stringify(first.program)).toEqual(JSON.stringify(second.program));

    const classParts = first.program.parts.filter((part: { k: string }) => part.k === 'class');
    expect(classParts.length, 'exactly one class Part').toEqual(1);
    const signal = (classParts[0] as { signal: string }).signal;
    expect(signal).toMatch(/^__compiledClass/);
    expect((classParts[0] as { path: number[] }).path).toEqual([0]);

    // The synthesized signal is a real computed property of the instance:
    // metadata records it with its source dependency, no attribute channel.
    const meta = first.program.metadata.properties.find(
      (property: { name: string }) => property.name === signal,
    ) as { computed?: boolean; deps?: string[]; attribute: string | null; reflect: boolean };
    expect(meta.computed).toEqual(true);
    expect(meta.deps).toEqual(['flag']);
    expect(meta.attribute).toEqual(null);
    expect(meta.reflect).toEqual(false);
    // The synthesized field adds no attribute channel; the declared
    // properties' own channels (reflect: false keeps the attribute) are the
    // only observed attributes.
    expect(first.program.metadata.observedAttributes).toEqual(['flag', 'count']);

    // The generated module derives the class value from the source signal;
    // this module never imported computed, so the factory references the
    // synthesized binding (asserted on its own test below).
    expect(first.code).toContain(
      `${signal}: (__s) => __openelementComputed(() => __s.flag.value ? 'on' : 'off'),`,
    );
  });

  test('binds the synthesized computed import when the module never imported computed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-conditional-class-import')",
      'export class ConditionalClassImport extends OpenElement {',
      '  @property({ type: Boolean, reflect: false }) flag = false;',
      "  render() { return <main class={this.flag ? 'on' : ''}>x</main>; }",
      '}',
    ].join('\n');
    const { code } = compileElementProgram(
      source,
      '/project/app/islands/conditional-class-import.tsx',
    );
    expect(code).toContain(
      "import { computed as __openelementComputed } from '@openelement/element';",
    );
    expect(code).toContain('__openelementComputed(() => __s.flag.value');
    // The authored import survives with the compile-time-only bindings
    // (element, property) stripped, exactly as any other module does.
    expect(code).toContain("import { OpenElement } from '@openelement/element';");
  });

  test('reuses the authored local binding when computed is imported under an alias', () => {
    const source = [
      "import { computed as derive, element, OpenElement, property } from '@openelement/element';",
      "@element('oe-conditional-class-alias')",
      'export class ConditionalClassAlias extends OpenElement {',
      '  @property({ type: Boolean, reflect: false }) flag = false;',
      "  render() { return <main class={this.flag ? 'on' : 'off'}>x</main>; }",
      '}',
    ].join('\n');
    const { code } = compileElementProgram(
      source,
      '/project/app/islands/conditional-class-alias.tsx',
    );
    expect(code).toContain('derive(() => __s.flag.value');
    expect(code).not.toContain('__openelementComputed');
  });

  test('supports the computed-condition grammar over declared properties', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-conditional-class-grammar')",
      'export class ConditionalClassGrammar extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      '  @property({ reflect: false }) items: string[] = [];',
      '  render() {',
      "    return <main class={this.count > 3 && this.items.length > 0 ? 'loaded' : ''}>x</main>;",
      '  }',
      '}',
    ].join('\n');
    const { program } = compileElementProgram(
      source,
      '/project/app/islands/conditional-class-grammar.tsx',
    );
    const classPart = program.parts.find((part: { k: string }) => part.k === 'class') as {
      signal: string;
    };
    const meta = program.metadata.properties.find(
      (property: { name: string }) => property.name === classPart.signal,
    ) as { deps?: string[] };
    // deps collect in read order across the whole condition.
    expect(meta.deps).toEqual(['count', 'items']);
  });
});
