/**
 * @openelement/element — #1160 TSX-to-Part Program vertical compiler v1.
 *
 * Behavior-first coverage for the open:compiled-element v1 transform:
 *   - the one-component fixture is transformed through the actual
 *     compiledElementPlugin() Vite transform hook
 *   - the emitted module embeds one deterministic, serializable Part Program
 *     (static structure + typed Part/Region instructions) that deep-equals the
 *     frozen expected-program.json fixture consumed by the element runtime test
 *   - re-running the transform yields byte-identical output
 *   - unsupported syntax fails closed at transform time with a source-located
 *     diagnostic; no runtime fallback is emitted
 *   - measurement evidence (generated bytes, instruction count) is recorded
 *
 * The compiler modules are loaded via dynamic import so a RED run proves the
 * harness and fixtures work while the new vertical behavior is absent.
 */

import { assert, assertEquals, assertStringIncludes, assertThrows } from '@std/assert';
import type { Plugin } from 'vite';

const FIXTURE_DIR = new URL('../__fixtures__/compiled-element-v1/', import.meta.url);

async function readFixture(name: string): Promise<string> {
  return await Deno.readTextFile(new URL(name, FIXTURE_DIR));
}

type PluginModule = typeof import('../src/internal/compiler/plugin.ts');

async function loadPluginModule(): Promise<PluginModule> {
  return await import('../src/internal/compiler/plugin.ts');
}

interface TransformContext {
  error(message: string): never;
}

function failingContext(): TransformContext & { messages: string[] } {
  const messages: string[] = [];
  return {
    messages,
    error(message: string): never {
      messages.push(message);
      throw new Error(message);
    },
  };
}

type TransformHook = (this: TransformContext, code: string, id: string) => string | null;

function transformOf(plugin: Plugin): TransformHook {
  assert(typeof plugin.transform === 'function', 'plugin must expose a transform hook');
  return plugin.transform as unknown as TransformHook;
}

function decodeBase64(value: string): string {
  const binary = atob(value);
  const bytes = Uint8Array.from(binary, (char) => char.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

Deno.test('compiled-element v1 - harness sanity (fixtures load)', async () => {
  const counter = await readFixture('counter.tsx');
  const expected = await readFixture('expected-program.json');
  assert(counter.includes("@element('oe-program-counter')"));
  assertEquals(JSON.parse(expected).tag, 'oe-program-counter');
});

Deno.test('compiled-element v1 - the standalone compiler hook has its canonical name', async () => {
  // The default Router pipeline (open:core) embeds the compiler instead of
  // registering this standalone plugin; that composition is pinned by the
  // adapter-side openPlugin ordering tests.
  const { compiledElementPlugin } = await loadPluginModule();
  assertEquals(compiledElementPlugin().name, 'open:compiled-element');
});

Deno.test('compiled-element v1 - fixture transforms through the Vite hook', async (t) => {
  const { compiledElementPlugin } = await loadPluginModule();
  const plugin = compiledElementPlugin();
  const transform = transformOf(plugin);
  const source = await readFixture('counter.tsx');
  const id = '/project/app/islands/counter.tsx';

  let emitted: string | null = null;
  await t.step('transform returns generated code', () => {
    emitted = transform.call(failingContext(), source, id);
    assert(typeof emitted === 'string');
    assertStringIncludes(emitted, '__partProgram');
  });

  const programLiteral = (code: string): string => {
    const marker = 'const __partProgram = ';
    const start = code.indexOf(marker);
    assert(start >= 0, 'generated code must embed the Part Program literal');
    const end = code.indexOf(';', start);
    return code.slice(start + marker.length, end);
  };

  await t.step('emitted program deep-equals the frozen expected program', async () => {
    const expected = JSON.parse(await readFixture('expected-program.json'));
    assertEquals(JSON.parse(programLiteral(emitted!)), expected);
  });

  await t.step('emitted metadata preserves @property reflection decisions (R2)', () => {
    const marker = 'const __compiledProperties = ';
    const start = emitted!.indexOf(marker);
    assert(start >= 0, 'generated code must embed compiled-property metadata');
    const end = emitted!.indexOf(';', start);
    const metadata = JSON.parse(emitted!.slice(start + marker.length, end));
    // Exact fixture decisions: count reflected; label and items not reflected.
    assertEquals(metadata, [
      {
        name: 'count',
        attribute: 'count',
        type: 'number',
        converter: 'number',
        reflect: true,
        default: 0,
      },
      {
        name: 'label',
        attribute: 'label',
        type: 'string',
        converter: 'string',
        reflect: false,
        default: 'ready',
      },
      {
        name: 'items',
        attribute: 'items',
        type: 'array',
        converter: 'array',
        reflect: false,
        default: [
          { id: 'a', text: 'alpha' },
          { id: 'b', text: 'beta' },
        ],
      },
    ]);
    // Compile-time data only: no runtime reflection behavior is emitted.
    assertEquals(emitted!.includes('attributeChangedCallback'), false);
    assertStringIncludes(emitted!, 'static __compiledProperties = __compiledProperties;');
    assertStringIncludes(emitted!, 'static props = __compiledProps;');
    assertStringIncludes(emitted!, 'static observedAttributes = __observedAttributes;');
  });

  await t.step('program carries static structure plus typed Part/Region instructions', () => {
    const program = JSON.parse(programLiteral(emitted!));
    assertEquals(program.version, 1);
    const kinds = program.parts.map((p: { k: string }) => p.k).sort();
    assertEquals(kinds, ['each', 'event', 'prop', 'text', 'when']);
    // instruction count = typed parts; static structure lives in the template
    assertEquals(program.parts.length, 5);
  });

  await t.step('emitted code contains no VNode/binding/hydration fallback vocabulary', () => {
    for (
      const token of [
        'VNode',
        'BindingDescriptor',
        'hydrationScope',
        'HydrationScope',
        'createElement(',
      ]
    ) {
      assertEquals(emitted!.includes(token), false, `generated code must not contain ${token}`);
    }
    assertStringIncludes(emitted!, 'not available in 0.44');
  });

  await t.step('re-running the transform yields byte-identical output', () => {
    const again = transform.call(failingContext(), source, id);
    assertEquals(again, emitted);
  });

  await t.step('inline source map carries x_openElement v1 program source records', async () => {
    const marker = '//# sourceMappingURL=data:application/json;base64,';
    const line = emitted!.split('\n').find((candidate) => candidate.startsWith(marker));
    assert(line, 'generated code must embed an inline base64 source map');
    const map = JSON.parse(decodeBase64(line.slice(marker.length)));
    assertEquals(map.version, 3);
    assertEquals(map.sources, [id]);
    // sourcesContent carries the original TSX source verbatim.
    assertEquals(map.sourcesContent, [source]);
    // The frozen fixture program is the source of truth for the v1 records:
    // x_openElement must deep-equal its sourceMap (file + every record).
    const expected = JSON.parse(await readFixture('expected-program.json'));
    assertEquals(map.x_openElement.version, 1);
    assertEquals(map.x_openElement, expected.sourceMap);
    assertEquals(map.x_openElement.records.length, expected.sourceMap.records.length);
  });

  await t.step('measurement evidence is recorded', () => {
    const programJson = programLiteral(emitted!);
    const generatedBytes = new TextEncoder().encode(emitted!).length;
    const programBytes = new TextEncoder().encode(programJson).length;
    const instructionCount = JSON.parse(programJson).parts.length;
    // Frozen program evidence (alpha.0 fixture): regenerated only by changing the
    // fixture grammar. These are evidence, not a performance claim.
    assertEquals(instructionCount, 5);
    console.log(
      JSON.stringify({
        proof: 'adapter-compiler',
        generatedBytes,
        programBytes,
        instructionCount,
      }),
    );
  });

  await t.step('files outside the program grammar marker pass through untouched', () => {
    const result = transform.call(
      failingContext(),
      'export class Plain { render() { return null; } }',
      '/project/app/components/plain.tsx',
    );
    assertEquals(result, null);
  });
});

Deno.test('compiled-element v1 - unsupported syntax fails closed with located diagnostics', async (t) => {
  const { compiledElementPlugin } = await loadPluginModule();
  const transform = transformOf(compiledElementPlugin());

  await t.step('spread attributes are rejected with file/line location', async () => {
    const source = await readFixture('unsupported-spread.tsx');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/unsupported-spread.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    assert(thrown, 'transform must throw for unsupported syntax');
    assertEquals(ctx.messages.length, 1);
    const message = ctx.messages[0];
    assertStringIncludes(message, 'unsupported-spread.tsx:');
    assertStringIncludes(message, 'OEC9');
    assertStringIncludes(message.toLowerCase(), 'spread');
  });

  await t.step('unknown decorators on an OpenElement class fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      'declare function mystery(): ClassDecorator;',
      "@element('oe-proof-mystery')",
      '@mystery()',
      'export class Mystery extends OpenElement {',
      '  render() { return <div>ok</div>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/mystery.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    assert(thrown, 'transform must throw for unknown decorators');
    assertStringIncludes(ctx.messages[0], 'mystery.tsx:');
    assertStringIncludes(ctx.messages[0].toLowerCase(), 'decorator');
  });

  await t.step('classes not extending OpenElement fail closed', () => {
    const source = [
      "import { element } from '@openelement/element';",
      "@element('oe-proof-alien')",
      'export class Alien extends HTMLElement {',
      '  render() { return null; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    let thrown: Error | null = null;
    try {
      transform.call(ctx, source, '/project/app/islands/alien.tsx');
    } catch (err) {
      thrown = err as Error;
    }
    assert(thrown, 'transform must throw for non-OpenElement base classes');
    assertStringIncludes(ctx.messages[0], 'OpenElement');
  });

  await t.step('path-addressed fixed sinks after dynamic anchors fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-unsafe-path')",
      'export class UnsafePath extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() {',
      '    return <div>{this.count > 0 ? <p>positive</p> : <p>zero</p>}<input value={this.label} /></div>;',
      '  }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/unsafe-path.tsx'),
      Error,
      'OEC9015',
    );
    assertStringIncludes(ctx.messages[0], 'dynamic anchor');
  });

  await t.step('duplicate static and dynamic attribute sinks fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-duplicate-attribute')",
      'export class DuplicateAttribute extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <input value="static" value={this.label} />; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/duplicate-attribute.tsx'),
      Error,
      'duplicate attribute',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9011');
  });

  await t.step('void elements with children fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-void-children')",
      'export class VoidChildren extends OpenElement {',
      '  render() { return <input>not supported</input>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/void-children.tsx'),
      Error,
      'void element',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9013');
  });

  await t.step('event-looking attribute sinks fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-unsafe-attribute')",
      'export class UnsafeAttribute extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <input onclick={this.label} />; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/unsafe-attribute.tsx'),
      Error,
      'unsafe',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9011');
  });

  await t.step('conditions outside the seed operator fail closed', () => {
    const source = [
      "import { element, OpenElement, property } from '@openelement/element';",
      "@element('oe-proof-unsupported-condition')",
      'export class UnsupportedCondition extends OpenElement {',
      '  @property({ reflect: false }) count = 0;',
      '  render() { return <div>{this.count === 1 ? <p>one</p> : <p>other</p>}</div>; }',
      '}',
    ].join('\n');
    const ctx = failingContext();
    assertThrows(
      () => transform.call(ctx, source, '/project/app/islands/unsupported-condition.tsx'),
      Error,
      'finite numeric literal',
    );
    assertStringIncludes(ctx.messages[0], 'OEC9013');
  });

  await t.step(
    'list Regions admit multi-field item slots and fail closed on non-item expressions',
    async () => {
      const { compileElementProgram } = await import(
        '../src/internal/compiler/semantic-core/compile.ts'
      );
      // alpha.8: item templates carry one ival/iattr slot per item field — a row
      // may bind {item.text} twice and per-item attributes (id, href, ...).
      const source = [
        "import { element, OpenElement, property } from '@openelement/element';",
        "@element('oe-proof-multi-field')",
        'export class MultiField extends OpenElement {',
        "  @property({ reflect: false }) items = [{ id: 'a', text: 'alpha', link: '/a' }];",
        '  render() {',
        '    return <ul>{this.items.map((item) => <li key={item.id} id={item.id}>{item.text}{item.text}<a href={item.link}>{item.text}</a></li>)}</ul>;',
        '  }',
        '}',
      ].join('\n');
      const program = compileElementProgram(source, '/project/app/islands/multi-field.tsx').program;
      const each = program.parts.find((part: { k: string }) => part.k === 'each') as {
        field?: string;
        item: unknown[];
      } | undefined;
      assert(each, 'each Region must exist');
      assertEquals(
        each.field,
        undefined,
        'multi-field templates omit the Region field restatement',
      );
      assert(JSON.stringify(each.item).includes('"iattrs"'));

      // Expressions that are not item field slots still fail closed.
      const bad = [
        "import { element, OpenElement, property } from '@openelement/element';",
        "@element('oe-proof-bad-item')",
        'export class BadItem extends OpenElement {',
        "  @property({ reflect: false }) items = [{ id: 'a', text: 'alpha' }];",
        '  render() {',
        '    return <ul>{this.items.map((item) => <li key={item.id}>{item.text.toUpperCase()}</li>)}</ul>;',
        '  }',
        '}',
      ].join('\n');
      const ctx = failingContext();
      assertThrows(
        () => transform.call(ctx, bad, '/project/app/islands/bad-item.tsx'),
        Error,
        'item child must be',
      );
      assertStringIncludes(ctx.messages[0], 'OEC9013');
    },
  );
});

Deno.test('compiled-element alpha.1 - canonical program records and decorator lowering', async () => {
  const { compiledElementPlugin } = await loadPluginModule();
  const transform = transformOf(compiledElementPlugin());
  const source = [
    "import { element, OpenElement, property } from '@openelement/element';",
    "@element('oe-alpha-one')",
    'export class AlphaOne extends OpenElement {',
    '  @property({ type: Number, reflect: true })',
    '  count = 0;',
    "  @property({ type: Boolean, attribute: 'enabled' })",
    '  enabled = false;',
    '  render() {',
    '    return <button disabled={this.enabled} onClick={() => this.count++}>Count: {this.count}</button>;',
    '  }',
    '}',
  ].join('\n');
  const id = '/project/app/islands/alpha-one.tsx';
  const emitted = transform.call(failingContext(), source, id);
  assert(typeof emitted === 'string');

  const marker = 'const __partProgram = ';
  const start = emitted.indexOf(marker);
  assert(start >= 0, 'generated code must embed the Part Program literal');
  const end = emitted.indexOf(';', start);
  const program = JSON.parse(emitted.slice(start + marker.length, end));

  assertEquals(program.version, 1);
  assertEquals(program.root, { id: 'root', kind: 'light', nodes: ['e0'] });
  assertEquals(program.parts.map((part: { k: string }) => part.k), ['bool', 'event', 'text']);
  assertEquals(program.parts[0].location, {
    id: 'p0',
    kind: 'sink',
    node: 'e0',
    path: [0],
  });
  assertEquals(program.dependencies, [
    { signal: 'enabled', owner: { kind: 'part', index: 0 }, location: 'p0' },
    { signal: 'count', owner: { kind: 'part', index: 2 }, location: 'p2' },
  ]);
  assertEquals(program.metadata.properties, [
    {
      name: 'count',
      attribute: 'count',
      type: 'number',
      converter: 'number',
      reflect: true,
      default: 0,
    },
    {
      name: 'enabled',
      attribute: 'enabled',
      type: 'boolean',
      converter: 'boolean',
      reflect: false,
      default: false,
    },
  ]);
  assertEquals(program.metadata.observedAttributes, ['count', 'enabled']);
  assert(
    program.sourceMap.records.some((record: { id: string; source: { file: string } }) =>
      record.id === 'p0' && record.source.file === id
    ),
  );
  assertStringIncludes(emitted, 'static observedAttributes = __observedAttributes;');
  assertStringIncludes(emitted, 'static props = __compiledProps;');
  assertEquals(emitted.includes('@element'), false);
  assertEquals(emitted.includes('@property'), false);
  assertEquals(emitted.includes('accessor '), false);
});

Deno.test('compiled-element alpha.1 - program validation fails closed on unsafe identity', async () => {
  const [{ compileElementProgram }, { validatePartProgram }] = await Promise.all([
    import('../src/internal/compiler/semantic-core/compile.ts'),
    import('../src/internal/compiler/semantic-core/program.ts'),
  ]);
  const source = await readFixture('counter.tsx');
  const program = compileElementProgram(source, '/project/app/islands/counter.tsx').program;

  const shiftedLocation = structuredClone(program) as {
    parts: Array<{ location: { path: number[] } }>;
  };
  shiftedLocation.parts[1].location.path = [0];
  assertThrows(() => validatePartProgram(shiftedLocation), Error, 'location path');

  const shiftedElementLocation = structuredClone(program) as {
    locations: Array<{ id: string; path: number[]; tag?: string }>;
  };
  shiftedElementLocation.locations[0].path = [0, 99];
  assertThrows(
    () => validatePartProgram(shiftedElementLocation),
    Error,
    'locations[0] element',
  );

  const renamedElementLocation = structuredClone(program) as {
    locations: Array<{ id: string; path: number[]; tag?: string }>;
  };
  renamedElementLocation.locations[0].tag = 'span';
  assertThrows(
    () => validatePartProgram(renamedElementLocation),
    Error,
    'locations[0] element',
  );

  const mismatchedItemField = structuredClone(program) as {
    parts: Array<{
      item?: Array<{ children?: Array<{ field?: string }> }>;
    }>;
  };
  mismatchedItemField.parts[4].item![0].children![0].field = 'id';
  assertThrows(
    () => validatePartProgram(mismatchedItemField),
    Error,
    'must use item field',
  );

  const mismatchedRegionSource = structuredClone(program) as {
    regions: Array<{ source: string }>;
  };
  mismatchedRegionSource.regions[0].source = 'p0';
  assertThrows(
    () => validatePartProgram(mismatchedRegionSource),
    Error,
    'regions[0]',
  );

  const unknownPart = structuredClone(program) as { parts: Array<{ k: string }> };
  unknownPart.parts[0].k = 'future';
  assertThrows(() => validatePartProgram(unknownPart), Error, 'unknown part kind');
});

Deno.test('compiled-element alpha.8 - canonical page/island authoring grammar', async (t) => {
  const { compileElementProgram, CompiledElementError } = await import(
    '../src/internal/compiler/semantic-core/compile.ts'
  );

  const prelude = [
    "import { element, OpenElement, property } from '@openelement/element';",
    "import { defineIslandConfig } from '@openelement/router';",
  ].join('\n');

  await t.step('default-exported class with a shadow root and the island policy statement', () => {
    const source = [
      prelude,
      "export const openElement = defineIslandConfig({ hydrate: 'load', ssr: true, dsd: true });",
      "@element('oe-alpha8-page', { root: 'shadow-open' })",
      'export default class Alpha8Page extends OpenElement {',
      "  @property({ reflect: false }) label = 'ready';",
      '  render() { return <main><h1>{this.label}</h1></main>; }',
      '}',
    ].join('\n');
    const { code, program } = compileElementProgram(source, '/project/app/routes/alpha8.tsx');
    assertEquals(program.root.kind, 'shadow-open');
    assertStringIncludes(code, 'export default class Alpha8Page extends OpenElement {');
    // The island delivery policy is copied verbatim into the compiled module.
    assertStringIncludes(
      code,
      "export const openElement = defineIslandConfig({ hydrate: 'load', ssr: true, dsd: true });",
    );
  });

  await t.step(
    'nested custom-element hosts lower as static shells with prop-Part attributes',
    () => {
      const source = [
        prelude,
        "@element('oe-alpha8-host')",
        'export class Alpha8Host extends OpenElement {',
        "  @property({ reflect: false }) marker = '';",
        '  render() {',
        '    return <main><decoupled-view marker={this.marker}></decoupled-view><live-counter></live-counter></main>;',
        '  }',
        '}',
      ].join('\n');
      const { program } = compileElementProgram(source, '/project/app/components/host.tsx');
      const template = JSON.stringify(program.template);
      assert(template.includes('"tag":"decoupled-view"'), template);
      assert(template.includes('"tag":"live-counter"'), template);
      const propPart = program.parts.find((part: { k: string }) => part.k === 'prop') as
        | { name?: string; signal?: string }
        | undefined;
      assertEquals(propPart?.name, 'marker');
      assertEquals(propPart?.signal, 'marker');
    },
  );

  await t.step('nested custom-element hosts inside list Region items', () => {
    const source = [
      prelude,
      "@element('oe-alpha8-list')",
      'export class Alpha8List extends OpenElement {',
      '  @property({ reflect: false }) items: Array<{ id: string; text: string }> = [];',
      '  render() {',
      '    return <ul>{this.items.map((item) => <li key={item.id}>{item.text}<live-counter></live-counter></li>)}</ul>;',
      '  }',
      '}',
    ].join('\n');
    const { program } = compileElementProgram(source, '/project/app/components/list.tsx');
    const each = program.parts.find((part: { k: string }) => part.k === 'each');
    assert(each, 'each Region must exist');
    assert(JSON.stringify(each).includes('"tag":"live-counter"'));
  });

  await t.step('fail-closed grammar boundaries for the new constructs', () => {
    const base = [
      prelude,
      "@element('oe-alpha8-bad')",
      'export class Alpha8Bad extends OpenElement {',
      "  @property({ reflect: false }) marker = '';",
      '  __RENDER__',
      '}',
    ].join('\n');
    const render = (body: string) => base.replace('__RENDER__', body);
    const expectFailure = (source: string, code: string, fragment: string) => {
      let thrown: unknown;
      try {
        compileElementProgram(source, '/project/app/components/bad.tsx');
      } catch (error) {
        thrown = error;
      }
      assert(thrown instanceof CompiledElementError, `expected ${code} failure`);
      const text = String(thrown);
      assertStringIncludes(text, code);
      assertStringIncludes(text, fragment);
    };

    // Host children are the host's light content (slot projection is platform
    // behavior): they lower with the ordinary grammar.
    const withChildren = compileElementProgram(
      render('render() { return <main><live-counter><span>x</span></live-counter></main>; }'),
      '/project/app/components/host-children.tsx',
    );
    assert(
      JSON.stringify(withChildren.program.template).includes('"tag":"live-counter"'),
      'host children must lower',
    );
    // Host event handlers are outside the grammar.
    expectFailure(
      render(
        'render() { return <main><live-counter onClick={this.marker}></live-counter></main>; }',
      ),
      'OEC9017',
      'event handlers',
    );
    // Host refs are outside the grammar.
    expectFailure(
      render('render() { return <main><live-counter ref={this.marker}></live-counter></main>; }'),
      'OEC9017',
      'may not carry a ref',
    );
    // Component (uppercase) tags remain rejected.
    expectFailure(
      render('render() { return <main><Widget></Widget></main>; }'),
      'OEC9010',
      'compiler grammar',
    );
    // Unknown root modes are rejected at the decorator.
    expectFailure(
      render('render() { return <main></main>; }').replace(
        "@element('oe-alpha8-bad')",
        "@element('oe-alpha8-bad', { root: 'sideways' })",
      ),
      'OEC9002',
      'root "sideways" is unsupported',
    );
    // A runtime top-level statement that is not the island policy fails closed.
    expectFailure(
      render('render() { return <main></main>; }') + '\nexport const other = Math.random();',
      'OEC9008',
      'runtime top-level statements',
    );
    // The island policy must stay a static defineIslandConfig object literal.
    expectFailure(
      render('render() { return <main></main>; }') +
        '\nexport const openElement = defineIslandConfig(compute());',
      'OEC9008',
      'runtime top-level statements',
    );
  });

  await t.step(
    'computed fields, html sinks and element options (alpha.8 grammar extension)',
    () => {
      // Positive: computed field drives a bool sink; innerHTML sink; element
      // options emit the facade statics.
      const source = [
        "import { computed, element, OpenElement, property, trustedHtml, type TrustedHtml } from '@openelement/element';",
        "@element('oe-alpha8-computed', { root: 'shadow-open', delegatesFocus: true, formAssociated: true })",
        'export default class Alpha8Computed extends OpenElement {',
        "  @property({ reflect: false }) label = '';",
        "  @property({ type: Object, reflect: false, attribute: false }) bodyHtml: TrustedHtml = trustedHtml('');",
        "  @property({ reflect: false, attribute: false }) noLabel = computed(() => this.label === '') as unknown as boolean;",
        '  render() {',
        '    return <main><button hidden={this.noLabel}>{this.label}</button><div innerHTML={this.bodyHtml} trustedHtml></div></main>;',
        '  }',
        '}',
      ].join('\n');
      const { code, program } = compileElementProgram(
        source,
        '/project/app/components/computed.tsx',
      );
      const meta = program.metadata.properties.find((p: { name: string }) =>
        p.name === 'noLabel'
      ) as {
        computed?: boolean;
        deps?: string[];
      };
      assertEquals(meta.computed, true);
      assertEquals(meta.deps, ['label']);
      assert(program.parts.some((p: { k: string }) => p.k === 'html'), 'html Part must exist');
      assertStringIncludes(code, 'static delegatesFocus = true;');
      assertStringIncludes(code, 'static formAssociated = true;');
      assertStringIncludes(code, 'static __computedFields = {');
      assertStringIncludes(code, "noLabel: (__s) => computed(() => __s.label.value === '')");

      const expectFailure = (src: string, code: string, fragment: string) => {
        let thrown: unknown;
        try {
          compileElementProgram(src, '/project/app/components/bad-computed.tsx');
        } catch (error) {
          thrown = error;
        }
        assert(
          thrown instanceof CompiledElementError,
          `expected ${code} failure, got ${String(thrown)}`,
        );
        const text = String(thrown);
        assertStringIncludes(text, code);
        assertStringIncludes(text, fragment);
      };
      const badPrelude = [
        "import { computed, element, OpenElement, property } from '@openelement/element';",
        "@element('oe-alpha8-bad-computed')",
        'export class BadComputed extends OpenElement {',
        "  @property({ reflect: false }) label = '';",
      ].join('\n');

      // A computed that reads an undeclared member fails closed.
      expectFailure(
        [
          badPrelude,
          "  @property({ reflect: false, attribute: false }) bad = computed(() => this.missing === '') as unknown as boolean;",
          '  render() { return <main>{this.label}</main>; }',
          '}',
        ].join('\n'),
        'OEC9024',
        'this.missing',
      );
      // A computed with an attribute channel fails closed.
      expectFailure(
        [
          badPrelude,
          "  @property({ reflect: false }) bad = computed(() => this.label === '') as unknown as boolean;",
          '  render() { return <main>{this.label}</main>; }',
          '}',
        ].join('\n'),
        'OEC9025',
        'attribute: false',
      );
      // An html sink with element children fails closed (the sink owns content).
      expectFailure(
        [
          "import { element, OpenElement, property, trustedHtml, type TrustedHtml } from '@openelement/element';",
          "@element('oe-alpha8-bad-html')",
          'export class BadHtml extends OpenElement {',
          "  @property({ type: Object, reflect: false, attribute: false }) bodyHtml: TrustedHtml = trustedHtml('');",
          '  render() { return <main><div innerHTML={this.bodyHtml} trustedHtml><span>x</span></div></main>; }',
          '}',
        ].join('\n'),
        'OEC9026',
        'childless',
      );
    },
  );
});

Deno.test('compiled-element alpha.9 - trusted HTML sink admission matrix', async (t) => {
  const { compileElementProgram, CompiledElementError } = await import(
    '../src/internal/compiler/semantic-core/compile.ts'
  );

  const validPrelude = [
    "import { element, OpenElement, property, trustedHtml, type TrustedHtml } from '@openelement/element';",
    "@element('oe-alpha9-trusted-html')",
    'export class Alpha9TrustedHtml extends OpenElement {',
  ];
  const validField =
    "  @property({ type: Object, reflect: false, attribute: false }) bodyHtml: TrustedHtml = trustedHtml('');";
  const sourceFor = (render: string, field = validField) =>
    [...validPrelude, field, '  render() { return ' + render + '; }', '}'].join('\n');

  await t.step('accepts marker + Object + TrustedHtml initializer', () => {
    const result = compileElementProgram(
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml></div>'),
      '/project/app/components/alpha9-trusted-html.tsx',
    );
    assert(result.program.parts.some((part: { k: string }) => part.k === 'html'));
    assertEquals(result.program.metadata.properties[0], {
      name: 'bodyHtml',
      attribute: null,
      type: 'object',
      converter: 'object',
      reflect: false,
      default: null,
    });
  });

  const expectOec9026 = (name: string, source: string) => {
    let thrown: unknown;
    try {
      compileElementProgram(source, `/project/app/components/${name}.tsx`);
    } catch (error) {
      thrown = error;
    }
    assert(thrown instanceof CompiledElementError, `${name} must fail with CompiledElementError`);
    assertStringIncludes(String(thrown), 'OEC9026');
  };

  await t.step('rejects an innerHTML sink without the marker', () => {
    expectOec9026(
      'alpha9-missing-marker',
      sourceFor('<div innerHTML={this.bodyHtml}></div>'),
    );
  });

  await t.step('rejects trustedHtml={false}', () => {
    expectOec9026(
      'alpha9-false-marker',
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml={false}></div>'),
    );
  });

  await t.step('rejects a marker without an innerHTML sink', () => {
    expectOec9026('alpha9-marker-without-sink', sourceFor('<div trustedHtml></div>'));
  });

  await t.step('rejects a string-typed innerHTML sink', () => {
    const stringField =
      "  @property({ type: String, reflect: false, attribute: false }) bodyHtml: string = '';";
    expectOec9026(
      'alpha9-string-sink',
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml></div>', stringField),
    );
  });

  await t.step('rejects a TrustedHtml initializer without type:Object/attribute:false', () => {
    const incompleteField =
      "  @property({ reflect: false }) bodyHtml: TrustedHtml = trustedHtml('');";
    expectOec9026(
      'alpha9-incomplete-trusted-html-field',
      sourceFor('<div innerHTML={this.bodyHtml} trustedHtml></div>', incompleteField),
    );
  });
});
