/**
 * Install-command projection + gate (#1414 item 5).
 *
 * The documented install command has ONE owner: the create CLI exports the
 * canonical string (packages/create/src/install-command.ts). This tool projects
 * it into `www/app/data/_generated-install-command.ts`, the site render path
 * interpolates `{{INSTALL_COMMAND}}` from that module (the same placeholder
 * mechanism as `{{OPENELEMENT_VERSION}}`), and every curated display copy in
 * the repository is asserted against the canonical string — a hand-written
 * command that differs from what the CLI prints fails `--check`, which
 * gate:release (the release train) runs.
 *
 * The assertion compares the command's *prefix* (the `deno run … npm:…@tag`
 * part) so a documentation example may name its own project (`my-app`) while
 * every flag and specifier stays the CLI's.
 */
import { fromFileUrl, join } from '@std/path';
import { createInstallCommand } from '../../packages/create/src/install-command.ts';

export const INSTALL_COMMAND_ARTIFACT = 'www/app/data/_generated-install-command.ts';
const repoRoot = fromFileUrl(new URL('../../', import.meta.url));

/**
 * Files that display the install command to a reader. Each must either use the
 * generated truth (the placeholder or the generated module) or carry a command
 * whose prefix matches the canonical one exactly.
 *
 * CHANGELOG.md is deliberately absent: it is a dated record of what shipped,
 * so an older command in it is history, not current guidance (the same reason
 * blog dispatches are excluded from the content gate).
 */
const DISPLAY_FILES: readonly string[] = [
  'README.md',
  'README.zh.md',
  'packages/create/README.md',
  'www/content/docs/guide/getting-started.md',
  'www/content/docs/guide/getting-started.zh.md',
  'www/content/docs/guide/tutorial.md',
  'www/content/docs/guide/tutorial.zh.md',
  'www/app/routes/index/index.tsx',
  'www/app/components/page-home.tsx',
  'www/e2e/cinematic-home.spec.ts',
];

/**
 * A documented install command: any `deno run … npm:@openelement/create@tag`
 * invocation. The match ends at the specifier — the project name that follows
 * is a free example, so two copies agree exactly when their flags and
 * specifier agree.
 */
const DOCUMENTED_COMMAND =
  /deno run (?:-{1,2}[a-zA-Z][a-zA-Z-]*(?: [^-\s][^\s]*)? )*npm:@openelement\/create@[^\s]+/g;

/**
 * The comparable shape of an install command: its flags and specifier, with
 * the dist-tag normalized so a deliberately pinned version is compared on the
 * flags alone (`@<tag>`).
 */
function commandShape(command: string): string {
  const match = command.match(DOCUMENTED_COMMAND)?.[0];
  if (!match) return '';
  return match.replace(/@[^\s]+$/, '@<tag>');
}

const canonicalCommand = createInstallCommand('my-app');
const canonicalShape = commandShape(canonicalCommand);

export interface InstallCommandBuild {
  command: string;
  failures: string[];
}

export async function buildInstallCommand(): Promise<InstallCommandBuild> {
  const failures: string[] = [];
  if (canonicalShape === '') {
    failures.push('the canonical install command does not match the documented command shape');
  }

  for (const relative of DISPLAY_FILES) {
    let text: string;
    try {
      text = await Deno.readTextFile(join(repoRoot, relative));
    } catch (cause) {
      throw new Error(`${relative} is missing`, { cause });
    }
    if (text.includes('{{INSTALL_COMMAND}}') || text.includes('_generated-install-command.ts')) {
      // Interpolated: the reader sees the generated string, so there is
      // nothing here to compare.
      continue;
    }
    const documented = [...text.matchAll(DOCUMENTED_COMMAND)].map((match) => match[0]);
    for (const command of documented) {
      if (commandShape(command) === canonicalShape) continue;
      failures.push(
        `${relative} documents an install command that differs from the create CLI's:\n` +
          `    documented: ${commandShape(command)}\n` +
          `    canonical:  ${canonicalShape}\n` +
          `    Use {{INSTALL_COMMAND}} (site content) or the generated module instead of a copy.`,
      );
    }
  }

  return { command: canonicalCommand, failures };
}

export function renderInstallCommandModule(build: InstallCommandBuild): string {
  // JSON.stringify, not formatJson: the payload is a single string and the
  // module is consumed by direct interpolation (formatJson would wrap it in an
  // object literal).
  return '// Auto-generated by www/tools/generate-install-command.ts (#1414) — do not edit\n' +
    "// Source of truth: packages/create/src/install-command.ts, the create CLI's own\n" +
    '// canonical string. Regenerate with `deno task --cwd www generate:install-command`;\n' +
    '// the file is untracked and rebuilt before test/site:build.\n' +
    `export const installCommand = ${JSON.stringify(build.command)} as const;\n`;
}

if (import.meta.main) {
  const check = Deno.args.includes('--check');
  const build = await buildInstallCommand();
  if (build.failures.length > 0) {
    console.error('install-command gate failed:');
    for (const failure of build.failures) console.error(`- ${failure}`);
    Deno.exit(1);
  }
  const module = renderInstallCommandModule(build);
  if (check) {
    let existing: string;
    try {
      existing = await Deno.readTextFile(join(repoRoot, INSTALL_COMMAND_ARTIFACT));
    } catch {
      console.error(
        `${INSTALL_COMMAND_ARTIFACT} is missing; run deno task --cwd www generate:install-command`,
      );
      Deno.exit(1);
    }
    if (existing !== module) {
      console.error(
        `${INSTALL_COMMAND_ARTIFACT} is stale; run deno task --cwd www generate:install-command`,
      );
      Deno.exit(1);
    }
    console.log(
      `Install-command check passed (${DISPLAY_FILES.length} display files, 1 canonical string).`,
    );
  } else {
    await Deno.writeTextFile(join(repoRoot, INSTALL_COMMAND_ARTIFACT), module);
    console.log(`Wrote the canonical install command to ${INSTALL_COMMAND_ARTIFACT}`);
  }
}
