/**
 * Generate the site data modules required by tests, the site check tools and the
 * site build on a clean clone.
 *
 * One canonical entry for every committed site content module, emitted from
 * the checked-in inputs (verified with a single --check):
 *   www/content/**                      -> _generated-{guide,architecture,blog}-data.ts
 *   CHANGELOG.md                        -> _generated-changelog-archive.ts
 *   docs/release/release-state.json     -> _generated-release-line.ts
 *   www/lib/content-dates.json          -> _generated-content-meta.ts
 *   PAGE_CODE_SOURCES (below)           -> _generated-page-code.ts
 *
 * The remaining modules under www/app/data/ (_generated-api-reference.ts,
 * version.ts) are consumed as ordinary checked-in modules; the API reference
 * has its own `pnpm --filter @openelement/www run generate:api-reference` gate.
 *
 * `--check` regenerates in memory and fails on drift.
 */
import {
  loadCollectionData,
  writeBlogDataModule,
  writeCollectionDataModule,
} from '../lib/content.ts';
import { highlightSiteCode, renderSiteMarkdown } from '../lib/markdown.ts';
import { blogCollection, prepareBlogPosts } from '../lib/blog.ts';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { articleCollections } from '../content-collections.ts';
import { readFile, writeFile } from 'node:fs/promises';
import process from 'node:process';

const siteRoot = fileURLToPath(new URL('../../www/', import.meta.url));

/**
 * The two page-component code blocks (home hero, contributing setup) — the
 * one copy of their source. They live here, not in the JSX, because the
 * highlighted markup is compiled at generation time through the site's ONE
 * highlight pipeline (lib/markdown.ts) and projected into <open-code-block>
 * as trusted HTML; the pages carry only the generated bytes. Editing a
 * snippet means editing here and rerunning generate:content (check:content-data
 * fails on drift).
 */
const PAGE_CODE_SOURCES = {
  homeHeroCode: {
    lang: 'tsx',
    source: `import { element, OpenElement, property } from '@openelement/element'

@element('open-counter', { root: 'shadow-open' })
export class OpenCounter extends OpenElement {
  @property({ reflect: true, attribute: 'count', type: Number })
  count = 0

  render() {
    return (
      <button type="button">Count: {this.count}</button>
    )
  }
}

// SSR: <open-counter count="0"> + DSD shadow root.
// Markup paints and reads with no JavaScript.`,
  },
  contributingSetupCode: {
    lang: 'bash',
    source: `git clone https://github.com/open-element/openelement.git
cd openelement
pnpm install
pnpm test`,
  },
} as const;

const outputs = new Map<string, string>();
for (const name of ['guide', 'architecture'] as const) {
  const options = {
    ...articleCollections[name],
    contentDir: join(siteRoot, articleCollections[name].contentDir),
  };
  // The loader resolves the site's computed placeholders ({{INSTALL_COMMAND}}
  // among them, #1414) before rendering, so the emitted module already carries
  // the create CLI's canonical string.
  const entries = await loadCollectionData(name, options);
  const output = writeCollectionDataModule(name, entries, options);
  outputs.set(join(siteRoot, `app/data/_generated-${name}-data.ts`), output);
}

const blogOptions = { ...blogCollection, contentDir: join(siteRoot, blogCollection.contentDir) };
const blogEntries = await loadCollectionData('blog', blogOptions);
outputs.set(
  join(siteRoot, 'app/data/_generated-blog-data.ts'),
  writeBlogDataModule(prepareBlogPosts(blogEntries)),
);

// Changelog archive, rendered from the repository CHANGELOG.md (a first-party
// file — same trust level as the collections) through the same build-time
// markdown pipeline, so its fences carry identical build-time highlighting.
// The route consumes this module instead of reading the filesystem and
// running marked at render time: a missing CHANGELOG.md now fails the
// generation step itself (fail closed) rather than shipping a fallback page.
const changelogSource = await readFile(join(siteRoot, '../CHANGELOG.md'), 'utf8');
// CHANGELOG.md links are repository-relative so they resolve on GitHub; on
// the built site they would 404 (#1159 link truth), so they are projected
// onto the canonical GitHub tree before rendering.
const changelogMarkdown = changelogSource
  .replace(/^#\s+Changelog\s*\n/, '')
  .replaceAll('](./', '](https://github.com/open-element/openelement/tree/main/');
outputs.set(
  join(siteRoot, 'app/data/_generated-changelog-archive.ts'),
  `// GENERATED by www/tools/generate-site-content-data.ts from the repository
// CHANGELOG.md — do not edit by hand. Regenerate with
// \`pnpm --filter @openelement/www run generate:content\` (part of site:build).

/** Rendered CHANGELOG.md archive: H1 stripped, links projected, fences highlighted. */
export const changelogArchiveHtml: string = ${JSON.stringify(await renderSiteMarkdown(changelogMarkdown))};
`,
);

// The two page-component code blocks, pre-highlighted through the same Shiki
// pipeline as every fence (single highlighter instance, single --shiki-*
// theme; sources live in PAGE_CODE_SOURCES above). The routes project these
// bytes into <open-code-block> as trusted HTML.
outputs.set(
  join(siteRoot, 'app/data/_generated-page-code.ts'),
  `// GENERATED by www/tools/generate-site-content-data.ts from PAGE_CODE_SOURCES
// in that tool — do not edit by hand. Regenerate with
// \`pnpm --filter @openelement/www run generate:content\` (part of site:build).

/** Home hero: the open-counter component example, Shiki-highlighted (tsx). */
export const homeHeroCodeHtml: string = ${JSON.stringify(
    await highlightSiteCode(
      PAGE_CODE_SOURCES.homeHeroCode.source,
      PAGE_CODE_SOURCES.homeHeroCode.lang,
    ),
  )};

/** Contributing setup: the clone/build command sequence, Shiki-highlighted (bash). */
export const contributingSetupCodeHtml: string = ${JSON.stringify(
    await highlightSiteCode(
      PAGE_CODE_SOURCES.contributingSetupCode.source,
      PAGE_CODE_SOURCES.contributingSetupCode.lang,
    ),
  )};
`,
);

// Release-line truth, derived from docs/release/release-state.json (the
// registry-verified source of truth) so site copy about the source line
// flips automatically when the release train publishes — no manual wording
// sweep. Consumed by www/app/data/version.ts.
const releaseState = JSON.parse(
  await readFile(join(siteRoot, '../docs/release/release-state.json'), 'utf8'),
) as {
  sourceVersion: string;
  packages: Array<{ name: string; registry: Record<string, string | undefined> }>;
};
const sourceVersion = releaseState.sourceVersion;
const alphaResolutions = releaseState.packages.map((pkg) => pkg.registry.alpha);
// The source line counts as published only when EVERY package's @alpha
// dist-tag resolves to it — a partial train must still read as unpublished.
const sourceLinePublished = alphaResolutions.every((v) => v === sourceVersion);
const createEntry = releaseState.packages.find((pkg) => pkg.name === '@openelement/create');
const alphaResolvesTo = createEntry?.registry.alpha ?? 'unknown';

// Roadmap publish-state drift guard: app/routes/roadmap.tsx must not
// hand-write an alpha-train publish claim beside
// docs/release/release-state.json — that status is derived in
// www/app/data/version.ts from the same generated truth, so whichever claim
// contradicts the tracked registry state fails here and turns CI red
// (www#check:content-data) instead of shipping a stale roadmap row.
const roadmapSource = await readFile(join(siteRoot, 'app/routes/roadmap.tsx'), 'utf8');
const contradictingClaims = sourceLinePublished
  ? [/repository baseline/iu, /not yet on npm/iu, /仓库基线——尚未发布到 npm/u]
  : [/published to npm under the @alpha dist-tag/iu, /已通过 @alpha dist-tag 发布到 npm/u];
const roadmapDrift = contradictingClaims.filter((claim) => claim.test(roadmapSource));
if (roadmapDrift.length > 0) {
  console.error(
    'roadmap publish-state drift: app/routes/roadmap.tsx hand-writes an alpha-train ' +
      'publish claim that contradicts docs/release/release-state.json; the status ' +
      'must stay derived from www/app/data/version.ts.',
  );
  for (const claim of roadmapDrift) console.error(`  ${claim}`);
  process.exit(1);
}

outputs.set(
  join(siteRoot, 'app/data/_generated-release-line.ts'),
  `// GENERATED by www/tools/generate-site-content-data.ts from
// docs/release/release-state.json — do not edit by hand. Regenerate with
// \`pnpm --filter @openelement/www run generate:content\` (part of site:build).
export const SOURCE_VERSION = '${sourceVersion}';
export const SOURCE_LINE_PUBLISHED = ${sourceLinePublished};
export const ALPHA_RESOLVES_TO = '${alphaResolvesTo}';
`,
);

// Per-article source-freshness stamps, projected from the committed
// manifest (never from Git: the build must run without .git or a network).
const contentDates = JSON.parse(
  await readFile(join(siteRoot, 'lib/content-dates.json'), 'utf8'),
) as { generatedFrom: string; articles: Record<string, { en: string; zh: string }> };
const STAMP = /^(?:\d{4}-\d{2}-\d{2}|uncommitted)$/;
const metaMap: Record<string, { en: string; zh: string }> = {};
for (const slug of Object.keys(contentDates.articles).sort()) {
  const stamps = contentDates.articles[slug];
  if (!STAMP.test(stamps.en) || !STAMP.test(stamps.zh)) {
    throw new Error(`generate-site-content-data: bad date stamps for ${slug}`);
  }
  metaMap[slug] = { en: stamps.en, zh: stamps.zh };
}
outputs.set(
  join(siteRoot, 'app/data/_generated-content-meta.ts'),
  `// Auto-generated by www/tools/generate-site-content-data.ts from lib/content-dates.json - do not edit.

/** Last-commit ISO date per article source, keyed by \`<collection>/<slug>\`. */
export const contentMeta: Record<string, { en: string; zh: string }> = ${JSON.stringify(
    metaMap,
    null,
    2,
  )};
`,
);

if (process.argv.slice(2).includes('--check')) {
  const drifted: string[] = [];
  for (const [path, expected] of outputs) {
    let current = '';
    try {
      current = await readFile(path, 'utf8');
    } catch {
      // Missing file is drift; fall through to the mismatch path.
    }
    if (current !== expected) drifted.push(path);
  }
  if (drifted.length > 0) {
    console.error(
      'site content data drift: regenerate with pnpm --filter @openelement/www run generate:content',
    );
    for (const path of drifted) console.error(`  ${path}`);
    process.exit(1);
  }
  console.log('site content data check passed.');
} else {
  for (const [path, output] of outputs) await writeFile(path, output);
  console.log(`site content data written: ${outputs.size} modules.`);
}
