/**
 * Generate the site data modules required by tests, the site check tools and the
 * site build on a clean clone.
 *
 * One canonical entry for every committed site content module, emitted from
 * the checked-in inputs (verified with a single --check):
 *   www/content/**                      -> _generated-{guide,architecture,blog}-data.ts
 *   docs/release/release-state.json     -> _generated-release-line.ts
 *   www/lib/content-dates.json          -> _generated-content-meta.ts
 *
 * The remaining modules under www/app/data/ (_generated-api-reference.ts,
 * version.ts) are consumed as ordinary checked-in modules; the API reference
 * has its own `deno task --cwd www generate:api-reference` gate.
 *
 * `--check` regenerates in memory and fails on drift.
 */
import {
  loadCollectionData,
  writeBlogDataModule,
  writeCollectionDataModule,
} from '../lib/content.ts';
import { blogCollection, prepareBlogPosts } from '../lib/blog.ts';
import { fromFileUrl, join } from '@std/path';
import { articleCollections } from '../content-collections.ts';

const siteRoot = fromFileUrl(new URL('../../www/', import.meta.url));

const outputs = new Map<string, string>();
for (const name of ['guide', 'architecture'] as const) {
  const options = {
    ...articleCollections[name],
    contentDir: join(siteRoot, articleCollections[name].contentDir),
  };
  // The loader resolves the site's computed placeholders ({{INSTALL_COMMAND}}
  // among them, #1414) before rendering, so the emitted module already carries
  // the create CLI's canonical string.
  const entries = await loadCollectionData(name, options);
  const output = writeCollectionDataModule(name, entries, options);
  outputs.set(join(siteRoot, `app/data/_generated-${name}-data.ts`), output);
}

const blogOptions = { ...blogCollection, contentDir: join(siteRoot, blogCollection.contentDir) };
const blogEntries = await loadCollectionData('blog', blogOptions);
outputs.set(
  join(siteRoot, 'app/data/_generated-blog-data.ts'),
  writeBlogDataModule(prepareBlogPosts(blogEntries)),
);

// Release-line truth, derived from docs/release/release-state.json (the
// registry-verified source of truth) so site copy about the source line
// flips automatically when the release train publishes — no manual wording
// sweep. Consumed by www/app/data/version.ts.
const releaseState = JSON.parse(
  await Deno.readTextFile(join(siteRoot, '../docs/release/release-state.json')),
) as {
  sourceVersion: string;
  packages: Array<{ name: string; registry: Record<string, string | undefined> }>;
};
const sourceVersion = releaseState.sourceVersion;
const alphaResolutions = releaseState.packages.map((pkg) => pkg.registry.alpha);
// The source line counts as published only when EVERY package's @alpha
// dist-tag resolves to it — a partial train must still read as unpublished.
const sourceLinePublished = alphaResolutions.every((v) => v === sourceVersion);
const createEntry = releaseState.packages.find((pkg) => pkg.name === '@openelement/create');
const alphaResolvesTo = createEntry?.registry.alpha ?? 'unknown';

// Roadmap publish-state drift guard: app/routes/roadmap.tsx must not
// hand-write an alpha-train publish claim beside
// docs/release/release-state.json — that status is derived in
// www/app/data/version.ts from the same generated truth, so whichever claim
// contradicts the tracked registry state fails here and turns CI red
// (www#check:content-data) instead of shipping a stale roadmap row.
const roadmapSource = await Deno.readTextFile(join(siteRoot, 'app/routes/roadmap.tsx'));
const contradictingClaims = sourceLinePublished
  ? [/repository baseline/iu, /not yet on npm/iu, /仓库基线——尚未发布到 npm/u]
  : [
    /published to npm under the @alpha dist-tag/iu,
    /已通过 @alpha dist-tag 发布到 npm/u,
  ];
const roadmapDrift = contradictingClaims.filter((claim) => claim.test(roadmapSource));
if (roadmapDrift.length > 0) {
  console.error(
    'roadmap publish-state drift: app/routes/roadmap.tsx hand-writes an alpha-train ' +
      'publish claim that contradicts docs/release/release-state.json; the status ' +
      'must stay derived from www/app/data/version.ts.',
  );
  for (const claim of roadmapDrift) console.error(`  ${claim}`);
  Deno.exit(1);
}

outputs.set(
  join(siteRoot, 'app/data/_generated-release-line.ts'),
  `// GENERATED by www/tools/generate-site-content-data.ts from
// docs/release/release-state.json — do not edit by hand. Regenerate with
// \`deno task --cwd www generate:content\` (part of site:build).
export const SOURCE_VERSION = '${sourceVersion}';
export const SOURCE_LINE_PUBLISHED = ${sourceLinePublished};
export const ALPHA_RESOLVES_TO = '${alphaResolvesTo}';
`,
);

// Per-article source-freshness stamps, projected from the committed
// manifest (never from Git: the build must run without .git or a network).
const contentDates = JSON.parse(
  await Deno.readTextFile(join(siteRoot, 'lib/content-dates.json')),
) as { generatedFrom: string; articles: Record<string, { en: string; zh: string }> };
const STAMP = /^(?:\d{4}-\d{2}-\d{2}|uncommitted)$/;
const metaMap: Record<string, { en: string; zh: string }> = {};
for (const slug of Object.keys(contentDates.articles).sort()) {
  const stamps = contentDates.articles[slug];
  if (!STAMP.test(stamps.en) || !STAMP.test(stamps.zh)) {
    throw new Error(`generate-site-content-data: bad date stamps for ${slug}`);
  }
  metaMap[slug] = { en: stamps.en, zh: stamps.zh };
}
outputs.set(
  join(siteRoot, 'app/data/_generated-content-meta.ts'),
  `// Auto-generated by www/tools/generate-site-content-data.ts from lib/content-dates.json - do not edit.

/** Last-commit ISO date per article source, keyed by \`<collection>/<slug>\`. */
export const contentMeta: Record<string, { en: string; zh: string }> = ${
    JSON.stringify(metaMap, null, 2)
  };
`,
);

if (Deno.args.includes('--check')) {
  const drifted: string[] = [];
  for (const [path, expected] of outputs) {
    let current = '';
    try {
      current = await Deno.readTextFile(path);
    } catch {
      // Missing file is drift; fall through to the mismatch path.
    }
    if (current !== expected) drifted.push(path);
  }
  if (drifted.length > 0) {
    console.error(
      'site content data drift: regenerate with deno task --cwd www generate:content',
    );
    for (const path of drifted) console.error(`  ${path}`);
    Deno.exit(1);
  }
  console.log('site content data check passed.');
} else {
  for (const [path, output] of outputs) await Deno.writeTextFile(path, output);
  console.log(`site content data written: ${outputs.size} modules.`);
}
