/**
 * Generate the article route modules, their element bindings and the article
 * route table from the content collections.
 *
 * Adding one article used to mean three hand-written artifacts: a route module,
 * a component binding, and a row in the article test table. The owner ruling is
 * that the Site follows its generators, so this generator derives all three from
 * the single source of truth — `www/content/docs/<collection>/<slug>[.<locale>].md`
 * and its frontmatter — and is their only writer:
 *
 *   app/routes/<collection>/<routeFile>.tsx
 *     the page module: `definePage(Binding, { head, props })` with the
 *     collection/slug literal the model projects. `index.tsx` when the slug is
 *     the collection name (the collection overview URL, e.g. `/architecture`).
 *   app/components/article-routes/<collection>-<slug>.tsx
 *     the thin element binding the route module renders.
 *   app/data/_generated-article-routes.ts
 *     the route table tests (and any future consumer) read instead of a hand
 *     list: collection, slug, file names, element tag, class name, nav order.
 *
 * The emitted route modules and bindings are byte-identical to the hand-written
 * ones they replaced except for the added header line and one class name
 * (`architecture-dsd`'s `DsdGuidePage` is now the derived `DsdPage`), so the
 * sitemap's route scan (tools/lib/site-route-scan.ts) enumerates exactly the
 * same public routes and the built site is unchanged.
 *
 * Boundaries, all fail-closed in both write and --check mode:
 *
 *   - only the article collections in content-collections.ts are managed. The
 *     non-article surface (`/`, /404, /blog, /docs, /reference, /errors,
 *     /roadmap, /changelog, /contributing, /index/…) lives outside the managed
 *     directories and is never read, written or deleted;
 *   - inside a managed directory, an unexpected file that does not carry this
 *     generator's header is an error, never a silent delete: ownership is
 *     proven by the header, and a hand-written file is never guessed at;
 *   - a generated file whose content file disappeared is stale: deleted in
 *     write mode, drift in --check mode;
 *   - a collection entry without an English source, two content files resolving
 *     to the same route *or to the same generated file* (a collection overview
 *     article and a separate `index` article both own `index.tsx`), a slug that
 *     cannot become a module name, or a non-numeric `order` are errors.
 *
 * `--check` regenerates every artifact in memory and requires byte equality
 * with the files on disk (plus an empty stale/unknown set). The pure rules are
 * exported and pinned by generate-site-article-routes.test.ts; the entry point
 * below only runs as the main module, so importing it never writes.
 */
import { walk } from '@std/fs/walk';
import { dirname, fromFileUrl, join, relative } from '@std/path';
import { loadCollectionData } from '../lib/content.ts';
import { articleCollections } from '../content-collections.ts';

type ArticleCollection = keyof typeof articleCollections;

const collectionNames = Object.keys(articleCollections) as ArticleCollection[];

const siteRoot = fromFileUrl(new URL('../../www/', import.meta.url));
const routesDir = 'app/routes';
const componentsDir = 'app/components/article-routes';
const tablePath = 'app/data/_generated-article-routes.ts';

/** Ownership marker: every file this generator writes starts with this line. */
const generatedHeader = '// Auto-generated by www/tools/generate-site-article-routes.ts';

/**
 * Binding class-name prefix per collection. The name is only a greppable symbol
 * for these internal bindings (nothing imports it by name outside the route
 * module the generator also writes); the prefixes reproduce every class name the
 * hand-written bindings used, so the migration renames exactly one class
 * (`architecture-dsd`'s `DsdGuidePage` becomes `DsdPage`).
 */
const classPrefix: Readonly<Record<ArticleCollection, string>> = {
  guide: 'Guide',
  architecture: '',
};

/**
 * URL slug shape that can also become a module name, tag and file name: every
 * hyphen-separated segment non-empty, so a leading/trailing/double hyphen
 * (which would still be a live URL) cannot silently produce a degenerate file
 * name, element tag or class name.
 */
const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

export interface ArticleRoute {
  collection: ArticleCollection;
  slug: string;
  /** File name inside app/routes/<collection>/. */
  routeFile: string;
  /** File name inside app/components/article-routes/. */
  componentFile: string;
  /** Custom element tag the binding registers. */
  elementTag: string;
  /** Default-exported binding class name. */
  className: string;
  /** Frontmatter nav order (English source). */
  order: number;
}

/** `web-component-admission` -> `WebComponentAdmission`; `i18n` -> `I18n`. */
export function pascalCase(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/** The frontmatter fields this generator reads from a collection entry. */
export interface RouteSourceEntry {
  slug: string;
  locale?: string;
  frontmatter: Record<string, unknown>;
}

/**
 * Pure route-set derivation for one collection: one route per English source,
 * with every fail-closed rule applied (see the module doc). Exported so the
 * rules are pinned by tests instead of only exercised through a real run.
 */
export function routeSetFor(
  collection: ArticleCollection,
  entries: readonly RouteSourceEntry[],
): ArticleRoute[] {
  const bySlug = new Map<string, { locales: Set<string>; order: number }>();
  for (const entry of entries) {
    const locale = entry.locale ?? 'en';
    if (!slugPattern.test(entry.slug)) {
      throw new Error(
        `[article-routes] content/docs/${collection}/${entry.slug}: slug must match ${slugPattern} ` +
          'to become a route module name',
      );
    }
    const order = Number(entry.frontmatter.order);
    if (!Number.isFinite(order)) {
      throw new Error(
        `[article-routes] content/docs/${collection}/${entry.slug}: frontmatter.order must be a number`,
      );
    }
    const known = bySlug.get(entry.slug);
    if (known) {
      if (known.locales.has(locale)) {
        throw new Error(
          `[article-routes] content/docs/${collection}: two content files resolve to ` +
            `${entry.slug} (${locale})`,
        );
      }
      known.locales.add(locale);
      continue;
    }
    bySlug.set(entry.slug, { locales: new Set([locale]), order });
  }
  const routes: ArticleRoute[] = [];
  for (const [slug, record] of bySlug) {
    if (!record.locales.has('en')) {
      throw new Error(
        `[article-routes] content/docs/${collection}/${slug}: no English source (X.md) — every ` +
          `route projects an English original; found only ${[...record.locales].join(', ')}`,
      );
    }
    routes.push({
      collection,
      slug,
      // The collection overview article owns the collection root URL.
      routeFile: slug === collection ? 'index.tsx' : `${slug}.tsx`,
      componentFile: `${collection}-${slug}.tsx`,
      elementTag: `${collection}-${slug}`,
      className: `${classPrefix[collection]}${pascalCase(slug)}Page`,
      order: record.order,
    });
  }
  return routes;
}

/**
 * The route set: content-driven, one entry per English source. Markdown
 * rendering is skipped (only frontmatter and locale-suffixed slugs are read),
 * like the nav generator does.
 */
async function collectRoutes(): Promise<ArticleRoute[]> {
  const routes: ArticleRoute[] = [];
  for (const collection of collectionNames) {
    const options = articleCollections[collection];
    const entries = await loadCollectionData(collection, {
      ...options,
      contentDir: join(siteRoot, options.contentDir),
      markdown: (content: string) => content,
    });
    routes.push(...routeSetFor(collection, entries));
  }
  return routes.sort((a, b) =>
    collectionNames.indexOf(a.collection) - collectionNames.indexOf(b.collection) ||
    a.order - b.order ||
    (a.slug < b.slug ? -1 : 1)
  );
}

export function renderRouteModule(route: ArticleRoute): string {
  const source = `www/content/docs/${route.collection}/${route.slug}.md`;
  return `${generatedHeader} from ${source} - do not edit.
import { definePage } from '@openelement/router';
import ${route.className} from '../../components/article-routes/${route.componentFile}';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(${route.className}, {
  head: ({ locale }) => articlePageHead('${route.collection}', '${route.slug}', locale),
  props({ locale }) {
    return { model: projectArticlePage('${route.collection}', '${route.slug}', locale) };
  },
});
`;
}

export function renderComponent(route: ArticleRoute): string {
  const source = `www/content/docs/${route.collection}/${route.slug}.md`;
  return `${generatedHeader} for ${source} - do not edit.
import { element, OpenElement, property } from '@openelement/element';
import '../../site-ui/open-article-view.tsx';
import type { ArticlePageModel } from '../../site-ui/article-page-model.ts';

@element('${route.elementTag}')
export default class ${route.className} extends OpenElement {
  @property({ reflect: false, attribute: false })
  model: ArticlePageModel = {
    notFoundClass: 'container',
    articleClass: 'is-hidden',
    slug: '',
    notFoundMessage: '',
    metadata: { breadcrumb: '', title: '', lede: '' },
    navigation: {},
    railItems: [],
    articleHtml: '',
  };

  // Same base-field redeclaration as open-layout: the compiled @property
  // shadows OpenElementConfiguration.locale (SSR injection or the \`locale\`
  // attribute); tsc's \`override\` demand is rejected by the compiled grammar.
  @property({ reflect: false })
  // @ts-expect-error compiled @property shadows the optional base field
  locale = 'en';

  render() {
    return <open-article-view model={this.model} locale={this.locale}></open-article-view>;
  }
}
`;
}

function renderTable(routes: ArticleRoute[]): string {
  const collectionUnion = collectionNames.map((name) => JSON.stringify(name)).join(' | ');
  return `${generatedHeader} from the article content collections - do not edit.
/**
 * One row per article route, derived from www/content/docs/<collection>/*.md
 * (the English original of each pair). Wire the site to an article by adding
 * content, then run \`deno task --cwd tools/repo generate:all\`: the route module,
 * the element binding and this table are all emitted from the same source.
 */
export interface GeneratedArticleRoute {
  collection: ${collectionUnion};
  slug: string;
  /** File name inside app/routes/<collection>/. */
  routeFile: string;
  /** File name inside app/components/article-routes/. */
  componentFile: string;
  /** Custom element tag the binding registers. */
  elementTag: string;
  /** Default-exported binding class name. */
  className: string;
  /** Frontmatter nav order (English source). */
  order: number;
}

export const articleRoutes: GeneratedArticleRoute[] = ${JSON.stringify(routes, null, 2)};
`;
}

interface PlannedFile {
  /** Repository-relative path (posix separators). */
  rel: string;
  content: string;
}

/**
 * Every artifact this generator owns, derived solely from the route set.
 *
 * Fail-closed on output collisions: two routes that compute the same output
 * path (a collection overview and a separate `index` article both map to
 * `app/routes/<collection>/index.tsx`) would otherwise silently drop one
 * route and leave its binding orphaned. Both claiming content files and the
 * contested path are named instead.
 */
export function planFiles(routes: ArticleRoute[]): PlannedFile[] {
  const files: PlannedFile[] = [];
  /** Output path -> the content source that already claimed it. */
  const claimed = new Map<string, string>();
  const claim = (rel: string, content: string, source: string): void => {
    const owner = claimed.get(rel);
    if (owner !== undefined) {
      throw new Error(
        `[article-routes] two content files resolve to the same generated file ${rel}: ` +
          `${owner} and ${source}. Rename one of them. (A slug equal to the collection name owns ` +
          `${routesDir}/<collection>/index.tsx, so a separate 'index' article cannot also map ` +
          'there.)',
      );
    }
    claimed.set(rel, source);
    files.push({ rel, content });
  };
  for (const route of routes) {
    const source = `content/docs/${route.collection}/${route.slug}.md`;
    claim(`${routesDir}/${route.collection}/${route.routeFile}`, renderRouteModule(route), source);
    claim(`${componentsDir}/${route.componentFile}`, renderComponent(route), source);
  }
  claim(tablePath, renderTable(routes), 'the generated route table');
  return files;
}

/** Directories this generator owns, mapped to the walk depth that covers them. */
export function managedDirectories(): Map<string, number> {
  const dirs = new Map<string, number>();
  // A collection's route directory is managed even when its content is empty:
  // that is exactly when its last generated route module must be cleaned up.
  for (const collection of collectionNames) dirs.set(`${routesDir}/${collection}`, Infinity);
  dirs.set(componentsDir, 1);
  return dirs;
}

async function readIfPresent(path: string): Promise<string | undefined> {
  try {
    return await Deno.readTextFile(path);
  } catch {
    return undefined;
  }
}

/**
 * Write or check every planned artifact. Only runs as the entry module: the
 * file also exports its pure rules for tests, and importing them must never
 * write to the tree.
 */
async function main(): Promise<void> {
  const routes = await collectRoutes();
  const expected = new Map(planFiles(routes).map((file) => [file.rel, file.content]));

  /** Generated files already on disk for routes that no longer have content. */
  const stale: string[] = [];
  /** Files in a managed directory that neither this generator nor content owns. */
  const unexpected: string[] = [];

  for (const [dir, maxDepth] of managedDirectories()) {
    let dirExists = true;
    try {
      if (!(await Deno.stat(join(siteRoot, dir))).isDirectory) dirExists = false;
    } catch {
      dirExists = false;
    }
    if (!dirExists) continue;
    for await (
      const entry of walk(join(siteRoot, dir), {
        includeDirs: false,
        maxDepth,
        followSymlinks: false,
      })
    ) {
      // Editor/OS droppings (.DS_Store) are not route sources; everything else
      // is held to the ownership rule below.
      if (entry.name.startsWith('.')) continue;
      const rel = relative(siteRoot, entry.path);
      if (expected.has(rel)) continue;
      const source = entry.isSymlink ? '' : await readIfPresent(entry.path) ?? '';
      if (!entry.isSymlink && source.startsWith(generatedHeader)) stale.push(rel);
      else unexpected.push(rel);
    }
  }

  if (unexpected.length > 0) {
    console.error(
      `article routes: ${unexpected.length} file(s) in a managed directory are neither ` +
        'content-backed nor generated by this generator (a symlinked route file counts as ' +
        'unowned: the sitemap scanner skips symlinks):',
    );
    for (const rel of [...unexpected].sort()) console.error(`  ${rel}`);
    console.error(
      'the generator owns app/routes/<collection>/ and app/components/article-routes/; add the ' +
        'matching content (www/content/docs/<collection>/<slug>.md) or move the file out of the ' +
        'managed directory — it will not be deleted or overwritten.',
    );
    Deno.exit(1);
  }

  const drift: string[] = [];
  for (const [rel, content] of expected) {
    const current = await readIfPresent(join(siteRoot, rel));
    if (current !== content) drift.push(rel);
  }

  const check = Deno.args.includes('--check');
  if (check) {
    if (drift.length > 0 || stale.length > 0) {
      console.error('article routes drift:');
      for (const rel of [...drift].sort()) console.error(`  differs from content: ${rel}`);
      for (const rel of [...stale].sort()) console.error(`  stale (content gone): ${rel}`);
      console.error('regenerate with deno task --cwd www generate:article-routes');
      Deno.exit(1);
    }
    console.log(`article routes check passed (${routes.length} article(s)).`);
  } else {
    for (const [rel, content] of expected) {
      const path = join(siteRoot, rel);
      await Deno.mkdir(dirname(path), { recursive: true });
      await Deno.writeTextFile(path, content);
    }
    for (const rel of stale) await Deno.remove(join(siteRoot, rel));
    console.log(
      `article routes written: ${routes.length} article(s) -> ${routes.length} route module(s), ` +
        `${routes.length} binding(s), table${
          stale.length > 0 ? `; ${stale.length} stale file(s) removed` : ''
        }.`,
    );
  }
}

if (import.meta.main) await main();
