// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/architecture/comparison.md - do not edit.
import { definePage } from '@openelement/router';
import ComparisonPage from '../../components/article-routes/architecture-comparison.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(ComparisonPage, {
  head: ({ locale }) => articlePageHead('architecture', 'comparison', locale),
  props({ locale }) {
    return { model: projectArticlePage('architecture', 'comparison', locale) };
  },
});
