// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/architecture/dsd.md - do not edit.
import { definePage } from '@openelement/router';
import DsdPage from '../../components/article-routes/architecture-dsd.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(DsdPage, {
  head: ({ locale }) => articlePageHead('architecture', 'dsd', locale),
  props({ locale }) {
    return { model: projectArticlePage('architecture', 'dsd', locale) };
  },
});
