// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/architecture/architecture.md - do not edit.
import { definePage } from '@openelement/router';
import ArchitecturePage from '../../components/article-routes/architecture-architecture.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(ArchitecturePage, {
  head: ({ locale }) => articlePageHead('architecture', 'architecture', locale),
  props({ locale }) {
    return { model: projectArticlePage('architecture', 'architecture', locale) };
  },
});
