// Auto-generated by www/tools/generate-site-article-routes.ts from www/content/docs/architecture/islands.md - do not edit.
import { definePage } from '@openelement/router';
import IslandsPage from '../../components/article-routes/architecture-islands.tsx';
import { articlePageHead, projectArticlePage } from '../../site-ui/article-page-model.ts';

export default definePage(IslandsPage, {
  head: ({ locale }) => articlePageHead('architecture', 'islands', locale),
  props({ locale }) {
    return { model: projectArticlePage('architecture', 'islands', locale) };
  },
});
