import { assert, assertEquals, assertExists, assertStringIncludes } from '@std/assert';
import { loadCollectionData } from '../lib/content.ts';
import { fromFileUrl } from '@std/path';
import { articleCollections } from '../content-collections.ts';
import { projectArticlePage } from '../app/site-ui/article-page-model.ts';
// The route table is generated from the same content this file loads
// (www/tools/generate-site-article-routes.ts, run by `generate:all`), so the
// tests below double as its staleness gate: the table is compared against the
// content files and against the managed route directories on disk.
import { articleRoutes } from '../app/data/_generated-article-routes.ts';

type ArticleCollection = keyof typeof articleCollections;
type ArticleContentPage = {
  slug: string;
  locale?: string;
  frontmatter: {
    title: string;
    lede?: string;
    order: number;
    locale: string;
    section: string;
    navLabel?: string;
  };
  content: string;
  html: string;
};
const siteRoot = fromFileUrl(new URL('../', import.meta.url));
const loadContentPages = (collection: ArticleCollection) =>
  loadCollectionData(collection, {
    ...articleCollections[collection],
    contentDir: `${siteRoot}/${articleCollections[collection].contentDir}`,
  }) as Promise<ArticleContentPage[]>;
const collections = Object.keys(articleCollections) as ArticleCollection[];
const tableGenerator = 'www/tools/generate-site-article-routes.ts';

// The content routes share the site-ui article shell: each route module is a
// thin binding — a content slug — and the nav contract (section / order /
// navLabel) lives in the article frontmatter
// (www/content/docs/<collection>/<slug>[.<locale>].md), the single source of
// truth that www/tools/generate-site-article-routes.ts projects (#1087,
// ADR-0136). Adding an article means adding content and running `generate:all`;
// no hand-written route module, binding or table row remains.
for (const route of articleRoutes) {
  const { collection, slug, className, componentFile, elementTag, routeFile } = route;
  Deno.test(`${collection}/${slug} is a thin article shell`, async () => {
    const routeSource = await Deno.readTextFile(
      new URL(`../app/routes/${collection}/${routeFile}`, import.meta.url),
    );
    const adapterSource = await Deno.readTextFile(
      new URL(`../app/components/article-routes/${componentFile}`, import.meta.url),
    );
    assertStringIncludes(routeSource, 'export default definePage(');
    assertStringIncludes(
      routeSource,
      `projectArticlePage('${collection}', '${slug}', locale)`,
    );
    assert(
      !routeSource.includes('export const meta'),
      `${collection}/${slug} must not duplicate nav metadata; declare it in the frontmatter`,
    );
    assertStringIncludes(adapterSource, `@element('${elementTag}')`);
    assertStringIncludes(adapterSource, `class ${className} extends OpenElement`);
    assertStringIncludes(
      adapterSource,
      '<open-article-view model={this.model} locale={this.locale}>',
    );
    // The generated header is what proves ownership to the generator (its
    // "--check" and its stale cleanup both key off it), and it names the
    // content file each artifact is derived from.
    const header = `// Auto-generated by ${tableGenerator}`;
    const sourcePath = `www/content/docs/${collection}/${slug}.md`;
    assert(
      routeSource.startsWith(header) && routeSource.split('\n')[0].includes(sourcePath),
      `${collection}/${slug}: ${routeFile} must be generator output naming ${sourcePath}`,
    );
    assert(
      adapterSource.startsWith(header) && adapterSource.split('\n')[0].includes(sourcePath),
      `${collection}/${slug}: ${componentFile} must be generator output naming ${sourcePath}`,
    );

    const model = projectArticlePage(collection, slug, 'en');
    assertEquals(model.slug, slug);
    assert(model.metadata.title.length > 0, `${collection}/${slug} must project article data`);
    assertStringIncludes(
      model.articleHtml,
      '<h2',
      `${collection}/${slug} must project compiled article HTML`,
    );
  });
}

// Ownership: the generated table, the content collections and the managed route
// directories must agree. A hand-added route module (no content) or a stale
// table row fails here, not only in the generator's own gate.
Deno.test('managed article directories hold exactly the generated routes', async () => {
  assert(articleRoutes.length > 0, 'the generated article route table is empty');
  for (const collection of collections) {
    const listed = articleRoutes
      .filter((route) => route.collection === collection)
      .map((route) => route.routeFile)
      .sort();
    const onDisk: string[] = [];
    for await (
      const entry of Deno.readDir(new URL(`../app/routes/${collection}/`, import.meta.url))
    ) {
      if (entry.isFile && entry.name.endsWith('.tsx')) onDisk.push(entry.name);
    }
    assertEquals(
      onDisk.sort(),
      listed,
      `app/routes/${collection}/ must hold exactly the routes the content emits`,
    );
    const bindings: string[] = [];
    for await (
      const entry of Deno.readDir(new URL('../app/components/article-routes/', import.meta.url))
    ) {
      if (entry.isFile && entry.name.startsWith(`${collection}-`)) bindings.push(entry.name);
    }
    assertEquals(
      bindings.sort(),
      articleRoutes.filter((route) => route.collection === collection)
        .map((route) => route.componentFile).sort(),
      'app/components/article-routes/ must hold exactly the generated bindings',
    );
  }
});

Deno.test('the article route table is generated, never hand-maintained', async () => {
  const source = await Deno.readTextFile(
    new URL('../app/data/_generated-article-routes.ts', import.meta.url),
  );
  assertStringIncludes(
    source.split('\n')[0],
    `Auto-generated by ${tableGenerator}`,
    'the route table is a generated artifact; hand-maintaining it re-introduces the wiring this generator deleted',
  );
});

// Content-level assertions run against the real Markdown via the pipeline's
// pure loader — no generated-artifact dependency.
Deno.test('content covers every route in both locales', async () => {
  for (const collection of collections) {
    const pages = await loadContentPages(collection);
    for (
      const { slug, order } of articleRoutes.filter((route) => route.collection === collection)
    ) {
      for (const locale of ['en', 'zh'] as const) {
        const page = pages.find((p) => p.slug === slug && p.locale === locale);
        assertExists(page, `content/${collection} missing ${slug} (${locale})`);
        assertEquals(
          page.frontmatter.order,
          order,
          `${collection}/${slug} (${locale}) order mismatch`,
        );
        assert(
          page.frontmatter.title.length > 0,
          `${collection}/${slug} (${locale}) title must not be empty`,
        );
        assert(
          typeof page.frontmatter.section === 'string' && page.frontmatter.section.length > 0,
          `${collection}/${slug} (${locale}) must declare a nav section`,
        );
        assertStringIncludes(
          page.html,
          '<h2',
          `${collection}/${slug} (${locale}) must have article sections`,
        );
        assert(
          !page.html.includes('open-card'),
          `${collection}/${slug} (${locale}) must not contain cards`,
        );
      }
    }
  }
});

// The other direction: a content file the table has not caught up with. The
// table is generated, so this can only fail when it is stale — the failure mode
// a generated artifact consumed by tests otherwise hides.
Deno.test('content has no route the generated table misses', async () => {
  for (const collection of collections) {
    const pages = await loadContentPages(collection);
    const fromContent = [
      ...new Set(
        pages.filter((page) => (page.locale ?? 'en') === 'en').map((page) => page.slug),
      ),
    ].sort();
    const fromTable = articleRoutes
      .filter((route) => route.collection === collection)
      .map((route) => route.slug)
      .sort();
    assertEquals(
      fromContent,
      fromTable,
      `regenerate with \`deno task --cwd www generate:article-routes\` (${collection})`,
    );
  }
});

Deno.test('frontmatter orders are unique within each collection locale', async () => {
  for (const collection of collections) {
    const pages = await loadContentPages(collection);
    for (const locale of ['en', 'zh'] as const) {
      const orders = pages.filter((p) => p.locale === locale).map((p) => p.frontmatter.order);
      assertEquals(
        new Set(orders).size,
        orders.length,
        `duplicate orders in ${collection}/${locale}`,
      );
    }
  }
});

Deno.test('getting-started leads with copyable commands', async () => {
  const pages = await loadContentPages('guide');
  const en = pages.find((p) => p.slug === 'getting-started' && p.locale === 'en');
  assertExists(en);
  // The page's primary job: a fenced, copyable install command — not prose.
  assertStringIncludes(en.html, '<pre><code class="language-bash">');
  assertStringIncludes(en.html, 'npm:@openelement/create');
});

// The security page deep-links the configuration anchor; the configuration
// article must produce a heading whose generated id is middleware-use.
Deno.test('configuration keeps the middleware-use anchor target', async () => {
  const pages = await loadContentPages('guide');
  const en = pages.find((p) => p.slug === 'configuration' && p.locale === 'en');
  const security = pages.find((p) => p.slug === 'security' && p.locale === 'en');
  assertExists(en);
  assertExists(security);
  assertStringIncludes(en.html, '<h2>middleware.use</h2>');
  assertStringIncludes(security.html, '/guide/configuration#middleware-use');
});

Deno.test('content collection loading succeeds for all collections', async () => {
  const count = (await Promise.all(collections.map(loadContentPages)))
    .reduce((total, pages) => total + pages.length, 0);
  assertEquals(count, articleRoutes.length * 2, 'every route needs en + zh content');
});
