import { expect, test } from 'vitest';
import { loadCollectionData } from '../lib/content.ts';
import { fileURLToPath } from 'node:url';
import { articleCollections } from '../content-collections.ts';
import { projectArticlePage } from '../app/site-ui/article-page-model.ts';
// The route table is generated from the same content this file loads
// (www/tools/generate-site-article-routes.ts, run by `generate:all`), so the
// tests below double as its staleness gate: the table is compared against the
// content files and against the managed route directories on disk.
import { articleRoutes } from '../app/data/_generated-article-routes.ts';
import { readdir, readFile } from 'node:fs/promises';

type ArticleCollection = keyof typeof articleCollections;
type ArticleContentPage = {
  slug: string;
  locale?: string;
  frontmatter: {
    title: string;
    lede?: string;
    order: number;
    locale: string;
    section: string;
    navLabel?: string;
  };
  content: string;
  html: string;
};
const siteRoot = fileURLToPath(new URL('../', import.meta.url));
const loadContentPages = (collection: ArticleCollection) =>
  loadCollectionData(collection, {
    ...articleCollections[collection],
    contentDir: `${siteRoot}/${articleCollections[collection].contentDir}`,
  }) as Promise<ArticleContentPage[]>;
const collections = Object.keys(articleCollections) as ArticleCollection[];
const tableGenerator = 'www/tools/generate-site-article-routes.ts';

// The content routes share the site-ui article shell: each route module is a
// thin binding — a content slug — and the nav contract (section / order /
// navLabel) lives in the article frontmatter
// (www/content/docs/<collection>/<slug>[.<locale>].md), the single source of
// truth that www/tools/generate-site-article-routes.ts projects (#1087,
// ADR-0136). Adding an article means adding content and running `generate:all`;
// no hand-written route module, binding or table row remains.
for (const route of articleRoutes) {
  const { collection, slug, className, componentFile, elementTag, routeFile } = route;
  test(`${collection}/${slug} is a thin article shell`, async () => {
    const routeSource = await readFile(
      new URL(`../app/routes/${collection}/${routeFile}`, import.meta.url),
      'utf8',
    );
    const adapterSource = await readFile(
      new URL(`../app/components/article-routes/${componentFile}`, import.meta.url),
      'utf8',
    );
    expect(routeSource).toContain('export default definePage(');
    expect(routeSource).toContain(`projectArticlePage('${collection}', '${slug}', locale)`);
    expect(
      !routeSource.includes('export const meta'),
      `${collection}/${slug} must not duplicate nav metadata; declare it in the frontmatter`,
    ).toBeTruthy();
    expect(adapterSource).toContain(`@element('${elementTag}')`);
    expect(adapterSource).toContain(`class ${className} extends OpenElement`);
    expect(adapterSource).toContain('<open-article-view model={this.model} locale={this.locale}>');
    // The generated header is what proves ownership to the generator (its
    // "--check" and its stale cleanup both key off it), and it names the
    // content file each artifact is derived from.
    const header = `// Auto-generated by ${tableGenerator}`;
    const sourcePath = `www/content/docs/${collection}/${slug}.md`;
    expect(
      routeSource.startsWith(header) && routeSource.split('\n')[0].includes(sourcePath),
      `${collection}/${slug}: ${routeFile} must be generator output naming ${sourcePath}`,
    ).toBeTruthy();
    expect(
      adapterSource.startsWith(header) && adapterSource.split('\n')[0].includes(sourcePath),
      `${collection}/${slug}: ${componentFile} must be generator output naming ${sourcePath}`,
    ).toBeTruthy();

    const model = projectArticlePage(collection, slug, 'en');
    expect(model.slug).toEqual(slug);
    expect(
      model.metadata.title.length > 0,
      `${collection}/${slug} must project article data`,
    ).toBeTruthy();
    expect(model.articleHtml, `${collection}/${slug} must project compiled article HTML`).toContain(
      '<h2',
    );
  });
}

// Ownership: the generated table, the content collections and the managed route
// directories must agree. A hand-added route module (no content) or a stale
// table row fails here, not only in the generator's own gate.
test('managed article directories hold exactly the generated routes', async () => {
  expect(articleRoutes.length > 0, 'the generated article route table is empty').toBeTruthy();
  for (const collection of collections) {
    const listed = articleRoutes
      .filter((route) => route.collection === collection)
      .map((route) => route.routeFile)
      .sort();
    const onDisk: string[] = [];
    for (const entry of await readdir(new URL(`../app/routes/${collection}/`, import.meta.url), {
      withFileTypes: true,
    })) {
      if (entry.isFile() && entry.name.endsWith('.tsx')) onDisk.push(entry.name);
    }
    expect(
      onDisk.sort(),
      `app/routes/${collection}/ must hold exactly the routes the content emits`,
    ).toEqual(listed);
    const bindings: string[] = [];
    for (const entry of await readdir(
      new URL('../app/components/article-routes/', import.meta.url),
      {
        withFileTypes: true,
      },
    )) {
      if (entry.isFile() && entry.name.startsWith(`${collection}-`)) bindings.push(entry.name);
    }
    expect(
      bindings.sort(),
      'app/components/article-routes/ must hold exactly the generated bindings',
    ).toEqual(
      articleRoutes
        .filter((route) => route.collection === collection)
        .map((route) => route.componentFile)
        .sort(),
    );
  }
});

test('the article route table is generated, never hand-maintained', async () => {
  const source = await readFile(
    new URL('../app/data/_generated-article-routes.ts', import.meta.url),
    'utf8',
  );
  expect(
    source.split('\n')[0],
    'the route table is a generated artifact; hand-maintaining it re-introduces the wiring this generator deleted',
  ).toContain(`Auto-generated by ${tableGenerator}`);
});

// Content-level assertions run against the real Markdown via the pipeline's
// pure loader — no generated-artifact dependency.
test('content covers every route in both locales', async () => {
  for (const collection of collections) {
    const pages = await loadContentPages(collection);
    for (const { slug, order } of articleRoutes.filter(
      (route) => route.collection === collection,
    )) {
      for (const locale of ['en', 'zh'] as const) {
        const page = pages.find((p) => p.slug === slug && p.locale === locale);
        expect(page, `content/${collection} missing ${slug} (${locale})`).toEqual(
          expect.anything(),
        );
        expect(page.frontmatter.order, `${collection}/${slug} (${locale}) order mismatch`).toEqual(
          order,
        );
        expect(
          page.frontmatter.title.length > 0,
          `${collection}/${slug} (${locale}) title must not be empty`,
        ).toBeTruthy();
        expect(
          typeof page.frontmatter.section === 'string' && page.frontmatter.section.length > 0,
          `${collection}/${slug} (${locale}) must declare a nav section`,
        ).toBeTruthy();
        expect(page.html, `${collection}/${slug} (${locale}) must have article sections`).toContain(
          '<h2',
        );
        expect(
          !page.html.includes('open-card'),
          `${collection}/${slug} (${locale}) must not contain cards`,
        ).toBeTruthy();
      }
    }
  }
});

// The other direction: a content file the table has not caught up with. The
// table is generated, so this can only fail when it is stale — the failure mode
// a generated artifact consumed by tests otherwise hides.
test('content has no route the generated table misses', async () => {
  for (const collection of collections) {
    const pages = await loadContentPages(collection);
    const fromContent = [
      ...new Set(pages.filter((page) => (page.locale ?? 'en') === 'en').map((page) => page.slug)),
    ].sort();
    const fromTable = articleRoutes
      .filter((route) => route.collection === collection)
      .map((route) => route.slug)
      .sort();
    expect(
      fromContent,
      `regenerate with \`pnpm --dir www run generate:article-routes\` (${collection})`,
    ).toEqual(fromTable);
  }
});

test('frontmatter orders are unique within each collection locale', async () => {
  for (const collection of collections) {
    const pages = await loadContentPages(collection);
    for (const locale of ['en', 'zh'] as const) {
      const orders = pages.filter((p) => p.locale === locale).map((p) => p.frontmatter.order);
      expect(new Set(orders).size, `duplicate orders in ${collection}/${locale}`).toEqual(
        orders.length,
      );
    }
  }
});

test('getting-started leads with copyable commands', async () => {
  const pages = await loadContentPages('guide');
  const en = pages.find((p) => p.slug === 'getting-started' && p.locale === 'en');
  expect(en).toEqual(expect.anything());
  // The page's primary job: a fenced, copyable install command — not prose.
  // The pinned shape is the install command's scope-plus-tag (the canonical
  // `npm create @openelement@<tag>` alias, which npm resolves to
  // @openelement/create at that tag), the same invariant the install-command
  // gate compares on (www/tools/generate-install-command.ts): runner and
  // flags are the docs' choice, package and tag are the CLI's — the retired
  // Deno `npm:`-specifier spelling stays retired (ADR-0161).
  expect(en.html).toContain('<pre><code class="language-bash">');
  expect(en.html).toContain('@openelement@alpha');
});

// The security page deep-links the configuration anchor; the configuration
// article must produce a heading whose generated id is middleware-use.
test('configuration keeps the middleware-use anchor target', async () => {
  const pages = await loadContentPages('guide');
  const en = pages.find((p) => p.slug === 'configuration' && p.locale === 'en');
  const security = pages.find((p) => p.slug === 'security' && p.locale === 'en');
  expect(en).toEqual(expect.anything());
  expect(security).toEqual(expect.anything());
  expect(en.html).toContain('<h2>middleware.use</h2>');
  expect(security.html).toContain('/guide/configuration#middleware-use');
});

test('content collection loading succeeds for all collections', async () => {
  const count = (await Promise.all(collections.map(loadContentPages))).reduce(
    (total, pages) => total + pages.length,
    0,
  );
  expect(count, 'every route needs en + zh content').toEqual(articleRoutes.length * 2);
});
