/**
 * Client asset manifest protocol (#1471).
 *
 * The structured record of what the client build emits for island delivery:
 * the island client entry URL, one asset per compile-time island identity
 * (delivery tag), and the shared chunk URLs. Identity comes from the build's
 * island declarations joined with the Phase 2 client build manifest
 * (dist/client/.vite/manifest.json) and Rollup module metadata — never from
 * parsing output chunk file names.
 *
 * The request-time artifact dist/server/client-assets.js serializes this
 * record as pure data (no injection logic); the generated server entry reads
 * it at startup through the #951 client-script wiring.
 */

import type { IslandDeliveryStrategy } from './ssg.ts';

/** The client asset one compile-time island identity resolves to. */
export interface ClientIslandAsset {
  /**
   * Emitted asset URL (site-root relative, base-prefixed) of the chunk that
   * carries the island module — its dedicated chunk, a shared chunk, or the
   * client entry when the island has no chunk of its own.
   */
  file: string;
  /** Delivery strategy resolved from the island declaration at build time. */
  strategy: IslandDeliveryStrategy;
  /**
   * True when the island's delivery strategy hydrates at load time, so the
   * asset is a modulepreload candidate.
   */
  preload?: boolean;
}

/** The Phase 2 client build's delivery manifest, keyed by island identity. */
export interface ClientAssetManifest {
  /** The island client entry URL ('' when no client bundle shipped). */
  entry: string;
  /** Compile-time island identity (delivery tag) -> emitted asset. */
  islands: Record<string, ClientIslandAsset>;
  /** Shared chunk URLs emitted by the client build (JS, neither entry nor island-dedicated). */
  shared: string[];
  /**
   * Preloadable island style asset URLs (ADR-0164), sorted, base-prefixed.
   * Shadow-component CSS cannot be applied as a document-level stylesheet —
   * it cannot reach shadow trees — so the document channel's only role for
   * these URLs is preload; the sheets themselves are adopted through the
   * sheet adapters.
   */
  styles: string[];
}

/** The manifest a project without a client bundle carries. */
export const EMPTY_CLIENT_ASSET_MANIFEST: ClientAssetManifest = {
  entry: '',
  islands: {},
  shared: [],
  styles: [],
};

/**
 * Serialize the manifest as the generated dist/server/client-assets.js
 * module: pure structured data, no injection logic — consumers derive what
 * they need from these values.
 */
export function serializeClientAssetsModule(manifest: ClientAssetManifest): string {
  return `// Generated by openElement build — client asset manifest (structured data only).
// entry: the island client entry URL ('' when no client bundle shipped).
// islands: compile-time island identity (delivery tag) -> emitted asset.
// shared: shared chunk URLs emitted by the client build.
// styles: preloadable island style asset URLs (ADR-0164).
export const clientAssets = ${JSON.stringify(manifest, null, 2)};
`;
}
