/**
 * app-shell — compiled layout island (v0.44, ADR-0143).
 *
 * The server entry renders this class around every page
 * (appShell: { tagName, import, props } in vite.config.ts) and injects the
 * page host before the closing tag; the static <slot> projects it. The shell
 * is also a 'load' island: the compiled style scope applies `static styles`
 * when the element activates client-side (the serializer never inlines
 * styles into DSD), so the shell chrome is styled as soon as it hydrates.
 *
 * The compiler grammar v1 has no data-driven per-item attribute slots, so the
 * header nav is static authoring here — edit the links below directly
 * (the vite.config content.nav headerNav indirection of 0.43 is gone).
 */
import { defineIslandConfig } from '@openelement/router';
import { element, OpenElement, property } from '@openelement/element';
import { shellStyles } from '../components/page-styles.ts';

export const openElement = defineIslandConfig({ hydrate: 'load', ssr: true, dsd: true });

@element('app-shell', { root: 'shadow-open' })
export default class AppShell extends OpenElement {
  static override styles = shellStyles;

  /**
   * Filled from appShell.props in vite.config.ts at render time.
   * Attribute-backed (site-name) so the SSR'd value survives the client claim:
   * attribute: false properties reset to their compiled default on claim and
   * the drift check would fail closed.
   */
  @property({ reflect: false })
  siteName = 'openElement';

  render() {
    return (
      <div class='shell-body'>
        <header data-open-layout='app-shell'>
          <div class='bar'>
            <a class='brand' href='/'>{this.siteName}</a>
            <nav>
              <a href='/'>Home</a>
              <a href='/blog'>Blog</a>
            </nav>
          </div>
        </header>
        <main>
          <slot></slot>
        </main>
        <footer>
          <div class='foot'>
            <span>Generated by @openelement/create.</span>
            <a href='https://github.com/open-element/openelement'>GitHub</a>
          </div>
        </footer>
      </div>
    );
  }
}
