// Application-owned multi-handler entry. Nitro remains the sole fetch owner;
// Queue and Cron lifecycle hooks compose around its generated module.
// @ts-ignore generated by `deno task nitro:build` before Wrangler runs
import nitro from './.output-workers/server/index.mjs';
import { createCloudflareHandlers } from './lib/cloudflare-handlers.ts';

export default createCloudflareHandlers(nitro);
