/**
 * @openelement/adapter-vite/i18n-plugin - Node-only Vite plugin for i18n
 *
 * Build-time Vite plugin, allowed to use node:*.
 *
 * File-system access (cwd / mkdirSync / writeFileSync) goes through the
 * injected FileSystemAdapter (default: nodeFsAdapter); path joining still
 * uses node:path directly. This module MUST NOT be imported from the main
 * @openelement/router entry to avoid pulling Node built-ins into client island
 * bundles.
 *
 * Standalone usage requires explicit ctx parameter:
 * ```ts
 * openI18n({ locales: ['en', 'zh'], defaultLocale: 'en', ctx });  // ctx must be explicitly passed
 * ```
 */

import type { Plugin } from 'vite';
import type { OpenElementBuildContextLike } from './internal/protocol/framework.ts';
import { createLogger } from '@openelement/element';
import { join } from 'node:path';
import { type FileSystemAdapter, nodeFsAdapter } from './internal/content/fs-adapter.ts';
import { DEFAULT_DATA_DIR } from './internal/paths.ts';
import { loadI18nData } from '@openelement/router/i18n';
import type { OpenElementI18nOptions } from '@openelement/router/i18n';

const log = createLogger('i18n');

// ─── Data utilities (node-only) ───────────────────────────────────

/**
 * Generate TypeScript module source code for i18n configuration.
 * The output is a self-contained .ts file that exports locales,
 * defaultLocale, and helper functions.
 *
 * SOP-001: Virtual Modules Removal — replaces @openelement/generated/i18n.
 *
 * @param locales - Array of locale code strings (e.g. ['en', 'zh'])
 * @param defaultLocale - Default locale code (e.g. 'en')
 * @returns TypeScript module source string
 */
function writeI18nDataModule(locales: string[], defaultLocale: string): string {
  return [
    '// Auto-generated by @openelement/adapter-vite/i18n — do not edit',
    `export const locales = ${JSON.stringify(locales)};`,
    `export const defaultLocale = ${JSON.stringify(defaultLocale)};`,
    '',
    'export function getDefaultLocale(): string { return defaultLocale; }',
  ].join('\n') + '\n';
}

// ─── Vite plugin ─────────────────────────────────────────────────

/**
 * openElement i18n Vite plugin.
 * Configures locale options for route-level i18n helpers.
 */
export function openI18n(
  options: OpenElementI18nOptions & { ctx?: OpenElementBuildContextLike; fs?: FileSystemAdapter },
): Plugin {
  // ctx must be explicitly provided (via openElement() umbrella or direct param)
  const ctx = options.ctx;
  // File-system injection matches the blog/nav content plugins (#847): tests
  // can pass an in-memory adapter instead of touching the real disk.
  const fs = options.fs ?? nodeFsAdapter;

  return {
    name: 'open:i18n',

    buildStart() {
      // ADR 0018: Use loadI18nData() pure function - zero module state
      const i18nData = loadI18nData(options);

      // Write i18n options to ctx (shared build context)
      // The @openelement/generated/i18n plugin reads ctx.plugins.i18nOptions in its load() hook
      if (ctx) {
        ctx.registerPlugin('i18nOptions', {
          locales: i18nData.locales,
          defaultLocale: i18nData.defaultLocale,
        });
      }

      // SOP-001: Write generated i18n data module to disk.
      // Failing to write must fail the build: consumers import these files.
      const dataDir = join(fs.cwd(), DEFAULT_DATA_DIR);
      fs.mkdirSync(dataDir, { recursive: true });
      const i18nModule = writeI18nDataModule(i18nData.locales, i18nData.defaultLocale);
      fs.writeFileSync(join(dataDir, '_generated-i18n-data.ts'), i18nModule, 'utf-8');
      log.info(`I18n: wrote _generated-i18n-data.ts (${i18nData.locales.join(', ')})`);

      log.info(`${options.locales.join(', ')} (default: ${options.defaultLocale})`);
    },
  };
}

// Use @openelement/router/i18n for runtime helpers: loadI18nData, normalizeLocalePath

export default openI18n;
